export function generateBounceIn(props: Record<string, unknown>): string {
  const delay = (props.delay as number) ?? 0
  const scale = (props.scale as number) ?? 0.7
  const stiffness = (props.stiffness as number) ?? 400
  const damping = (props.damping as number) ?? 10
  const once = (props.once as boolean) ?? true

  return `// ForgeBounceIn.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-motion update bounce-in

'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

interface ForgeBounceInProps {
  children: React.ReactNode
  delay?: number
  scale?: number
  stiffness?: number
  damping?: number
  once?: boolean
}

export function ForgeBounceIn({
  children,
  delay = ${delay},
  scale = ${scale},
  stiffness = ${stiffness},
  damping = ${damping},
  once = ${once},
}: ForgeBounceInProps) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, scale }}
      animate={inView ? { opacity: 1, scale: 1 } : { opacity: 0, scale }}
      transition={{ type: 'spring', stiffness, damping, delay }}
    >
      {children}
    </motion.div>
  )
}
`
}
