export function generateCountUp(props: Record<string, unknown>): string {
  const from = (props.from as number) ?? 0
  const to = (props.to as number) ?? 100
  const duration = (props.duration as number) ?? 1.5
  const once = (props.once as boolean) ?? true

  return `// ForgeCountUp.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update count-up

'use client'

import { useRef, useEffect } from 'react'
import { useInView, useMotionValue, useTransform, animate, motion } from 'framer-motion'

interface ForgeCountUpProps {
  from?: number
  to?: number
  duration?: number
  once?: boolean
}

export function ForgeCountUp({
  from = ${from},
  to = ${to},
  duration = ${duration},
  once = ${once},
}: ForgeCountUpProps) {
  const ref = useRef<HTMLSpanElement>(null)
  const inView = useInView(ref, { once, amount: 0.5 })
  const count = useMotionValue(from)
  const rounded = useTransform(count, (v) => Math.round(v))
  const prefersReduced =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  useEffect(() => {
    if (!inView) return
    count.set(from)
    const controls = animate(count, to, {
      duration: prefersReduced ? 0 : duration,
      ease: 'easeOut',
    })
    return () => controls.stop()
  }, [inView, from, to, duration, prefersReduced, count])

  return <motion.span ref={ref}>{rounded}</motion.span>
}
`
}
