export function generateFadeDown(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 0.6
  const delay = (props.delay as number) ?? 0
  const distance = (props.distance as number) ?? 32
  const ease = (props.ease as string) ?? 'easeOut'
  const once = (props.once as boolean) ?? true

  return `// ForgeFadeDown.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update fade-down

'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

interface ForgeFadeDownProps {
  children: React.ReactNode
  duration?: number
  delay?: number
  distance?: number
  ease?: string
  once?: boolean
}

export function ForgeFadeDown({
  children,
  duration = ${duration},
  delay = ${delay},
  distance = ${distance},
  ease = '${ease}',
  once = ${once},
}: ForgeFadeDownProps) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: -distance }}
      animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: -distance }}
      transition={{ duration, delay, ease }}
    >
      {children}
    </motion.div>
  )
}
`
}
