export function generateFadeIn(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 0.6
  const delay = (props.delay as number) ?? 0
  const ease = (props.ease as string) ?? 'easeOut'
  const once = (props.once as boolean) ?? true

  return `// ForgeFadeIn.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update fade-in

'use client'

import type { ReactNode } from 'react'
import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

interface ForgeFadeInProps {
  children: ReactNode
  duration?: number
  delay?: number
  ease?: string
  once?: boolean
}

export function ForgeFadeIn({
  children,
  duration = ${duration},
  delay = ${delay},
  ease = '${ease}',
  once = ${once},
}: ForgeFadeInProps) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })
  const prefersReduced =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  return (
    <motion.div
      ref={ref}
      initial={prefersReduced ? false : { opacity: 0 }}
      animate={prefersReduced ? { opacity: 1 } : inView ? { opacity: 1 } : { opacity: 0 }}
      transition={prefersReduced ? { duration: 0 } : { duration, delay, ease }}
    >
      {children}
    </motion.div>
  )
}
`
}
