export function generateFloat(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 3
  const distance = (props.distance as number) ?? 12

  return `// ForgeFloat.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update float

'use client'

import { motion } from 'framer-motion'
import type { ReactNode } from 'react'

interface ForgeFloatProps {
  children: ReactNode
  duration?: number
  distance?: number
}

export function ForgeFloat({
  children,
  duration = ${duration},
  distance = ${distance},
}: ForgeFloatProps) {
  const prefersReduced =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  return (
    <motion.div
      animate={prefersReduced ? { y: 0 } : { y: [0, -distance, 0] }}
      transition={prefersReduced ? { duration: 0 } : { duration, repeat: Infinity, ease: 'easeInOut' }}
    >
      {children}
    </motion.div>
  )
}
`
}
