export function generateFloat(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 3
  const distance = (props.distance as number) ?? 12

  return `// ForgeFloat.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-motion update float

'use client'

import { motion } from 'framer-motion'

interface ForgeFloatProps {
  children: React.ReactNode
  duration?: number
  distance?: number
}

export function ForgeFloat({
  children,
  duration = ${duration},
  distance = ${distance},
}: ForgeFloatProps) {
  return (
    <motion.div
      animate={{ y: [0, -distance, 0] }}
      transition={{ duration, repeat: Infinity, ease: 'easeInOut' }}
    >
      {children}
    </motion.div>
  )
}
`
}
