export function generateParallax(props: Record<string, unknown>): string {
  const speed = (props.speed as number) ?? 0.3

  return `// ForgeParallax.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update parallax

'use client'

import type { ReactNode } from 'react'
import { useRef } from 'react'
import { motion, useScroll, useTransform } from 'framer-motion'

interface ForgeParallaxProps {
  children: ReactNode
  speed?: number
}

export function ForgeParallax({
  children,
  speed = ${speed},
}: ForgeParallaxProps) {
  const ref = useRef<HTMLDivElement>(null)
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ['start end', 'end start'],
  })
  const y = useTransform(
    scrollYProgress,
    [0, 1],
    [\`\${speed * -100}px\`, \`\${speed * 100}px\`]
  )
  const prefersReduced =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  return (
    <div ref={ref} style={{ overflow: 'hidden' }}>
      <motion.div style={{ y: prefersReduced ? 0 : y }}>
        {children}
      </motion.div>
    </div>
  )
}
`
}
