export function generatePulse(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 2
  const scale = (props.scale as number) ?? 1.05

  return `// ForgePulse.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-motion update pulse

'use client'

import { motion } from 'framer-motion'

interface ForgePulseProps {
  children: React.ReactNode
  duration?: number
  scale?: number
}

export function ForgePulse({
  children,
  duration = ${duration},
  scale = ${scale},
}: ForgePulseProps) {
  return (
    <motion.div
      animate={{ scale: [1, scale, 1] }}
      transition={{ duration, repeat: Infinity, ease: 'easeInOut' }}
    >
      {children}
    </motion.div>
  )
}
`
}
