export function generatePulse(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 2
  const scale = (props.scale as number) ?? 1.05

  return `// ForgePulse.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update pulse

'use client'

import { motion } from 'framer-motion'
import type { ReactNode } from 'react'

interface ForgePulseProps {
  children: ReactNode
  duration?: number
  scale?: number
}

export function ForgePulse({
  children,
  duration = ${duration},
  scale = ${scale},
}: ForgePulseProps) {
  const prefersReduced =
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-reduced-motion: reduce)').matches
      : false

  return (
    <motion.div
      animate={prefersReduced ? { scale: 1 } : { scale: [1, scale, 1] }}
      transition={prefersReduced ? { duration: 0 } : { duration, repeat: Infinity, ease: 'easeInOut' }}
    >
      {children}
    </motion.div>
  )
}
`
}
