export function generateReveal(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 0.7
  const delay = (props.delay as number) ?? 0
  const ease = (props.ease as string) ?? 'easeOut'
  const once = (props.once as boolean) ?? true

  return `// ForgeReveal.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-motion update reveal

'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

interface ForgeRevealProps {
  children: React.ReactNode
  duration?: number
  delay?: number
  ease?: string
  once?: boolean
}

export function ForgeReveal({
  children,
  duration = ${duration},
  delay = ${delay},
  ease = '${ease}',
  once = ${once},
}: ForgeRevealProps) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })

  return (
    // overflow:hidden is required for the clip-path to mask correctly
    <div style={{ overflow: 'hidden' }}>
      <motion.div
        ref={ref}
        initial={{ clipPath: 'inset(0 100% 0 0)' }}
        animate={inView ? { clipPath: 'inset(0 0% 0 0)' } : { clipPath: 'inset(0 100% 0 0)' }}
        transition={{ duration, delay, ease }}
      >
        {children}
      </motion.div>
    </div>
  )
}
`
}
