export function generateSlideInRight(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 0.6
  const delay = (props.delay as number) ?? 0
  const distance = (props.distance as number) ?? 48
  const ease = (props.ease as string) ?? 'easeOut'
  const once = (props.once as boolean) ?? true

  return `// ForgeSlideInRight.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-motion update slide-in-right

'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

interface ForgeSlideInRightProps {
  children: React.ReactNode
  duration?: number
  delay?: number
  distance?: number
  ease?: string
  once?: boolean
}

export function ForgeSlideInRight({
  children,
  duration = ${duration},
  delay = ${delay},
  distance = ${distance},
  ease = '${ease}',
  once = ${once},
}: ForgeSlideInRightProps) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })

  return (
    <div style={{ overflow: 'hidden' }}>
      <motion.div
        ref={ref}
        initial={{ opacity: 0, x: distance }}
        animate={inView ? { opacity: 1, x: 0 } : { opacity: 0, x: distance }}
        transition={{ duration, delay, ease }}
      >
        {children}
      </motion.div>
    </div>
  )
}
`
}
