export function generateStagger(props: Record<string, unknown>): string {
  const duration = (props.duration as number) ?? 0.5
  const delay = (props.delay as number) ?? 0
  const staggerDelay = (props.staggerDelay as number) ?? 0.1
  const distance = (props.distance as number) ?? 24
  const ease = (props.ease as string) ?? 'easeOut'
  const once = (props.once as boolean) ?? true

  return `// ForgeStagger.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update stagger

'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'

interface ForgeStaggerProps {
  children: React.ReactNode
  duration?: number
  delay?: number
  staggerDelay?: number
  distance?: number
  ease?: string
  once?: boolean
}

export function ForgeStagger({
  children,
  duration = ${duration},
  delay = ${delay},
  staggerDelay = ${staggerDelay},
  distance = ${distance},
  ease = '${ease}',
  once = ${once},
}: ForgeStaggerProps) {
  const ref = useRef<HTMLDivElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })

  return (
    <div ref={ref}>
      {React.Children.toArray(children).map((child, i) => (
        <motion.div
          key={i}
          initial={{ opacity: 0, y: distance }}
          animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: distance }}
          transition={{ duration, ease, delay: delay + i * staggerDelay }}
        >
          {child}
        </motion.div>
      ))}
    </div>
  )
}
`
}
