export function generateTypewriter(props: Record<string, unknown>): string {
  const text = (props.text as string) ?? 'Interfaces built to a standard you can feel.'
  const speed = (props.speed as number) ?? 40
  const once = (props.once as boolean) ?? true

  return `// ForgeTypewriter.tsx — generated by forge-motion CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/motion update typewriter

'use client'

import { useRef, useState, useEffect } from 'react'
import { useInView } from 'framer-motion'

interface ForgeTypewriterProps {
  text?: string
  speed?: number
  once?: boolean
}

export function ForgeTypewriter({
  text = ${JSON.stringify(text)},
  speed = ${speed},
  once = ${once},
}: ForgeTypewriterProps) {
  const ref = useRef<HTMLSpanElement>(null)
  const inView = useInView(ref, { once, amount: 0.3 })
  const [displayed, setDisplayed] = useState('')

  useEffect(() => {
    if (!inView) return
    setDisplayed('')
    let i = 0
    const interval = setInterval(() => {
      i++
      setDisplayed(text.slice(0, i))
      if (i >= text.length) clearInterval(interval)
    }, speed)
    return () => clearInterval(interval)
  }, [inView, text, speed])

  return <span ref={ref}>{displayed}</span>
}
`
}
