import fs from 'fs-extra'
import path from 'path'
import pc from 'picocolors'
import { readConfig, writeConfig, createDefaultConfig } from '../config.js'

export async function runInit(): Promise<void> {
  console.log(pc.bold('\n  forge-ui init\n'))

  // Don't overwrite an existing config
  const existing = await readConfig()
  if (existing) {
    console.log(pc.yellow('  forge.config.json already exists — skipping.'))
    console.log(pc.dim('  Run npx forge-ui add <component> to add components.\n'))
    return
  }

  const config = createDefaultConfig()
  await writeConfig(config)

  // Create the tokens CSS file
  const outputDir = path.join(process.cwd(), config.output)
  await fs.ensureDir(outputDir)
  const tokensPath = path.join(outputDir, 'forge-tokens.css')

  const tokens = `/* forge-tokens.css — generated by forge-ui CLI */
/* Import this in your root layout: import '@/components/forge/forge-tokens.css' */
/* Override any token to retheme your entire installation. */

:root {
  /* Backgrounds */
  --forge-bg:     #09090b;
  --forge-bg2:    #0f0f12;
  --forge-bg3:    #141418;

  /* Text */
  --forge-text:   #f0ede8;
  --forge-muted:  rgba(240, 237, 232, 0.38);
  --forge-hint:   rgba(240, 237, 232, 0.15);

  /* Spectrum palette */
  --forge-purple: #7F77DD;
  --forge-blue:   #378ADD;
  --forge-red:    #e24b4a;
  --forge-amber:  #EF9F27;
  --forge-teal:   #1D9E75;
  --forge-pink:   #D4537E;

  /* Typography */
  --forge-font:   'Inter', sans-serif;
  --forge-mono:   'DM Mono', monospace;
}
`

  await fs.writeFile(tokensPath, tokens, 'utf8')

  console.log(pc.green('  ✓') + ' forge.config.json')
  console.log(pc.green('  ✓') + ` ${config.output}/forge-tokens.css`)
  console.log(pc.dim('\n  Next: import the tokens in your root layout'))
  console.log(pc.cyan(`  import '@/components/forge/forge-tokens.css'\n`))
}
