import type { PropDefaultsMap } from "./types";

export const PROP_DEFAULTS: PropDefaultsMap = {
  button: {
    text: "Start a project",
    variant: "glow",
    size: "md",
    color: "#7F77DD",
    textSize: 13,
    weight: "400",
    radius: 8,
    paddingX: 20,
    paddingY: 10,
    icon: "none",
    iconPos: "left",
    hoverEffect: "lift",
    clickAnim: "ripple",
    shadow: "glow",
    letterSpacing: "-.01em",
    uppercase: false,
    fullWidth: false,
    disabled: false,
  },
  card: {
    title: "Design engineering",
    subtitle: "Interfaces built to a standard you can feel.",
    tag: "01",
    badge: "New",
    color: "#7F77DD",
    radius: 12,
    padding: 24,
    showTag: true,
    showBadge: false,
    width: 280,
  },
  input: {
    label: "Email address",
    placeholder: "hello@forgelabs.dev",
    hint: "We never share your email.",
    state: "default",
    color: "#7F77DD",
    radius: 8,
    size: "md",
    showLabel: true,
    showHint: true,
    type: "text",
  },
  badge: {
    text: "Open for work",
    color: "#1D9E75",
    variant: "pill",
    size: "md",
    showDot: true,
    dotPulse: true,
    uppercase: false,
  },
  toggle: {
    label: "Dark mode",
    checked: true,
    color: "#7F77DD",
    size: "md",
    showLabel: true,
    labelPos: "right",
  },
  select: {
    label: "Project type",
    placeholder: "Choose…",
    options: ["Landing page", "Website", "SaaS app", "Consultation"],
    color: "#7F77DD",
    hoverColor: "#7F77DD",
    radius: 8,
    size: "md",
    showLabel: true,
  },
  checkbox: {
    items: [
      "I agree to the terms",
      "Subscribe to updates",
      "Agree to privacy policy",
    ],
    checked: true,
    color: "#7F77DD",
    size: "md",
    variant: "square",
  },
  radio: {
    label: "Timeline",
    options: ["ASAP", "1–2 months", "3–6 months", "Flexible"],
    selected: 0,
    color: "#7F77DD",
    size: "md",
    layout: "vertical",
  },
  slider: {
    label: "Budget",
    min: 0,
    max: 20000,
    value: 8000,
    step: 500,
    color: "#7F77DD",
    showValue: true,
    unit: "£",
    size: "md",
  },
  textarea: {
    label: "Project brief",
    placeholder: "Tell me about what you're building…",
    hint: "The more detail the better.",
    rows: 4,
    color: "#7F77DD",
    radius: 8,
    showLabel: true,
    showHint: true,
    maxLength: 500,
    showCount: true,
  },
  avatar: {
    initials: "FL",
    color: "#7F77DD",
    size: "lg",
    shape: "circle",
    showStatus: true,
    status: "online",
    showRing: false,
  },
  statcard: {
    title: "Monthly revenue",
    value: "£48,200",
    delta: "+12.4%",
    deltaDir: "up",
    color: "#7F77DD",
    icon: "↑",
    showIcon: true,
    showDelta: true,
    showBar: true,
    barValue: 72,
  },
  taginput: {
    tags: ["Next.js", "TypeScript", "Tailwind"],
    placeholder: "Add tag…",
    color: "#7F77DD",
    variant: "soft",
    removable: true,
  },
  datepicker: {
    label: "Project start",
    color: "#7F77DD",
    radius: 8,
    showLabel: true,
    selectedDate: "2025-03-15",
  },
  spinner: {
    variant: "ring",
    color: "#7F77DD",
    size: "md",
    speed: "normal",
    showLabel: false,
    label: "Loading…",
  },
  fadeup: {
    text: "Interfaces built\nto a standard\nyou can feel.",
    color: "#7F77DD",
    duration: 600,
    stagger: true,
  },
  ticker: {
    items: ["Landing pages", "Websites", "SaaS apps", "Open source"],
    speed: "normal",
    color: "#7F77DD",
    separator: "—",
    gap: 48,
    pauseOnHover: true,
  },
  morphblob: {
    color: "#7F77DD",
    size: 120,
    speed: "normal",
    opacity: 0.8,
    blur: 0,
    gradient: true,
    color2: "#D4537E",
  },
  countup: {
    from: 0,
    to: 48200,
    prefix: "£",
    suffix: "",
    duration: 2000,
    color: "#7F77DD",
    size: "xl",
    label: "Total revenue",
    showLabel: true,
  },
  barchart: {
    title: "Monthly revenue",
    color: "#7F77DD",
    color2: "#378ADD",
    radius: 4,
    showGrid: true,
    showLegend: true,
    animated: true,
    data: [],
  },
  linechart: {
    title: "Visitor growth",
    color: "#1D9E75",
    color2: "#EF9F27",
    tension: 0.4,
    fill: true,
    showGrid: true,
    showDots: true,
    animated: true,
    data: [],
  },
  donut: {
    title: "Traffic sources",
    color: "#7F77DD",
    showLabels: true,
    showCenter: true,
    centerText: "24.1k",
    thickness: 28,
    animated: true,
    data: [],
  },
  progress: {
    label: "Completion",
    value: 72,
    color: "#7F77DD",
    radius: 4,
    height: 6,
    showLabel: true,
    showValue: true,
    striped: false,
  },
  sparkline: {
    color: "#7F77DD",
    fill: true,
    variant: "line",
    showDot: true,
    height: 60,
    animated: true,
    data: [],
  },
  cmdpalette: {
    placeholder: "Search components, docs, pages…",
    color: "#7F77DD",
    showCategories: true,
    showShortcuts: true,
    items: [
      "Components:Button",
      "Components:Card",
      "Components:Input",
      "Actions:Copy command",
      "Actions:Export",
    ],
  },
  navbar: {
    brand: "FORGE.labs",
    links: ["Work", "About", "Services", "Contact"],
    color: "#7F77DD",
    variant: "dark",
    showCta: true,
    ctaText: "Start project",
    showLogo: true,
  },
  breadcrumb: {
    items: "Home,Components,Button",
    color: "#7F77DD",
    separator: "/",
    showHome: true,
  },
  pagination: {
    total: 48,
    perPage: 10,
    current: 3,
    color: "#7F77DD",
    showCount: true,
    showArrows: true,
  },
  sidenav: {
    brand: "FORGE.ui",
    items: [
      "◎,Dashboard",
      "⊞,Components",
      "╱,Charts",
      "↑,Motion",
      "⚙,Settings",
    ],
    color: "#7F77DD",
    collapsed: false,
    showIcons: true,
    active: 1,
  },
  tabs: {
    tabs: ["Overview", "Features", "Pricing", "Docs"],
    active: 0,
    color: "#7F77DD",
    variant: "underline",
  },
  modal: {
    title: "Got something worth building?",
    body: "Drop a message and let's figure out if we're the right fit.",
    color: "#7F77DD",
    radius: 12,
    showClose: true,
    showFooter: true,
    primaryBtn: "Start a project",
    secondaryBtn: "Maybe later",
  },
  toast: {
    title: "Project enquiry sent",
    message: "We'll get back to you within 24 hours.",
    variant: "success",
    showIcon: true,
    showClose: true,
  },
  tooltip: {
    text: "Hover me",
    tip: "Opens in a new tab",
    color: "#7F77DD",
    variant: "dark",
  },
  dropdown: {
    label: "Options",
    items: ["Edit", "Duplicate", "Share", "Archive", "Delete"],
    dangerItems: [false, false, false, false, true],
    color: "#7F77DD",
    radius: 8,
    showDivider: true,
  },
  drawer: {
    title: "Project details",
    body: "Drawer content goes here. Forms, navigation, settings, or anything you need.",
    color: "#7F77DD",
    side: "right",
    showOverlay: true,
    width: 240,
  },
  skeleton: {
    variant: "card",
    lines: 3,
    color: "#7F77DD",
    animated: true,
    radius: 8,
  },
  alert: {
    title: "Deployment successful",
    message: "Your changes are live at forgelabs.dev",
    variant: "success",
    color: "#1D9E75",
    showIcon: true,
    showClose: true,
    showAction: false,
    actionText: "View site",
  },
  stepper: {
    steps: ["Details", "Design", "Review", "Launch"],
    descs: [
      "Choose your setup.",
      "We handle the build.",
      "Review before sign-off.",
      "Your project is live.",
    ],
    current: 1,
    color: "#7F77DD",
    variant: "horizontal",
    showDesc: true,
  },
  accordion: {
    items: [
      "What do you build?",
      "How long does it take?",
      "What does it cost?",
    ],
    bodies: [
      "Landing pages, marketing websites, SaaS products and web apps.",
      "Most projects take 4–12 weeks depending on scope.",
      "From £2,400 for landing pages to £8,000+ for SaaS products.",
    ],
    color: "#7F77DD",
    radius: 8,
  },
  table: {
    caption: "Recent projects",
    color: "#7F77DD",
    showStripes: true,
    showHover: true,
    compact: false,
    columns: ["Project", "Type", "Status"],
  },
};
