// ForgeCard — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update card

import './ForgeCard.css'

function hexToRgb(hex: string): string {
  const h = hex.replace('#', '')
  const r = parseInt(h.substring(0, 2), 16)
  const g = parseInt(h.substring(2, 4), 16)
  const b = parseInt(h.substring(4, 6), 16)
  return `${r}, ${g}, ${b}`
}

interface ForgeCardProps {
  title?: string
  subtitle?: string
  tag?: string
  badge?: string
  color?: string
  radius?: number
  padding?: number
  showTag?: boolean
  showBadge?: boolean
  showGlow?: boolean
  width?: number | string
  children?: React.ReactNode
  onClick?: () => void
}

export function ForgeCard({
  title = 'Card title',
  subtitle = 'Card subtitle or description text goes here.',
  tag,
  badge,
  color = '#7F77DD',
  radius = 12,
  padding = 24,
  showTag = true,
  showBadge = false,
  showGlow = true,
  width,
  children,
  onClick,
}: ForgeCardProps) {
  return (
    <div
      className={`forge-card${showGlow ? ' forge-card--glow' : ''}${onClick ? ' forge-card--clickable' : ''}`}
      style={{
        '--forge-card-color': color,
        '--forge-card-rgb': hexToRgb(color),
        borderRadius: radius,
        padding,
        width,
      } as React.CSSProperties}
      onClick={onClick}
    >
      {showTag && tag && <div className="forge-card__tag">{tag}</div>}
      <div className="forge-card__body">
        <div className="forge-card__title">{title}</div>
        {subtitle && <div className="forge-card__subtitle">{subtitle}</div>}
        {children}
      </div>
      {showBadge && badge && <div className="forge-card__badge">{badge}</div>}
      {showGlow && <div className="forge-card__glow" />}
    </div>
  )
}
