// ForgeBreadcrumb — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update breadcrumb

import './ForgeBreadcrumb.css'

interface ForgeBreadcrumbProps {
  items: { label: string; href?: string }[]
  color?: string
  separator?: string
  showHome?: boolean
}

export function ForgeBreadcrumb({
  items = [{ label: 'Home', href: '/' }, { label: 'Components' }, { label: 'Button' }],
  color = '#7F77DD',
  separator = '/',
  showHome = true,
}: ForgeBreadcrumbProps) {
  const all = showHome && items[0]?.label !== 'Home'
    ? [{ label: 'Home', href: '/' }, ...items]
    : items

  return (
    <nav
      className="forge-breadcrumb"
      aria-label="Breadcrumb"
      style={{ '--forge-breadcrumb-color': color, '--forge-breadcrumb-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      <ol className="forge-breadcrumb__list">
        {all.map((item, i) => {
          const isLast = i === all.length - 1
          return (
            <li key={i} className="forge-breadcrumb__item">
              {i > 0 && (
                <span className="forge-breadcrumb__sep" aria-hidden="true">
                  {separator}
                </span>
              )}
              {item.href && !isLast ? (
                <a href={item.href} className="forge-breadcrumb__link">
                  {item.label}
                </a>
              ) : (
                <span className={`forge-breadcrumb__current${isLast ? ' forge-breadcrumb__current--active' : ''}`}>
                  {item.label}
                </span>
              )}
            </li>
          )
        })}
      </ol>
    </nav>
  )
}
