// ForgeSlider — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update slider

import { useState } from 'react'
import './ForgeSlider.css'

interface ForgeSliderProps {
  label?: string
  min?: number
  max?: number
  step?: number
  value?: number
  color?: string
  showValue?: boolean
  unit?: string
  onChange?: (value: number) => void
}

export function ForgeSlider({
  label = 'Value',
  min = 0,
  max = 100,
  step = 1,
  value,
  color = '#7F77DD',
  showValue = true,
  unit = '',
  onChange,
}: ForgeSliderProps) {
  const [internal, setInternal] = useState(50)
  const controlled = value !== undefined
  const current = controlled ? value : internal
  const pct = ((current - min) / (max - min)) * 100

  return (
    <div
      className="forge-slider-wrap"
      style={{ '--forge-slider-color': color, '--forge-slider-rgb': '127, 119, 221', '--forge-slider-pct': `${pct}%` } as React.CSSProperties}
    >
      <div className="forge-slider-header">
        <span className="forge-slider-label">{label}</span>
        {showValue && (
          <span className="forge-slider-value">{unit}{current}</span>
        )}
      </div>
      <input
        type="range"
        className="forge-slider"
        min={min}
        max={max}
        step={step}
        value={current}
        onChange={e => {
          const v = Number(e.target.value)
          if (!controlled) setInternal(v)
          onChange?.(v)
        }}
      />
    </div>
  )
}
