// ForgeAccordion — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update accordion

import { useState } from 'react'
import './ForgeAccordion.css'

interface ForgeAccordionProps {
  items?: string[]
  bodies?: string[]
  color?: string
  radius?: number
  allowMultiple?: boolean
}

export function ForgeAccordion({
  items = ["Question one","Question two"],
  bodies = ["Answer one.","Answer two."],
  color = '#7F77DD',
  radius = 8,
  allowMultiple = false,
}: ForgeAccordionProps) {
  const [open, setOpen] = useState<number[]>([])

  function toggle(i: number) {
    if (allowMultiple) {
      setOpen(o => o.includes(i) ? o.filter(x => x !== i) : [...o, i])
    } else {
      setOpen(o => o.includes(i) ? [] : [i])
    }
  }

  return (
    <div
      className="forge-accordion"
      style={{ '--forge-accordion-color': color, '--forge-accordion-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      {items.map((item, i) => {
        const isOpen = open.includes(i)
        return (
          <div key={i} className={`forge-accordion__item${isOpen ? ' forge-accordion__item--open' : ''}`} style={{ borderRadius: radius }}>
            <button
              className="forge-accordion__trigger"
              onClick={() => toggle(i)}
              aria-expanded={isOpen}
            >
              <span>{item}</span>
              <span className={`forge-accordion__arrow${isOpen ? ' forge-accordion__arrow--open' : ''}`}>▾</span>
            </button>
            {isOpen && (
              <div className="forge-accordion__body">
                {bodies[i] ?? ''}
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
