// ForgeBadge — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update badge

import './ForgeBadge.css'

function hexToRgb(hex: string): string {
  const h = hex.replace('#', '')
  const r = parseInt(h.substring(0, 2), 16)
  const g = parseInt(h.substring(2, 4), 16)
  const b = parseInt(h.substring(4, 6), 16)
  return `${r}, ${g}, ${b}`
}

interface ForgeBadgeProps {
  children: React.ReactNode
  color?: string
  variant?: 'pill' | 'tag' | 'square'
  size?: 'sm' | 'md' | 'lg'
  showDot?: boolean
  dotPulse?: boolean
  uppercase?: boolean
}

export function ForgeBadge({
  children,
  color = '#7F77DD',
  variant = 'pill',
  size = 'md',
  showDot = true,
  dotPulse = true,
  uppercase = false,
}: ForgeBadgeProps) {
  return (
    <span
      className={`forge-badge forge-badge--${variant} forge-badge--${size}`}
      style={{
        '--forge-badge-color': color,
        '--forge-badge-rgb': hexToRgb(color),
        textTransform: uppercase ? 'uppercase' : 'none',
      } as React.CSSProperties}
    >
      {showDot && (
        <span className={`forge-badge__dot${dotPulse ? ' forge-badge__dot--pulse' : ''}`} />
      )}
      {children}
    </span>
  )
}
