// ForgeTooltip — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update tooltip

import { useState } from 'react'
import './ForgeTooltip.css'

interface ForgeTooltipProps {
  tip: string
  children: React.ReactNode
  color?: string
  variant?: 'dark' | 'light'
  position?: 'top' | 'bottom' | 'left' | 'right'
}

export function ForgeTooltip({
  tip,
  children,
  color = '#7F77DD',
  variant = 'dark',
  position = 'top',
}: ForgeTooltipProps) {
  const [visible, setVisible] = useState(false)

  return (
    <span
      className="forge-tooltip-wrap"
      style={{ '--forge-tooltip-color': color, '--forge-tooltip-rgb': '127, 119, 221' } as React.CSSProperties}
      onMouseEnter={() => setVisible(true)}
      onMouseLeave={() => setVisible(false)}
      onFocus={() => setVisible(true)}
      onBlur={() => setVisible(false)}
    >
      {children}
      {visible && (
        <span className={`forge-tooltip forge-tooltip--${variant} forge-tooltip--${position}`} role="tooltip">
          {tip}
        </span>
      )}
    </span>
  )
}
