// ForgePagination — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update pagination

import { useState } from 'react'
import './ForgePagination.css'

interface ForgePaginationProps {
  total?: number
  perPage?: number
  color?: string
  showCount?: boolean
  showArrows?: boolean
  page?: number
  onPageChange?: (page: number) => void
}

export function ForgePagination({
  total = 48,
  perPage = 10,
  color = '#7F77DD',
  showCount = true,
  showArrows = true,
  page,
  onPageChange,
}: ForgePaginationProps) {
  const [internal, setInternal] = useState(1)
  const controlled = page !== undefined
  const current = controlled ? page : internal
  const totalPages = Math.ceil(total / perPage)

  function go(p: number) {
    if (p < 1 || p > totalPages) return
    if (!controlled) setInternal(p)
    onPageChange?.(p)
  }

  // Build page number list with ellipsis
  function getPages(): (number | '...')[] {
    if (totalPages <= 7) return Array.from({ length: totalPages }, (_, i) => i + 1)
    if (current <= 4) return [1, 2, 3, 4, 5, '...', totalPages]
    if (current >= totalPages - 3) return [1, '...', totalPages - 4, totalPages - 3, totalPages - 2, totalPages - 1, totalPages]
    return [1, '...', current - 1, current, current + 1, '...', totalPages]
  }

  const start = (current - 1) * perPage + 1
  const end = Math.min(current * perPage, total)

  return (
    <div
      className="forge-pagination"
      style={{ '--forge-pagination-color': color, '--forge-pagination-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      {showCount && (
        <span className="forge-pagination__count">
          {start}–{end} of {total}
        </span>
      )}
      <div className="forge-pagination__pages">
        {showArrows && (
          <button
            className="forge-pagination__btn forge-pagination__arrow"
            onClick={() => go(current - 1)}
            disabled={current === 1}
            aria-label="Previous page"
          >
            ←
          </button>
        )}
        {getPages().map((p, i) =>
          p === '...' ? (
            <span key={`ellipsis-${i}`} className="forge-pagination__ellipsis">…</span>
          ) : (
            <button
              key={p}
              className={`forge-pagination__btn${current === p ? ' forge-pagination__btn--active' : ''}`}
              onClick={() => go(p as number)}
              aria-current={current === p ? 'page' : undefined}
            >
              {p}
            </button>
          )
        )}
        {showArrows && (
          <button
            className="forge-pagination__btn forge-pagination__arrow"
            onClick={() => go(current + 1)}
            disabled={current === totalPages}
            aria-label="Next page"
          >
            →
          </button>
        )}
      </div>
    </div>
  )
}
