// ForgeCountUp — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update countup
// Uses requestAnimationFrame — no animation library required.

import { useEffect, useRef, useState } from 'react'
import './ForgeCountUp.css'

interface ForgeCountUpProps {
  from?: number
  to?: number
  duration?: number
  prefix?: string
  suffix?: string
  color?: string
  size?: 'sm' | 'md' | 'lg' | 'xl'
  showLabel?: boolean
  label?: string
}

export function ForgeCountUp({
  from = 0,
  to = 48200,
  duration = 2000,
  prefix = '',
  suffix = '',
  color = '#7F77DD',
  size = 'xl',
  showLabel = true,
  label = 'Total',
}: ForgeCountUpProps) {
  const [value, setValue] = useState(from)
  const ref = useRef<HTMLDivElement>(null)
  const started = useRef(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started.current) {
          started.current = true
          const startTime = performance.now()
          const range = to - from

          function tick(now: number) {
            const elapsed = now - startTime
            const progress = Math.min(elapsed / duration, 1)
            // Ease out cubic
            const eased = 1 - Math.pow(1 - progress, 3)
            setValue(Math.round(from + range * eased))
            if (progress < 1) requestAnimationFrame(tick)
          }

          requestAnimationFrame(tick)
          observer.disconnect()
        }
      },
      { threshold: 0.3 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [from, to, duration])

  // Format number with commas
  const formatted = value.toLocaleString()

  return (
    <div
      ref={ref}
      className={`forge-countup forge-countup--${size}`}
      style={{ '--forge-countup-color': color, '--forge-countup-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      <div className="forge-countup__number">
        {prefix}<span className="forge-countup__value">{formatted}</span>{suffix}
      </div>
      {showLabel && <div className="forge-countup__label">{label}</div>}
    </div>
  )
}
