// ForgeTable — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update table

import './ForgeTable.css'

interface ForgeTableProps {
  columns?: string[]
  rows?: (string | number)[][]
  caption?: string
  color?: string
  showStripes?: boolean
  showHover?: boolean
  compact?: boolean
}

// Default demo rows — replace with your data
const DEFAULT_ROWS: (string | number)[][] = [
  ['Name 1', 'Status 1', 'Date 1'],
  ['Name 2', 'Status 2', 'Date 2'],
  ['Name 3', 'Status 3', 'Date 3'],
]

export function ForgeTable({
  columns = ["Name","Status","Date"],
  rows = DEFAULT_ROWS,
  caption = '',
  color = '#7F77DD',
  showStripes = true,
  showHover = true,
  compact = false,
}: ForgeTableProps) {
  return (
    <div
      className="forge-table-wrap"
      style={{ '--forge-table-color': color, '--forge-table-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      <table className={`forge-table${showStripes ? ' forge-table--striped' : ''}${showHover ? ' forge-table--hover' : ''}${compact ? ' forge-table--compact' : ''}`}>
        {caption && <caption className="forge-table__caption">{caption}</caption>}
        <thead>
          <tr>
            {columns.map(col => (
              <th key={col} className="forge-table__th">{col}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="forge-table__row">
              {row.map((cell, j) => (
                <td key={j} className="forge-table__td">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
