// ForgeToggle — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update toggle

import { useState } from 'react'
import './ForgeToggle.css'

interface ForgeToggleProps {
  label?: string
  color?: string
  size?: 'sm' | 'md' | 'lg'
  checked?: boolean
  showLabel?: boolean
  labelPos?: 'left' | 'right'
  onChange?: (checked: boolean) => void
}

export function ForgeToggle({
  label = 'Toggle',
  color = '#7F77DD',
  size = 'md',
  checked,
  showLabel = true,
  labelPos = 'right',
  onChange,
}: ForgeToggleProps) {
  const [internal, setInternal] = useState(false)
  const controlled = checked !== undefined
  const active = controlled ? checked : internal

  function handleClick() {
    if (!controlled) setInternal(v => !v)
    onChange?.(!active)
  }

  return (
    <div
      className={`forge-toggle-wrap forge-toggle-wrap--${labelPos}`}
      style={{ '--forge-toggle-color': color, '--forge-toggle-rgb': '127, 119, 221' } as React.CSSProperties}
      onClick={handleClick}
    >
      {showLabel && labelPos === 'left' && (
        <span className="forge-toggle-label">{label}</span>
      )}
      <div className={`forge-toggle forge-toggle--${size}${active ? ' forge-toggle--on' : ''}`}>
        <div className="forge-toggle__thumb" />
      </div>
      {showLabel && labelPos === 'right' && (
        <span className="forge-toggle-label">{label}</span>
      )}
    </div>
  )
}
