// ForgeMorphBlob — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update morphblob
// Pure CSS border-radius morphing — no SVG or canvas required.

import './ForgeMorphBlob.css'

interface ForgeMorphBlobProps {
  color?: string
  color2?: string
  size?: number
  speed?: 'slow' | 'normal' | 'fast'
  opacity?: number
  blur?: number
  gradient?: boolean
}

export function ForgeMorphBlob({
  color = '#7F77DD',
  color2 = '#D4537E',
  size = 120,
  speed = 'normal',
  opacity = 0.8,
  blur = 0,
  gradient = true,
}: ForgeMorphBlobProps) {
  return (
    <div
      className={`forge-blob forge-blob--${speed}`}
      style={{
        '--forge-blob-color': color,
        '--forge-blob-color2': color2,
        '--forge-blob-rgb': '127, 119, 221',
        width: size,
        height: size,
        opacity,
        filter: blur > 0 ? `blur(${blur}px)` : undefined,
        background: gradient
          ? `radial-gradient(circle at 30% 30%, ${color}, ${color2})`
          : color,
      } as React.CSSProperties}
    />
  )
}
