// ForgeToast — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update toast

import { useState } from 'react'
import './ForgeToast.css'

type ToastVariant = 'success' | 'error' | 'warning' | 'info'

interface ForgeToastProps {
  title?: string
  message?: string
  variant?: ToastVariant
  showIcon?: boolean
  showClose?: boolean
  onClose?: () => void
}

const ICONS: Record<ToastVariant, string> = {
  success: '✓',
  error: '✕',
  warning: '⚠',
  info: 'i',
}

export function ForgeToast({
  title = 'Notification',
  message,
  variant = 'success',
  showIcon = true,
  showClose = true,
  onClose,
}: ForgeToastProps) {
  const [visible, setVisible] = useState(true)

  function handleClose() {
    setVisible(false)
    onClose?.()
  }

  if (!visible) return null

  return (
    <div className={`forge-toast forge-toast--${variant}`} role="alert">
      {showIcon && (
        <span className="forge-toast__icon">{ICONS[variant]}</span>
      )}
      <div className="forge-toast__content">
        <div className="forge-toast__title">{title}</div>
        {message && <div className="forge-toast__message">{message}</div>}
      </div>
      {showClose && (
        <button className="forge-toast__close" onClick={handleClose} aria-label="Dismiss">✕</button>
      )}
    </div>
  )
}
