// ForgeButton — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-ui update button

import './ForgeButton.css'

interface ForgeButtonProps {
  children: React.ReactNode
  color?: string
  variant?: 'glow' | 'solid' | 'ghost' | 'outline' | 'soft' | 'spectrum'
  radius?: number
  uppercase?: boolean
  fullWidth?: boolean
  disabled?: boolean
  onClick?: () => void
}

export function ForgeButton({
  children,
  color = '#7F77DD',
  variant = 'glow',
  radius = 8,
  uppercase = false,
  fullWidth = false,
  disabled = false,
  onClick,
}: ForgeButtonProps) {
  return (
    <button
      className={`forge-btn forge-btn--${variant}${disabled ? ' forge-btn--disabled' : ''}${fullWidth ? ' forge-btn--full' : ''}`}
      style={{
        '--forge-color': color,
        '--forge-rgb': color,
        borderRadius: radius,
        textTransform: uppercase ? 'uppercase' : 'none',
      } as React.CSSProperties}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  )
}
