// ForgeLineChart — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update linechart
// Requires Chart.js — add to your layout:
// <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js" />

import { useEffect, useRef } from 'react'
import './ForgeLineChart.css'

interface ForgeLineChartProps {
  title?: string
  labels?: string[]
  series?: { label: string; data: number[]; color?: string }[]
  color?: string
  color2?: string
  tension?: number
  fill?: boolean
  showGrid?: boolean
  showDots?: boolean
  animated?: boolean
  height?: number
}

const DEFAULT_LABELS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
const DEFAULT_DATA = [30, 55, 45, 70, 60, 88]

export function ForgeLineChart({
  title = 'Chart',
  labels = DEFAULT_LABELS,
  series,
  color = '#1D9E75',
  color2 = '#EF9F27',
  tension = 0.4,
  fill = true,
  showGrid = true,
  showDots = true,
  animated = true,
  height = 260,
}: ForgeLineChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<unknown>(null)

  const resolvedSeries = series ?? [
    { label: 'Series 1', data: DEFAULT_DATA, color },
    { label: 'Series 2', data: DEFAULT_DATA.map(v => Math.round(v * 0.6)), color: color2 },
  ]

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const Chart = (window as any).Chart
    if (!Chart || !canvasRef.current) return
    if (chartRef.current) (chartRef.current as any).destroy()

    chartRef.current = new Chart(canvasRef.current, {
      type: 'line',
      data: {
        labels,
        datasets: resolvedSeries.map(s => ({
          label: s.label,
          data: s.data,
          borderColor: s.color ?? color,
          backgroundColor: fill ? `${s.color ?? color}22` : 'transparent',
          tension,
          fill,
          pointRadius: showDots ? 4 : 0,
          pointBackgroundColor: s.color ?? color,
          borderWidth: 2,
        })),
      },
      options: {
        responsive: true,
        animation: animated,
        plugins: {
          legend: { display: true, labels: { color: 'rgba(240,237,232,0.4)', font: { family: 'Inter', size: 11 }, boxWidth: 10 } },
          title: { display: !!title, text: title, color: 'rgba(240,237,232,0.6)', font: { family: 'Inter', size: 13, weight: '400' } },
        },
        scales: {
          x: { grid: { display: false }, ticks: { color: 'rgba(240,237,232,0.3)', font: { family: 'Inter', size: 11 } }, border: { display: false } },
          y: { grid: { display: showGrid, color: 'rgba(255,255,255,0.04)' }, ticks: { color: 'rgba(240,237,232,0.3)', font: { family: 'Inter', size: 11 } }, border: { display: false } },
        },
      },
    })

    return () => { if (chartRef.current) (chartRef.current as any).destroy() }
  }, [labels, color, color2, tension, fill, showGrid, showDots, animated, title])

  return (
    <div
      className="forge-linechart-wrap"
      style={{ '--forge-chart-color': color, '--forge-chart-rgb': '29, 158, 117' } as React.CSSProperties}
    >
      <canvas ref={canvasRef} height={height} />
    </div>
  )
}
