// ForgeStatCard — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update statcard

import './ForgeStatCard.css'

interface ForgeStatCardProps {
  title?: string
  value?: string | number
  delta?: string
  deltaDir?: 'up' | 'down'
  icon?: string
  color?: string
  showIcon?: boolean
  showDelta?: boolean
  showBar?: boolean
  barValue?: number
}

export function ForgeStatCard({
  title = 'Metric',
  value = '0',
  delta = '+0%',
  deltaDir = 'up',
  icon = '↑',
  color = '#7F77DD',
  showIcon = true,
  showDelta = true,
  showBar = true,
  barValue = 72,
}: ForgeStatCardProps) {
  const clamped = Math.min(100, Math.max(0, barValue))
  return (
    <div
      className="forge-statcard"
      style={{ '--forge-statcard-color': color, '--forge-statcard-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      <div className="forge-statcard__header">
        <span className="forge-statcard__title">{title}</span>
        {showIcon && <span className="forge-statcard__icon">{icon}</span>}
      </div>
      <div className="forge-statcard__value">{value}</div>
      {showDelta && (
        <div className={`forge-statcard__delta forge-statcard__delta--${deltaDir}`}>
          {deltaDir === 'up' ? '↑' : '↓'} {delta}
        </div>
      )}
      {showBar && (
        <div className="forge-statcard__track">
          <div className="forge-statcard__fill" style={{ width: `${clamped}%` }} />
        </div>
      )}
    </div>
  )
}
