// ForgeSpinner — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update spinner

import './ForgeSpinner.css'

interface ForgeSpinnerProps {
  color?: string
  variant?: 'ring' | 'dots' | 'bars' | 'orbit' | 'pulse'
  size?: 'sm' | 'md' | 'lg' | 'xl'
  speed?: 'slow' | 'normal' | 'fast'
  showLabel?: boolean
  label?: string
}

export function ForgeSpinner({
  color = '#7F77DD',
  variant = 'ring',
  size = 'md',
  speed = 'normal',
  showLabel = false,
  label = 'Loading…',
}: ForgeSpinnerProps) {
  return (
    <div
      className="forge-spinner-wrap"
      style={{ '--forge-spinner-color': color, '--forge-spinner-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      <div className={`forge-spinner forge-spinner--${variant} forge-spinner--${size} forge-spinner--${speed}`}>
        {variant === 'dots' && (
          <>
            <div className="forge-spinner__dot" />
            <div className="forge-spinner__dot" />
            <div className="forge-spinner__dot" />
          </>
        )}
        {variant === 'bars' && (
          <>
            <div className="forge-spinner__bar" />
            <div className="forge-spinner__bar" />
            <div className="forge-spinner__bar" />
            <div className="forge-spinner__bar" />
          </>
        )}
      </div>
      {showLabel && <span className="forge-spinner__label">{label}</span>}
    </div>
  )
}
