// ForgeTicker — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update ticker
// Pure CSS infinite scroll — no JS animation required.

import './ForgeTicker.css'

type TickerItem = string | { label: string; color: string }

function isDot(item: TickerItem): item is { label: string; color: string } {
  return typeof item === 'object' && 'color' in item
}

interface ForgeTickerProps {
  items?: TickerItem[]
  color?: string
  speed?: 'slow' | 'normal' | 'fast'
  separator?: string
  gap?: number
  pauseOnHover?: boolean
  bordered?: boolean
}

export function ForgeTicker({
  items = ['Item one', 'Item two', 'Item three', 'Item four'],
  color = '#7F77DD',
  speed = 'normal',
  separator = '—',
  gap = 48,
  pauseOnHover = true,
  bordered = false,
}: ForgeTickerProps) {
  const all = [...items, ...items]

  return (
    <div
      className={`forge-ticker${bordered ? ' forge-ticker--bordered' : ''}`}
      style={{
        '--forge-ticker-color': color,
        '--forge-ticker-rgb': '127, 119, 221',
        '--forge-ticker-gap': `${gap}px`,
      } as React.CSSProperties}
    >
      <div
        className={`forge-ticker__track forge-ticker__track--${speed}${pauseOnHover ? ' forge-ticker__track--pausable' : ''}`}
      >
        {all.map((item, i) =>
          isDot(item) ? (
            <span key={i} className="forge-ticker__item forge-ticker__item--dot">
              <span className="forge-ticker__dot" style={{ background: item.color }} />
              {item.label}
            </span>
          ) : (
            <span key={i} className="forge-ticker__item">
              {item as string}
              <span className="forge-ticker__sep">{separator}</span>
            </span>
          ),
        )}
      </div>
    </div>
  )
}
