// ForgeStepper — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update stepper

import { useState } from 'react'
import './ForgeStepper.css'

interface ForgeStepperProps {
  steps?: string[]
  descs?: string[]
  color?: string
  variant?: 'horizontal' | 'vertical'
  showDesc?: boolean
  current?: number
  onChange?: (step: number) => void
}

export function ForgeStepper({
  steps = ["Step 1","Step 2","Step 3"],
  descs = [],
  color = '#7F77DD',
  variant = 'horizontal',
  showDesc = true,
  current,
  onChange,
}: ForgeStepperProps) {
  const [internal, setInternal] = useState(0)
  const controlled = current !== undefined
  const active = controlled ? current : internal

  function handleClick(i: number) {
    if (!controlled) setInternal(i)
    onChange?.(i)
  }

  return (
    <div
      className={`forge-stepper forge-stepper--${variant}`}
      style={{ '--forge-stepper-color': color, '--forge-stepper-rgb': '127, 119, 221' } as React.CSSProperties}
    >
      {steps.map((step, i) => {
        const done = i < active
        const curr = i === active
        return (
          <div key={i} className={`forge-step${done ? ' forge-step--done' : ''}${curr ? ' forge-step--current' : ''}`}>
            <div className="forge-step__indicator" onClick={() => handleClick(i)}>
              <div className="forge-step__dot">
                {done ? '✓' : i + 1}
              </div>
              {i < steps.length - 1 && <div className="forge-step__line" />}
            </div>
            <div className="forge-step__content">
              <div className="forge-step__label">{step}</div>
              {showDesc && descs[i] && (
                <div className="forge-step__desc">{descs[i]}</div>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}
