// ForgeSkeleton — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update skeleton

import './ForgeSkeleton.css'

interface ForgeSkeletonProps {
  variant?: 'card' | 'text' | 'profile' | 'table'
  lines?: number
  radius?: number
  animated?: boolean
}

function Bone({ w = '100%', h = '16px', r = 6 }: { w?: string; h?: string; r?: number }) {
  return <div className="forge-sk-bone" style={{ width: w, height: h, borderRadius: r }} />
}

export function ForgeSkeleton({
  variant = 'card',
  lines = 3,
  radius = 8,
  animated = true,
}: ForgeSkeletonProps) {
  return (
    <div className={`forge-skeleton${animated ? ' forge-skeleton--animated' : ''}`}>
      {variant === 'text' && (
        <div className="forge-sk-text">
          {Array.from({ length: lines }).map((_, i) => (
            <Bone key={i} w={i === lines - 1 ? '65%' : '100%'} r={radius} />
          ))}
        </div>
      )}

      {variant === 'profile' && (
        <div className="forge-sk-profile">
          <Bone w="48px" h="48px" r={999} />
          <div className="forge-sk-profile__lines">
            <Bone w="140px" h="14px" r={radius} />
            <Bone w="100px" h="12px" r={radius} />
          </div>
        </div>
      )}

      {variant === 'card' && (
        <div className="forge-sk-card" style={{ borderRadius: radius }}>
          <Bone w="40%" h="11px" r={4} />
          <Bone w="85%" h="16px" r={radius} />
          <Bone w="100%" h="13px" r={radius} />
          <Bone w="70%" h="13px" r={radius} />
        </div>
      )}

      {variant === 'table' && (
        <div className="forge-sk-table">
          <div className="forge-sk-table__row forge-sk-table__header">
            {[40,25,20,15].map((w, i) => <Bone key={i} w={`${w}%`} h="12px" r={4} />)}
          </div>
          {Array.from({ length: lines }).map((_, i) => (
            <div key={i} className="forge-sk-table__row">
              {[40,25,20,15].map((w, j) => <Bone key={j} w={`${w}%`} h="13px" r={4} />)}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
