// ForgeAlert — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update alert

import { useState } from 'react'
import './ForgeAlert.css'

type AlertVariant = 'success' | 'error' | 'warning' | 'info'

interface ForgeAlertProps {
  title?: string
  message?: string
  variant?: AlertVariant
  showIcon?: boolean
  showClose?: boolean
  showAction?: boolean
  actionText?: string
  onAction?: () => void
  onClose?: () => void
}

const ICONS: Record<AlertVariant, string> = {
  success: '✓', error: '✕', warning: '⚠', info: 'i',
}

export function ForgeAlert({
  title = 'Alert',
  message = '',
  variant = 'success',
  showIcon = true,
  showClose = true,
  showAction = false,
  actionText = 'View',
  onAction,
  onClose,
}: ForgeAlertProps) {
  const [visible, setVisible] = useState(true)
  if (!visible) return null

  return (
    <div className={`forge-alert forge-alert--${variant}`} role="alert">
      {showIcon && <span className="forge-alert__icon">{ICONS[variant]}</span>}
      <div className="forge-alert__content">
        <div className="forge-alert__title">{title}</div>
        {message && <div className="forge-alert__message">{message}</div>}
        {showAction && (
          <button className="forge-alert__action" onClick={onAction}>{actionText}</button>
        )}
      </div>
      {showClose && (
        <button className="forge-alert__close" onClick={() => { setVisible(false); onClose?.() }} aria-label="Dismiss">✕</button>
      )}
    </div>
  )
}
