// ForgeFadeUp — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update fadeup
// Pure CSS animation — no Framer Motion required.

import { useEffect, useRef, useState } from 'react'
import './ForgeFadeUp.css'

interface ForgeFadeUpProps {
  // Pass a string with newlines to stagger each line,
  // or pass children for a single animated block.
  text?: string
  children?: React.ReactNode
  color?: string
  duration?: number
  stagger?: boolean
  delay?: number
}

export function ForgeFadeUp({
  text,
  children,
  color = '#7F77DD',
  duration = 600,
  stagger = true,
  delay = 0,
}: ForgeFadeUpProps) {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    // Use IntersectionObserver so animation triggers on scroll into view
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } },
      { threshold: 0.1 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  // If text prop provided, split into lines and stagger each one
  if (text) {
    const lines = text.split('\n').filter(Boolean)
    return (
      <div ref={ref} style={{ '--forge-fadeup-color': color } as React.CSSProperties}>
        {lines.map((line, i) => (
          <div
            key={i}
            className={`forge-fadeup-line${visible ? ' forge-fadeup-line--visible' : ''}`}
            style={{
              animationDuration: `${duration}ms`,
              animationDelay: stagger ? `${delay + i * 80}ms` : `${delay}ms`,
            }}
          >
            {line}
          </div>
        ))}
      </div>
    )
  }

  // Otherwise animate children as a single block
  return (
    <div
      ref={ref}
      className={`forge-fadeup-block${visible ? ' forge-fadeup-block--visible' : ''}`}
      style={{
        '--forge-fadeup-color': color,
        animationDuration: `${duration}ms`,
        animationDelay: `${delay}ms`,
      } as React.CSSProperties}
    >
      {children}
    </div>
  )
}
