import { hexToRgb } from "./utils.js";

export function generateAccordion(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const radius = (props.radius as number) ?? 8;
  const items = (props.items as string[]) ?? ["Question one", "Question two"];
  const bodies = (props.bodies as string[]) ?? ["Answer one.", "Answer two."];

  const tsx = `// ForgeAccordion — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update accordion

import { useState } from 'react'
import './ForgeAccordion.css'

interface ForgeAccordionProps {
  items?: string[]
  bodies?: string[]
  color?: string
  radius?: number
  allowMultiple?: boolean
}

export function ForgeAccordion({
  items = ${JSON.stringify(items)},
  bodies = ${JSON.stringify(bodies)},
  color = '${color}',
  radius = ${radius},
  allowMultiple = false,
}: ForgeAccordionProps) {
  const [open, setOpen] = useState<number[]>([])

  function toggle(i: number) {
    if (allowMultiple) {
      setOpen(o => o.includes(i) ? o.filter(x => x !== i) : [...o, i])
    } else {
      setOpen(o => o.includes(i) ? [] : [i])
    }
  }

  return (
    <div
      className="forge-accordion"
      style={{ '--forge-accordion-color': color, '--forge-accordion-rgb': '${rgb}' } as React.CSSProperties}
    >
      {items.map((item, i) => {
        const isOpen = open.includes(i)
        return (
          <div key={i} className={\`forge-accordion__item\${isOpen ? ' forge-accordion__item--open' : ''}\`} style={{ borderRadius: radius }}>
            <button
              className="forge-accordion__trigger"
              onClick={() => toggle(i)}
              aria-expanded={isOpen}
            >
              <span>{item}</span>
              <span className={\`forge-accordion__arrow\${isOpen ? ' forge-accordion__arrow--open' : ''}\`}>▾</span>
            </button>
            {isOpen && (
              <div className="forge-accordion__body">
                {bodies[i] ?? ''}
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
`;

  const css = `/* ForgeAccordion.css — generated by forge-ui CLI */
.forge-accordion {
  display: flex;
  flex-direction: column;
  gap: 4px;
  font-family: Inter, sans-serif;
  width: 100%;
}

.forge-accordion__item {
  background: #0f0f12;
  border: 1px solid rgba(255,255,255,0.06);
  overflow: hidden;
  transition: border-color 0.15s ease;
}

.forge-accordion__item--open {
  border-color: rgba(var(--forge-accordion-rgb), 0.2);
}

.forge-accordion__trigger {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  padding: 14px 16px;
  background: none;
  border: none;
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  color: rgba(240,237,232,0.7);
  letter-spacing: -0.01em;
  cursor: pointer;
  text-align: left;
  transition: color 0.15s ease;
}

.forge-accordion__trigger:hover { color: #f0ede8; }
.forge-accordion__item--open .forge-accordion__trigger { color: #f0ede8; }

.forge-accordion__arrow {
  font-size: 12px;
  color: rgba(240,237,232,0.25);
  transition: transform 0.2s ease;
  flex-shrink: 0;
}

.forge-accordion__arrow--open {
  transform: rotate(180deg);
  color: var(--forge-accordion-color);
}

.forge-accordion__body {
  padding: 0 16px 14px;
  font-size: 13px;
  font-weight: 300;
  color: rgba(240,237,232,0.45);
  letter-spacing: -0.01em;
  line-height: 1.6;
}

@media (prefers-reduced-motion: reduce) {
  .forge-accordion__item,
  .forge-accordion__trigger,
  .forge-accordion__arrow { transition: none; }
}
`;
  return { tsx, css };
}
