export function generateAlert(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const variant = (props.variant as string) ?? "success";
  const showIcon = (props.showIcon as boolean) ?? true;
  const showClose = (props.showClose as boolean) ?? true;
  const showAction = (props.showAction as boolean) ?? false;
  const actionText = (props.actionText as string) ?? "View";
  const title = (props.title as string) ?? "Alert";
  const message = (props.message as string) ?? "";

  const tsx = `// ForgeAlert — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update alert

import { useState } from 'react'
import './ForgeAlert.css'

type AlertVariant = 'success' | 'error' | 'warning' | 'info'

interface ForgeAlertProps {
  title?: string
  message?: string
  variant?: AlertVariant
  showIcon?: boolean
  showClose?: boolean
  showAction?: boolean
  actionText?: string
  onAction?: () => void
  onClose?: () => void
}

const ICONS: Record<AlertVariant, string> = {
  success: '✓', error: '✕', warning: '⚠', info: 'i',
}

export function ForgeAlert({
  title = '${title}',
  message = '${message}',
  variant = '${variant}',
  showIcon = ${showIcon},
  showClose = ${showClose},
  showAction = ${showAction},
  actionText = '${actionText}',
  onAction,
  onClose,
}: ForgeAlertProps) {
  const [visible, setVisible] = useState(true)
  if (!visible) return null

  return (
    <div className={\`forge-alert forge-alert--\${variant}\`} role="alert">
      {showIcon && <span className="forge-alert__icon">{ICONS[variant]}</span>}
      <div className="forge-alert__content">
        <div className="forge-alert__title">{title}</div>
        {message && <div className="forge-alert__message">{message}</div>}
        {showAction && (
          <button className="forge-alert__action" onClick={onAction}>{actionText}</button>
        )}
      </div>
      {showClose && (
        <button className="forge-alert__close" onClick={() => { setVisible(false); onClose?.() }} aria-label="Dismiss">✕</button>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeAlert.css — generated by forge-ui CLI */
.forge-alert {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 14px 16px;
  border-radius: 8px;
  border: 1px solid;
  font-family: Inter, sans-serif;
  width: 100%;
  box-sizing: border-box;
}

.forge-alert--success { background: rgba(29,158,117,0.08);  border-color: rgba(29,158,117,0.2);  }
.forge-alert--error   { background: rgba(226,75,74,0.08);   border-color: rgba(226,75,74,0.2);   }
.forge-alert--warning { background: rgba(239,159,39,0.08);  border-color: rgba(239,159,39,0.2);  }
.forge-alert--info    { background: rgba(55,138,221,0.08);  border-color: rgba(55,138,221,0.2);  }

.forge-alert__icon {
  font-size: 13px;
  flex-shrink: 0;
  margin-top: 1px;
}
.forge-alert--success .forge-alert__icon { color: #1D9E75; }
.forge-alert--error   .forge-alert__icon { color: #e24b4a; }
.forge-alert--warning .forge-alert__icon { color: #EF9F27; }
.forge-alert--info    .forge-alert__icon { color: #378ADD; }

.forge-alert__content { flex: 1; display: flex; flex-direction: column; gap: 4px; }

.forge-alert__title {
  font-size: 13px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.01em;
}

.forge-alert__message {
  font-size: 12px;
  font-weight: 300;
  color: rgba(240,237,232,0.5);
  letter-spacing: -0.01em;
  line-height: 1.5;
}

.forge-alert__action {
  background: none;
  border: none;
  font-family: Inter, sans-serif;
  font-size: 12px;
  font-weight: 400;
  letter-spacing: -0.01em;
  cursor: pointer;
  padding: 0;
  margin-top: 4px;
  text-decoration: underline;
  text-underline-offset: 2px;
}
.forge-alert--success .forge-alert__action { color: #1D9E75; }
.forge-alert--error   .forge-alert__action { color: #e24b4a; }
.forge-alert--warning .forge-alert__action { color: #EF9F27; }
.forge-alert--info    .forge-alert__action { color: #378ADD; }

.forge-alert__close {
  background: none;
  border: none;
  color: rgba(240,237,232,0.3);
  cursor: pointer;
  font-size: 11px;
  padding: 0;
  flex-shrink: 0;
  transition: color 0.15s ease;
}
.forge-alert__close:hover { color: #f0ede8; }
`;
  return { tsx, css };
}
