const RAMPS: Record<string, string> = {
  standard: " .,:;+*?%S#@",
  block: " ░▒▓█",
  braille: " ⠂⠆⠖⠶⠷⠿⡿⣿",
  minimal: " .:|=",
};

const ANIMATION_KEYFRAMES = `@keyframes forge-ascii-fadein {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes forge-ascii-scanline {
  from { clip-path: inset(0 0 100% 0); }
  to { clip-path: inset(0 0 0 0); }
}

@keyframes forge-ascii-flicker {
  0%, 100% { opacity: 1; }
  8% { opacity: 0.4; }
  18% { opacity: 0.9; }
  29% { opacity: 0.5; }
  41% { opacity: 1; }
  53% { opacity: 0.6; }
  67% { opacity: 0.95; }
  78% { opacity: 0.45; }
  89% { opacity: 1; }
}

@keyframes forge-ascii-wave {
  0%, 100% { transform: translateY(0); }
  25% { transform: translateY(-6px); }
  50% { transform: translateY(0); }
  75% { transform: translateY(6px); }
}

@keyframes forge-ascii-glitch {
  0%, 100% { transform: translate(0, 0); text-shadow: none; }
  20% { transform: translate(-2px, 1px); text-shadow: -2px 0 var(--forge-ascii-color), 2px 0 #e24b4a; }
  40% { transform: translate(2px, -1px); text-shadow: 2px 0 #378ADD, -2px 0 var(--forge-ascii-color); }
  60% { transform: translate(-1px, 0); text-shadow: -1px 0 var(--forge-ascii-color), 1px 0 #e24b4a; }
  80% { transform: translate(1px, 0); text-shadow: none; }
}`;

const ANIMATION_SHORTHAND: Record<string, string> = {
  fadein: "forge-ascii-fadein {{duration}}ms ease-out forwards",
  scanline: "forge-ascii-scanline {{duration}}ms steps(24, end) forwards",
  flicker: "forge-ascii-flicker {{duration}}ms linear infinite",
  wave: "forge-ascii-wave {{duration}}ms ease-in-out infinite",
  glitch: "forge-ascii-glitch {{duration}}ms steps(6, end) infinite",
};

export function generateAscii(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const density = (props.density as number) ?? 80;
  const characterSet = (props.characterSet as string) ?? "standard";
  const animation = (props.animation as string) ?? "fadein";
  const duration = (props.duration as number) ?? 1200;
  const ramp = RAMPS[characterSet] ?? RAMPS.standard;

  const tsx = `// ForgeAscii - generated by forge-ui CLI
// Edit this file freely - you own it.
// Re-generate with: npx @forgelabs-studio/ui update ascii
// Converts an uploaded PNG/JPG into ASCII art rendered as plain text.
// Runs synchronously on the main thread - fine for the kind of image sizes
// a person uploads by hand; resize very large images before converting if
// you need this on a hot path.

import { useRef, useState } from 'react'
import './ForgeAscii.css'

type CharacterSet = 'standard' | 'block' | 'braille' | 'minimal'
type AsciiAnimation = 'none' | 'fadein' | 'scanline' | 'flicker' | 'wave' | 'glitch'

const RAMPS: Record<CharacterSet, string> = {
  standard: ' .,:;+*?%S#@',
  block: ' ░▒▓█',
  braille: ' ⠂⠆⠖⠶⠷⠿⡿⣿',
  minimal: ' .:|=',
}

const ACCEPTED_TYPES = ['image/png', 'image/jpeg']

function brightnessToChar(brightness: number, ramp: string): string {
  const index = Math.min(ramp.length - 1, Math.floor((brightness / 255) * ramp.length))
  return ramp[index]
}

function convertToAscii(imageData: ImageData, density: number, ramp: string): string {
  const { width, height, data } = imageData
  const cols = Math.max(1, Math.min(200, Math.round(density)))
  const rows = Math.max(1, Math.round((height / width) * cols * 0.5))
  const cellWidth = width / cols
  const cellHeight = height / rows

  const lines: string[] = new Array(rows)
  for (let row = 0; row < rows; row++) {
    const yStart = Math.floor(row * cellHeight)
    const yEnd = Math.max(yStart + 1, Math.floor((row + 1) * cellHeight))

    let line = ''
    for (let col = 0; col < cols; col++) {
      const xStart = Math.floor(col * cellWidth)
      const xEnd = Math.max(xStart + 1, Math.floor((col + 1) * cellWidth))

      let total = 0
      let count = 0
      for (let y = yStart; y < yEnd; y++) {
        for (let x = xStart; x < xEnd; x++) {
          const i = (y * width + x) * 4
          total += data[i] * 0.299 + data[i + 1] * 0.587 + data[i + 2] * 0.114
          count++
        }
      }
      line += brightnessToChar(count > 0 ? total / count : 0, ramp)
    }
    lines[row] = line
  }

  return lines.join('\\n')
}

interface ForgeAsciiProps {
  color?: string
  density?: number
  characterSet?: CharacterSet
  animation?: AsciiAnimation
  duration?: number
}

export function ForgeAscii({
  color = '${color}',
  density = ${density},
  characterSet = '${characterSet}',
  animation = '${animation}',
  duration = ${duration},
}: ForgeAsciiProps) {
  const [asciiText, setAsciiText] = useState('')
  const [fileName, setFileName] = useState('')
  const [status, setStatus] = useState<'idle' | 'converting' | 'ready' | 'error'>('idle')
  const [dragOver, setDragOver] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)

  function handleFiles(files: FileList | null) {
    const file = files?.[0]
    if (!file || !ACCEPTED_TYPES.includes(file.type)) return

    setFileName(file.name)
    setStatus('converting')

    const img = new Image()
    img.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = img.naturalWidth
      canvas.height = img.naturalHeight
      const ctx = canvas.getContext('2d')
      if (!ctx) {
        setStatus('error')
        return
      }
      ctx.drawImage(img, 0, 0)

      try {
        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
        setAsciiText(convertToAscii(imageData, density, RAMPS[characterSet] ?? RAMPS.standard))
        setStatus('ready')
      } catch {
        setStatus('error')
      } finally {
        URL.revokeObjectURL(img.src)
      }
    }
    img.onerror = () => setStatus('error')
    img.src = URL.createObjectURL(file)
  }

  return (
    <div
      className="forge-ascii-wrap"
      style={{ '--forge-ascii-color': color, '--forge-ascii-duration': \`\${duration}ms\` } as React.CSSProperties}
    >
      <div
        className={\`forge-ascii-drop\${dragOver ? ' forge-ascii-drop--over' : ''}\`}
        onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => {
          e.preventDefault()
          setDragOver(false)
          handleFiles(e.dataTransfer.files)
        }}
        onClick={() => inputRef.current?.click()}
      >
        {asciiText ? (
          <pre className={\`forge-ascii\${animation !== 'none' ? \` forge-ascii--\${animation}\` : ''}\`}>
            {asciiText}
          </pre>
        ) : (
          <span className="forge-ascii-hint">
            {status === 'error' ? 'Could not read that file - try another PNG or JPG' : 'Click or drop a PNG / JPG'}
          </span>
        )}
        <input
          ref={inputRef}
          type="file"
          accept="image/png,image/jpeg"
          onChange={(e) => handleFiles(e.target.files)}
          style={{ display: 'none' }}
        />
      </div>
      {fileName && <div className="forge-ascii-filename">{fileName} - {status}</div>}
    </div>
  )
}
`;

  // All five variants are wired up, not just the one chosen at generation time -
  // the `animation` prop is meant to stay switchable at runtime, same as `speed`
  // on ForgeMorphBlob.
  const animationCss = Object.entries(ANIMATION_SHORTHAND)
    .map(([id, shorthand]) => `.forge-ascii--${id} {\n  animation: ${shorthand.replace("{{duration}}", "var(--forge-ascii-duration)")};\n}`)
    .join("\n\n");

  const css = `/* ForgeAscii.css - generated by forge-ui CLI */
/* Glyph ramp baked in at generation time (${characterSet}): ${ramp} */

.forge-ascii-wrap {
  display: inline-block;
}

.forge-ascii-drop {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 200px;
  min-height: 120px;
  padding: 16px;
  background: #09090b;
  border: 1px dashed rgba(255,255,255,0.15);
  border-radius: 8px;
  cursor: pointer;
  transition: border-color 0.12s, background 0.12s;
}

.forge-ascii-drop--over {
  border-color: var(--forge-ascii-color);
  background: rgba(255,255,255,0.03);
}

.forge-ascii-hint {
  font-family: Inter, sans-serif;
  font-size: 12px;
  color: rgba(240,237,232,0.4);
}

.forge-ascii-filename {
  margin-top: 6px;
  font-family: 'DM Mono', ui-monospace, monospace;
  font-size: 11px;
  color: rgba(240,237,232,0.4);
}

.forge-ascii {
  margin: 0;
  color: var(--forge-ascii-color);
  font-family: 'DM Mono', ui-monospace, monospace;
  font-size: 8px;
  line-height: 1.1;
  white-space: pre;
}
${ANIMATION_KEYFRAMES}
${animationCss}
@media (prefers-reduced-motion: reduce) {
  .forge-ascii {
    animation: none !important;
  }
}
`;

  return { tsx, css };
}
