import { hexToRgb } from "./utils.js";

export function generateAvatar(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const size = (props.size as string) ?? "md";
  const shape = (props.shape as string) ?? "circle";
  const showStatus = (props.showStatus as boolean) ?? true;
  const status = (props.status as string) ?? "online";
  const showRing = (props.showRing as boolean) ?? false;
  const initials = (props.initials as string) ?? "FL";

  const sizeMap: Record<string, string> = {
    xs: "24px",
    sm: "32px",
    md: "40px",
    lg: "48px",
    xl: "64px",
  };
  const fontSizeMap: Record<string, string> = {
    xs: "9px",
    sm: "11px",
    md: "13px",
    lg: "16px",
    xl: "20px",
  };
  const shapeMap: Record<string, string> = {
    circle: "50%",
    squircle: "30%",
    square: "6px",
  };
  const statusColorMap: Record<string, string> = {
    online: "#1D9E75",
    away: "#EF9F27",
    busy: "#e24b4a",
    offline: "#555",
  };

  const tsx = `// ForgeAvatar — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update avatar

import './ForgeAvatar.css'

interface ForgeAvatarProps {
  initials?: string
  color?: string
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  shape?: 'circle' | 'squircle' | 'square'
  showStatus?: boolean
  status?: 'online' | 'away' | 'busy' | 'offline'
  showRing?: boolean
  src?: string
  alt?: string
}

export function ForgeAvatar({
  initials = '${initials}',
  color = '${color}',
  size = '${size}',
  shape = '${shape}',
  showStatus = ${showStatus},
  status = '${status}',
  showRing = ${showRing},
  src,
  alt,
}: ForgeAvatarProps) {
  return (
    <div
      className={\`forge-avatar forge-avatar--\${size} forge-avatar--\${shape}\${showRing ? ' forge-avatar--ring' : ''}\`}
      style={{ '--forge-avatar-color': color, '--forge-avatar-rgb': '${rgb}' } as React.CSSProperties}
    >
      {src ? (
        <img src={src} alt={alt ?? initials} className="forge-avatar__img" />
      ) : (
        <span className="forge-avatar__initials">{initials}</span>
      )}
      {showStatus && (
        <span className={\`forge-avatar__status forge-avatar__status--\${status}\`} />
      )}
    </div>
  )
}
`;

  const css = `/* ForgeAvatar.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-avatar {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: rgba(var(--forge-avatar-rgb), 0.15);
  border: 1px solid rgba(var(--forge-avatar-rgb), 0.25);
  font-family: Inter, sans-serif;
  font-weight: 400;
  letter-spacing: -0.01em;
  color: rgba(var(--forge-avatar-rgb), 0.9);
  flex-shrink: 0;
  overflow: hidden;
}

/* Sizes */
.forge-avatar--xs { width: ${sizeMap.xs}; height: ${sizeMap.xs}; font-size: ${fontSizeMap.xs}; }
.forge-avatar--sm { width: ${sizeMap.sm}; height: ${sizeMap.sm}; font-size: ${fontSizeMap.sm}; }
.forge-avatar--md { width: ${sizeMap.md}; height: ${sizeMap.md}; font-size: ${fontSizeMap.md}; }
.forge-avatar--lg { width: ${sizeMap.lg}; height: ${sizeMap.lg}; font-size: ${fontSizeMap.lg}; }
.forge-avatar--xl { width: ${sizeMap.xl}; height: ${sizeMap.xl}; font-size: ${fontSizeMap.xl}; }

/* Shapes */
.forge-avatar--circle   { border-radius: ${shapeMap.circle}; }
.forge-avatar--squircle { border-radius: ${shapeMap.squircle}; }
.forge-avatar--square   { border-radius: ${shapeMap.square}; }

/* Ring */
.forge-avatar--ring {
  box-shadow: 0 0 0 2px #09090b, 0 0 0 4px var(--forge-avatar-color);
}

/* Image */
.forge-avatar__img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

/* Status dot */
.forge-avatar__status {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 28%;
  height: 28%;
  border-radius: 50%;
  border: 2px solid #09090b;
}
.forge-avatar__status--online  { background: ${statusColorMap.online}; }
.forge-avatar__status--away    { background: ${statusColorMap.away}; }
.forge-avatar__status--busy    { background: ${statusColorMap.busy}; }
.forge-avatar__status--offline { background: ${statusColorMap.offline}; }
`;
  return { tsx, css };
}
