import { hexToRgb } from "./utils.js";

export function generateBadge(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#1D9E75";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "pill";
  const size = (props.size as string) ?? "md";
  const showDot = (props.showDot as boolean) ?? true;
  const dotPulse = (props.dotPulse as boolean) ?? true;
  const uppercase = (props.uppercase as boolean) ?? false;

  const radiusMap: Record<string, string> = {
    pill: "999px",
    tag: "4px",
    square: "0px",
  };

  const paddingMap: Record<string, string> = {
    sm: "2px 8px",
    md: "4px 12px",
    lg: "6px 16px",
  };

  const fontSizeMap: Record<string, string> = {
    sm: "10px",
    md: "12px",
    lg: "13px",
  };

  const tsx = `// ForgeBadge — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update badge

import './ForgeBadge.css'

interface ForgeBadgeProps {
  children: React.ReactNode
  color?: string
  variant?: 'pill' | 'tag' | 'square'
  size?: 'sm' | 'md' | 'lg'
  showDot?: boolean
  dotPulse?: boolean
  uppercase?: boolean
}

export function ForgeBadge({
  children,
  color = '${color}',
  variant = '${variant}',
  size = '${size}',
  showDot = ${showDot},
  dotPulse = ${dotPulse},
  uppercase = ${uppercase},
}: ForgeBadgeProps) {
  return (
    <span
      className={\`forge-badge forge-badge--\${variant} forge-badge--\${size}\`}
      style={{
        '--forge-badge-color': color,
        '--forge-badge-rgb': '${rgb}',
        textTransform: uppercase ? 'uppercase' : 'none',
      } as React.CSSProperties}
    >
      {showDot && (
        <span className={\`forge-badge__dot\${dotPulse ? ' forge-badge__dot--pulse' : ''}\`} />
      )}
      {children}
    </span>
  )
}
`;

  const css = `/* ForgeBadge.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-family: Inter, sans-serif;
  font-weight: 400;
  letter-spacing: -0.01em;
  border: 1px solid rgba(var(--forge-badge-rgb), 0.25);
  background: rgba(var(--forge-badge-rgb), 0.10);
  color: rgba(var(--forge-badge-rgb), 0.90);
  white-space: nowrap;
}

/* Variants */
.forge-badge--pill   { border-radius: ${radiusMap.pill}; }
.forge-badge--tag    { border-radius: ${radiusMap.tag}; }
.forge-badge--square { border-radius: ${radiusMap.square}; }

/* Sizes */
.forge-badge--sm { padding: ${paddingMap.sm}; font-size: ${fontSizeMap.sm}; }
.forge-badge--md { padding: ${paddingMap.md}; font-size: ${fontSizeMap.md}; }
.forge-badge--lg { padding: ${paddingMap.lg}; font-size: ${fontSizeMap.lg}; }

/* Dot */
.forge-badge__dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--forge-badge-color);
  flex-shrink: 0;
}

/* Pulse animation */
@keyframes forge-badge-pulse {
  0%, 100% { opacity: 1; transform: scale(1); }
  50%       { opacity: 0.4; transform: scale(0.8); }
}
.forge-badge__dot--pulse {
  animation: forge-badge-pulse 1.5s ease-in-out infinite;
}
`;
  return { tsx, css };
}
