import { hexToRgb } from "./utils.js";

export function generateBarChart(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const color2 = (props.color2 as string) ?? "#378ADD";
  const radius = (props.radius as number) ?? 4;
  const showGrid = (props.showGrid as boolean) ?? true;
  const showLegend = (props.showLegend as boolean) ?? true;
  const animated = (props.animated as boolean) ?? true;
  const title = (props.title as string) ?? "Chart";

  const tsx = `// ForgeBarChart — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update barchart
// Requires Chart.js — add to your layout:
// <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js" />

import { useEffect, useRef } from 'react'
import './ForgeBarChart.css'

interface ForgeBarChartProps {
  title?: string
  labels?: string[]
  series?: { label: string; data: number[]; color?: string }[]
  color?: string
  color2?: string
  radius?: number
  showGrid?: boolean
  showLegend?: boolean
  animated?: boolean
  height?: number
}

const DEFAULT_LABELS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
const DEFAULT_DATA = [42, 68, 55, 81, 63, 90]

export function ForgeBarChart({
  title = '${title}',
  labels = DEFAULT_LABELS,
  series,
  color = '${color}',
  color2 = '${color2}',
  radius = ${radius},
  showGrid = ${showGrid},
  showLegend = ${showLegend},
  animated = ${animated},
  height = 260,
}: ForgeBarChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<unknown>(null)

  const resolvedSeries = series ?? [
    { label: 'Series 1', data: DEFAULT_DATA, color },
    { label: 'Series 2', data: DEFAULT_DATA.map(v => Math.round(v * 0.7)), color: color2 },
  ]

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const Chart = (window as any).Chart
    if (!Chart || !canvasRef.current) return
    if (chartRef.current) (chartRef.current as any).destroy()

    chartRef.current = new Chart(canvasRef.current, {
      type: 'bar',
      data: {
        labels,
        datasets: resolvedSeries.map(s => ({
          label: s.label,
          data: s.data,
          backgroundColor: s.color ?? color,
          borderRadius: radius,
          borderSkipped: false,
        })),
      },
      options: {
        responsive: true,
        animation: animated,
        plugins: {
          legend: { display: showLegend, labels: { color: 'rgba(240,237,232,0.4)', font: { family: 'Inter', size: 11 }, boxWidth: 10 } },
          title: { display: !!title, text: title, color: 'rgba(240,237,232,0.6)', font: { family: 'Inter', size: 13, weight: '400' } },
        },
        scales: {
          x: { grid: { display: false }, ticks: { color: 'rgba(240,237,232,0.3)', font: { family: 'Inter', size: 11 } }, border: { display: false } },
          y: { grid: { display: showGrid, color: 'rgba(255,255,255,0.04)' }, ticks: { color: 'rgba(240,237,232,0.3)', font: { family: 'Inter', size: 11 } }, border: { display: false } },
        },
      },
    })

    return () => { if (chartRef.current) (chartRef.current as any).destroy() }
  }, [labels, color, color2, radius, showGrid, showLegend, animated, title])

  return (
    <div
      className="forge-chart-wrap"
      style={{ '--forge-chart-color': color, '--forge-chart-rgb': '${rgb}' } as React.CSSProperties}
    >
      <canvas ref={canvasRef} height={height} />
    </div>
  )
}
`;

  const css = `/* ForgeBarChart.css — generated by forge-ui CLI */
.forge-chart-wrap {
  width: 100%;
  background: #0f0f12;
  border: 1px solid rgba(255,255,255,0.06);
  border-radius: 10px;
  padding: 16px;
  box-sizing: border-box;
}
`;
  return { tsx, css };
}
