import { hexToRgb } from "./utils.js";

export function generateBreadcrumb(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const separator = (props.separator as string) ?? "/";
  const showHome = (props.showHome as boolean) ?? true;

  const tsx = `// ForgeBreadcrumb — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update breadcrumb

import './ForgeBreadcrumb.css'

interface ForgeBreadcrumbProps {
  items: { label: string; href?: string }[]
  color?: string
  separator?: string
  showHome?: boolean
}

export function ForgeBreadcrumb({
  items = [{ label: 'Home', href: '/' }, { label: 'Components' }, { label: 'Button' }],
  color = '${color}',
  separator = '${separator}',
  showHome = ${showHome},
}: ForgeBreadcrumbProps) {
  const all = showHome && items[0]?.label !== 'Home'
    ? [{ label: 'Home', href: '/' }, ...items]
    : items

  return (
    <nav
      className="forge-breadcrumb"
      aria-label="Breadcrumb"
      style={{ '--forge-breadcrumb-color': color, '--forge-breadcrumb-rgb': '${rgb}' } as React.CSSProperties}
    >
      <ol className="forge-breadcrumb__list">
        {all.map((item, i) => {
          const isLast = i === all.length - 1
          return (
            <li key={i} className="forge-breadcrumb__item">
              {i > 0 && (
                <span className="forge-breadcrumb__sep" aria-hidden="true">
                  {separator}
                </span>
              )}
              {item.href && !isLast ? (
                <a href={item.href} className="forge-breadcrumb__link">
                  {item.label}
                </a>
              ) : (
                <span className={\`forge-breadcrumb__current\${isLast ? ' forge-breadcrumb__current--active' : ''}\`}>
                  {item.label}
                </span>
              )}
            </li>
          )
        })}
      </ol>
    </nav>
  )
}
`;

  const css = `/* ForgeBreadcrumb.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-breadcrumb {
  font-family: Inter, sans-serif;
}

.forge-breadcrumb__list {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0;
  list-style: none;
  margin: 0;
  padding: 0;
}

.forge-breadcrumb__item {
  display: flex;
  align-items: center;
  gap: 0;
}

.forge-breadcrumb__sep {
  font-size: 12px;
  color: rgba(240, 237, 232, 0.2);
  margin: 0 6px;
  user-select: none;
}

.forge-breadcrumb__link {
  font-size: 13px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.38);
  text-decoration: none;
  letter-spacing: -0.01em;
  transition: color 0.15s ease;
}

.forge-breadcrumb__link:hover {
  color: var(--forge-breadcrumb-color);
}

.forge-breadcrumb__current {
  font-size: 13px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.38);
  letter-spacing: -0.01em;
}

.forge-breadcrumb__current--active {
  color: rgba(240, 237, 232, 0.7);
}
`;
  return { tsx, css };
}
