import { hexToRgb } from "./utils.js";

export function generateButton(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "glow";
  const radius = (props.radius as number) ?? 8;
  const hoverEffect = (props.hoverEffect as string) ?? "lift";
  const shadow = (props.shadow as string) ?? "glow";
  const clickAnim = (props.clickAnim as string) ?? "ripple";
  const uppercase = (props.uppercase as boolean) ?? false;
  const fullWidth = (props.fullWidth as boolean) ?? false;

  const tsx = `// ForgeButton — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx forge-ui update button

import './ForgeButton.css'

interface ForgeButtonProps {
  children: React.ReactNode
  color?: string
  variant?: 'glow' | 'solid' | 'ghost' | 'outline' | 'soft' | 'spectrum'
  radius?: number
  uppercase?: boolean
  fullWidth?: boolean
  disabled?: boolean
  onClick?: () => void
}

export function ForgeButton({
  children,
  color = '${color}',
  variant = '${variant}',
  radius = ${radius},
  uppercase = ${uppercase},
  fullWidth = ${fullWidth},
  disabled = false,
  onClick,
}: ForgeButtonProps) {
  return (
    <button
      className={\`forge-btn forge-btn--\${variant}\${disabled ? ' forge-btn--disabled' : ''}\${fullWidth ? ' forge-btn--full' : ''}\`}
      style={{
        '--forge-color': color,
        '--forge-rgb': color,
        borderRadius: radius,
        textTransform: uppercase ? 'uppercase' : 'none',
      } as React.CSSProperties}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  )
}
`;

  const css = `/* ForgeButton.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 7px;
  padding: 10px 20px;
  font-size: 13px;
  font-weight: 400;
  font-family: Inter, sans-serif;
  letter-spacing: -0.01em;
  border: 1px solid transparent;
  cursor: pointer;
  transition: all 0.2s ease;
  position: relative;
  overflow: hidden;
}

/* Glow variant — default */
.forge-btn--glow {
  background: rgba(${rgb}, 0.10);
  border-color: rgba(${rgb}, 0.28);
  color: rgba(${rgb}, 0.90);
}
.forge-btn--glow:hover {
  border-color: rgba(${rgb}, 0.55);
  box-shadow: 0 0 22px rgba(${rgb}, 0.25);
  ${hoverEffect === "lift" ? "transform: translateY(-2px);" : ""}
  ${hoverEffect === "scale" ? "transform: scale(1.04);" : ""}
}

/* Solid variant */
.forge-btn--solid {
  background: ${color};
  border-color: ${color};
  color: #ffffff;
}
.forge-btn--solid:hover {
  opacity: 0.88;
  ${hoverEffect === "lift" ? "transform: translateY(-2px);" : ""}
}

/* Ghost variant */
.forge-btn--ghost {
  background: transparent;
  border-color: rgba(255,255,255,0.1);
  color: rgba(240,237,232,0.5);
}
.forge-btn--ghost:hover {
  background: rgba(255,255,255,0.05);
  color: #f0ede8;
}

/* Outline variant */
.forge-btn--outline {
  background: transparent;
  border-color: rgba(${rgb}, 0.5);
  color: rgba(${rgb}, 0.9);
}

/* Soft variant */
.forge-btn--soft {
  background: rgba(${rgb}, 0.07);
  border-color: transparent;
  color: rgba(${rgb}, 0.9);
}

/* Disabled state */
.forge-btn--disabled {
  opacity: 0.4;
  cursor: not-allowed;
  pointer-events: none;
}

/* Full width */
.forge-btn--full {
  width: 100%;
}

/* Shadow: ${shadow} */
${shadow === "glow" ? `.forge-btn:hover { box-shadow: 0 0 20px rgba(${rgb}, 0.25), 0 4px 16px rgba(${rgb}, 0.12); }` : ""}
${shadow === "soft" ? `.forge-btn:hover { box-shadow: 0 6px 20px rgba(0,0,0,0.35); }` : ""}

/* Click animation: ${clickAnim} */
${
  clickAnim === "ripple"
    ? `
@keyframes forge-ripple {
  to { transform: scale(20); opacity: 0; }
}
.forge-btn .forge-ripple {
  position: absolute;
  border-radius: 50%;
  width: 10px;
  height: 10px;
  background: rgba(255,255,255,0.25);
  animation: forge-ripple 0.5s ease-out forwards;
  pointer-events: none;
}`
    : ""
}
`;

  return { tsx, css };
}
