import { hexToRgb } from "./utils";

export function generateCheckbox(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const size = (props.size as string) ?? "md";
  const variant = (props.variant as string) ?? "square";
  const items = (props.items as string[]) ?? ["I agree to the terms"];

  const sizeMap: Record<string, string> = {
    sm: "14px",
    md: "16px",
    lg: "20px",
  };
  const fontMap: Record<string, string> = {
    sm: "12px",
    md: "13px",
    lg: "14px",
  };
  const radiusMap: Record<string, string> = {
    square: "3px",
    round: "50%",
    squircle: "30%",
  };

  const tsx = `// ForgeCheckbox — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update checkbox

import { useState } from 'react'
import './ForgeCheckbox.css'

interface ForgeCheckboxProps {
  items?: string[]
  color?: string
  size?: 'sm' | 'md' | 'lg'
  variant?: 'square' | 'round' | 'squircle'
  onChange?: (checked: boolean[]) => void
}

export function ForgeCheckbox({
  items = ${JSON.stringify(items)},
  color = '${color}',
  size = '${size}',
  variant = '${variant}',
  onChange,
}: ForgeCheckboxProps) {
  const [checked, setChecked] = useState<boolean[]>(items.map(() => false))

  function toggle(i: number) {
    const next = [...checked]
    next[i] = !next[i]
    setChecked(next)
    onChange?.(next)
  }

  return (
    <div
      className="forge-checkbox-group"
      style={{ '--forge-checkbox-color': color, '--forge-checkbox-rgb': '${rgb}' } as React.CSSProperties}
    >
      {items.map((item, i) => (
        <label key={i} className={\`forge-checkbox-item forge-checkbox-item--\${size}\`} onClick={() => toggle(i)}>
          <div className={\`forge-checkbox forge-checkbox--\${variant} forge-checkbox--\${size}\${checked[i] ? ' forge-checkbox--checked' : ''}\`}>
            {checked[i] && <span className="forge-checkbox__check">✓</span>}
          </div>
          <span className="forge-checkbox-label">{item}</span>
        </label>
      ))}
    </div>
  )
}
`;

  const css = `/* ForgeCheckbox.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-checkbox-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
  font-family: Inter, sans-serif;
}

.forge-checkbox-item {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  user-select: none;
}

.forge-checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  border: 1px solid rgba(255, 255, 255, 0.15);
  background: rgba(255, 255, 255, 0.04);
  transition: all 0.15s ease;
}

.forge-checkbox--sm { width: ${sizeMap.sm}; height: ${sizeMap.sm}; }
.forge-checkbox--md { width: ${sizeMap.md}; height: ${sizeMap.md}; }
.forge-checkbox--lg { width: ${sizeMap.lg}; height: ${sizeMap.lg}; }

.forge-checkbox--square   { border-radius: ${radiusMap.square}; }
.forge-checkbox--round    { border-radius: ${radiusMap.round}; }
.forge-checkbox--squircle { border-radius: ${radiusMap.squircle}; }

.forge-checkbox--checked {
  background: rgba(var(--forge-checkbox-rgb), 0.2);
  border-color: rgba(var(--forge-checkbox-rgb), 0.6);
  box-shadow: 0 0 8px rgba(var(--forge-checkbox-rgb), 0.2);
}

.forge-checkbox__check {
  font-size: 70%;
  color: var(--forge-checkbox-color);
  line-height: 1;
}

.forge-checkbox-label {
  font-size: ${fontMap[size] ?? fontMap.md};
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-checkbox-item:hover .forge-checkbox {
  border-color: rgba(var(--forge-checkbox-rgb), 0.35);
}
`;
  return { tsx, css };
}
