import { hexToRgb } from "./utils.js";

export function generateCommandPalette(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const placeholder = (props.placeholder as string) ?? "Search…";
  const showCategories = (props.showCategories as boolean) ?? true;
  const showShortcuts = (props.showShortcuts as boolean) ?? true;
  const items = (props.items as string[]) ?? [
    "Components:Button",
    "Components:Card",
    "Actions:Copy command",
  ];

  const tsx = `// ForgeCommand — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update cmdpalette

import { useState, useEffect } from 'react'
import './ForgeCommand.css'

interface CommandItem {
  category: string
  label: string
}

interface ForgeCommandProps {
  items?: string[]
  placeholder?: string
  color?: string
  showCategories?: boolean
  showShortcuts?: boolean
  onSelect?: (item: CommandItem) => void
  // Set trigger to true to use ⌘K keyboard shortcut
  triggerOnKey?: boolean
}

export function ForgeCommand({
  items = ${JSON.stringify(items)},
  placeholder = '${placeholder}',
  color = '${color}',
  showCategories = ${showCategories},
  showShortcuts = ${showShortcuts},
  onSelect,
  triggerOnKey = false,
}: ForgeCommandProps) {
  const [open, setOpen] = useState(!triggerOnKey)
  const [query, setQuery] = useState('')

  // Parse items from "Category:Label" format
  const parsed: CommandItem[] = items.map(item => {
    const [category, ...rest] = item.split(':')
    return { category, label: rest.join(':') || category }
  })

  // Filter by query
  const filtered = query
    ? parsed.filter(i => i.label.toLowerCase().includes(query.toLowerCase()))
    : parsed

  // Group by category
  const grouped = filtered.reduce<Record<string, CommandItem[]>>((acc, item) => {
    if (!acc[item.category]) acc[item.category] = []
    acc[item.category].push(item)
    return acc
  }, {})

  useEffect(() => {
    if (!triggerOnKey) return
    function handleKey(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault()
        setOpen(o => !o)
      }
      if (e.key === 'Escape') setOpen(false)
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [triggerOnKey])

  if (!open) return null

  return (
    <div
      className="forge-cmd-overlay"
      onClick={e => { if (e.target === e.currentTarget) setOpen(false) }}
      style={{ '--forge-cmd-color': color, '--forge-cmd-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className="forge-cmd">
        <div className="forge-cmd__search">
          <span className="forge-cmd__search-icon">⌕</span>
          <input
            className="forge-cmd__input"
            placeholder={placeholder}
            value={query}
            onChange={e => setQuery(e.target.value)}
            autoFocus
          />
          {showShortcuts && <span className="forge-cmd__esc">esc</span>}
        </div>
        <div className="forge-cmd__results">
          {Object.entries(grouped).map(([category, catItems]) => (
            <div key={category}>
              {showCategories && (
                <div className="forge-cmd__category">{category}</div>
              )}
              {catItems.map((item, i) => (
                <button
                  key={i}
                  className="forge-cmd__item"
                  onClick={() => { onSelect?.(item); setOpen(false) }}
                >
                  <span className="forge-cmd__item-label">{item.label}</span>
                  {showShortcuts && <span className="forge-cmd__item-hint">↵</span>}
                </button>
              ))}
            </div>
          ))}
          {filtered.length === 0 && (
            <div className="forge-cmd__empty">No results for "{query}"</div>
          )}
        </div>
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeCommand.css — generated by forge-ui CLI */
.forge-cmd-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding-top: 15vh;
  z-index: 100;
  backdrop-filter: blur(4px);
}

.forge-cmd {
  width: 100%;
  max-width: 520px;
  background: #0f0f12;
  border: 1px solid rgba(255,255,255,0.1);
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 24px 64px rgba(0,0,0,0.5);
  font-family: Inter, sans-serif;
  margin: 0 16px;
}

.forge-cmd__search {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 14px 16px;
  border-bottom: 1px solid rgba(255,255,255,0.06);
}

.forge-cmd__search-icon {
  font-size: 15px;
  color: rgba(240,237,232,0.25);
  flex-shrink: 0;
}

.forge-cmd__input {
  flex: 1;
  background: none;
  border: none;
  outline: none;
  font-family: Inter, sans-serif;
  font-size: 14px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.01em;
}

.forge-cmd__input::placeholder { color: rgba(240,237,232,0.2); }

.forge-cmd__esc {
  font-size: 10px;
  color: rgba(240,237,232,0.2);
  background: rgba(255,255,255,0.06);
  border-radius: 3px;
  padding: 2px 5px;
  letter-spacing: 0.02em;
  flex-shrink: 0;
}

.forge-cmd__results {
  max-height: 320px;
  overflow-y: auto;
  padding: 6px;
}

.forge-cmd__category {
  font-size: 10px;
  font-weight: 400;
  color: rgba(240,237,232,0.2);
  letter-spacing: 0.06em;
  text-transform: uppercase;
  padding: 8px 10px 4px;
}

.forge-cmd__item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  padding: 8px 10px;
  border-radius: 6px;
  background: none;
  border: none;
  font-family: Inter, sans-serif;
  cursor: pointer;
  transition: background 0.1s ease;
  text-align: left;
}

.forge-cmd__item:hover {
  background: rgba(var(--forge-cmd-rgb), 0.08);
}

.forge-cmd__item-label {
  font-size: 13px;
  font-weight: 400;
  color: rgba(240,237,232,0.7);
  letter-spacing: -0.01em;
}

.forge-cmd__item:hover .forge-cmd__item-label { color: #f0ede8; }

.forge-cmd__item-hint {
  font-size: 11px;
  color: rgba(240,237,232,0.15);
}

.forge-cmd__empty {
  padding: 24px;
  text-align: center;
  font-size: 13px;
  color: rgba(240,237,232,0.2);
  letter-spacing: -0.01em;
}
`;
  return { tsx, css };
}
