import { hexToRgb } from "./utils.js";

export function generateCountUp(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const to = (props.to as number) ?? 48200;
  const from = (props.from as number) ?? 0;
  const duration = (props.duration as number) ?? 2000;
  const prefix = (props.prefix as string) ?? "";
  const suffix = (props.suffix as string) ?? "";
  const size = (props.size as string) ?? "xl";
  const showLabel = (props.showLabel as boolean) ?? true;
  const label = (props.label as string) ?? "Total";

  const fontSizeMap: Record<string, string> = {
    sm: "24px",
    md: "32px",
    lg: "48px",
    xl: "64px",
  };

  const tsx = `// ForgeCountUp — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update countup
// Uses requestAnimationFrame — no animation library required.

import { useEffect, useRef, useState } from 'react'
import './ForgeCountUp.css'

interface ForgeCountUpProps {
  from?: number
  to?: number
  duration?: number
  prefix?: string
  suffix?: string
  color?: string
  size?: 'sm' | 'md' | 'lg' | 'xl'
  showLabel?: boolean
  label?: string
}

export function ForgeCountUp({
  from = ${from},
  to = ${to},
  duration = ${duration},
  prefix = '${prefix}',
  suffix = '${suffix}',
  color = '${color}',
  size = '${size}',
  showLabel = ${showLabel},
  label = '${label}',
}: ForgeCountUpProps) {
  const [value, setValue] = useState(from)
  const ref = useRef<HTMLDivElement>(null)
  const started = useRef(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started.current) {
          started.current = true
          const startTime = performance.now()
          const range = to - from

          function tick(now: number) {
            const elapsed = now - startTime
            const progress = Math.min(elapsed / duration, 1)
            // Ease out cubic
            const eased = 1 - Math.pow(1 - progress, 3)
            setValue(Math.round(from + range * eased))
            if (progress < 1) requestAnimationFrame(tick)
          }

          requestAnimationFrame(tick)
          observer.disconnect()
        }
      },
      { threshold: 0.3 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [from, to, duration])

  // Format number with commas
  const formatted = value.toLocaleString()

  return (
    <div
      ref={ref}
      className={\`forge-countup forge-countup--\${size}\`}
      style={{ '--forge-countup-color': color, '--forge-countup-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className="forge-countup__number">
        {prefix}<span className="forge-countup__value">{formatted}</span>{suffix}
      </div>
      {showLabel && <div className="forge-countup__label">{label}</div>}
    </div>
  )
}
`;

  const css = `/* ForgeCountUp.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-countup {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 4px;
  font-family: Inter, sans-serif;
}

.forge-countup__number {
  font-weight: 300;
  letter-spacing: -0.04em;
  color: #f0ede8;
  line-height: 1;
}

.forge-countup--sm .forge-countup__number { font-size: ${fontSizeMap.sm}; }
.forge-countup--md .forge-countup__number { font-size: ${fontSizeMap.md}; }
.forge-countup--lg .forge-countup__number { font-size: ${fontSizeMap.lg}; }
.forge-countup--xl .forge-countup__number { font-size: ${fontSizeMap.xl}; }

.forge-countup__value {
  color: var(--forge-countup-color);
}

.forge-countup__label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.3);
  letter-spacing: -0.01em;
}

@media (prefers-reduced-motion: reduce) {
  .forge-countup__value {
    transition: none;
  }
}
`;
  return { tsx, css };
}
