import { hexToRgb } from "./utils.js";

export function generateDatePicker(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const radius = (props.radius as number) ?? 8;
  const showLabel = (props.showLabel as boolean) ?? true;
  const label = (props.label as string) ?? "Date";

  const tsx = `// ForgeDatePicker — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update datepicker

import { useState } from 'react'
import './ForgeDatePicker.css'

interface ForgeDatePickerProps {
  label?: string
  color?: string
  radius?: number
  showLabel?: boolean
  value?: string
  onChange?: (date: string) => void
}

const DAYS = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December']

export function ForgeDatePicker({
  label = '${label}',
  color = '${color}',
  radius = ${radius},
  showLabel = ${showLabel},
  value,
  onChange,
}: ForgeDatePickerProps) {
  const today = new Date()
  const [open, setOpen] = useState(false)
  const [viewYear, setViewYear] = useState(today.getFullYear())
  const [viewMonth, setViewMonth] = useState(today.getMonth())
  const [selected, setSelected] = useState<string>(value ?? '')

  const current = selected ? new Date(selected) : null

  function getDaysInMonth(y: number, m: number) {
    return new Date(y, m + 1, 0).getDate()
  }

  function getFirstDayOfMonth(y: number, m: number) {
    return new Date(y, m, 1).getDay()
  }

  function selectDate(day: number) {
    const d = new Date(viewYear, viewMonth, day)
    const iso = d.toISOString().split('T')[0]
    setSelected(iso)
    onChange?.(iso)
    setOpen(false)
  }

  function prevMonth() {
    if (viewMonth === 0) { setViewMonth(11); setViewYear(y => y - 1) }
    else setViewMonth(m => m - 1)
  }

  function nextMonth() {
    if (viewMonth === 11) { setViewMonth(0); setViewYear(y => y + 1) }
    else setViewMonth(m => m + 1)
  }

  const daysInMonth = getDaysInMonth(viewYear, viewMonth)
  const firstDay = getFirstDayOfMonth(viewYear, viewMonth)
  const cells = Array.from({ length: firstDay + daysInMonth }, (_, i) =>
    i < firstDay ? null : i - firstDay + 1
  )

  function formatDisplay(iso: string) {
    const d = new Date(iso)
    return \`\${MONTHS[d.getMonth()]} \${d.getDate()}, \${d.getFullYear()}\`
  }

  // suppress unused warning — current is available for callers extending this component
  void current

  return (
    <div
      className="forge-dp-wrap"
      style={{ '--forge-dp-color': color, '--forge-dp-rgb': '${rgb}' } as React.CSSProperties}
    >
      {showLabel && label && (
        <label className="forge-dp-label">{label}</label>
      )}
      <button
        type="button"
        className="forge-dp-trigger"
        style={{ borderRadius: radius }}
        onClick={() => setOpen(o => !o)}
      >
        <span className={\`forge-dp-trigger__text\${!selected ? ' forge-dp-trigger__text--placeholder' : ''}\`}>
          {selected ? formatDisplay(selected) : 'Select a date'}
        </span>
        <span className="forge-dp-trigger__icon">◫</span>
      </button>

      {open && (
        <div className="forge-dp-calendar" style={{ borderRadius: radius }}>
          {/* Month navigation */}
          <div className="forge-dp-nav">
            <button type="button" className="forge-dp-nav__btn" onClick={prevMonth}>←</button>
            <span className="forge-dp-nav__label">
              {MONTHS[viewMonth]} {viewYear}
            </span>
            <button type="button" className="forge-dp-nav__btn" onClick={nextMonth}>→</button>
          </div>

          {/* Day headers */}
          <div className="forge-dp-grid">
            {DAYS.map(d => (
              <div key={d} className="forge-dp-day-header">{d}</div>
            ))}

            {/* Date cells */}
            {cells.map((day, i) => {
              if (!day) return <div key={\`empty-\${i}\`} />
              const iso = \`\${viewYear}-\${String(viewMonth + 1).padStart(2, '0')}-\${String(day).padStart(2, '0')}\`
              const isSelected = selected === iso
              const isToday = iso === today.toISOString().split('T')[0]
              return (
                <button
                  key={iso}
                  type="button"
                  className={\`forge-dp-cell\${isSelected ? ' forge-dp-cell--selected' : ''}\${isToday ? ' forge-dp-cell--today' : ''}\`}
                  onClick={() => selectDate(day)}
                >
                  {day}
                </button>
              )
            })}
          </div>
        </div>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeDatePicker.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-dp-wrap {
  display: flex;
  flex-direction: column;
  gap: 5px;
  font-family: Inter, sans-serif;
  position: relative;
  width: fit-content;
}

.forge-dp-label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-dp-trigger {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 32px;
  padding: 9px 14px;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  cursor: pointer;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
  min-width: 200px;
}

.forge-dp-trigger:hover,
.forge-dp-trigger:focus {
  border-color: rgba(var(--forge-dp-rgb), 0.4);
  box-shadow: 0 0 0 3px rgba(var(--forge-dp-rgb), 0.1);
  outline: none;
}

.forge-dp-trigger__text {
  font-size: 13px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.01em;
}

.forge-dp-trigger__text--placeholder {
  color: rgba(240, 237, 232, 0.25);
}

.forge-dp-trigger__icon {
  font-size: 13px;
  color: rgba(240, 237, 232, 0.25);
}

/* Calendar dropdown */
.forge-dp-calendar {
  position: absolute;
  top: calc(100% + 6px);
  left: 0;
  z-index: 50;
  background: #0f0f12;
  border: 1px solid rgba(255, 255, 255, 0.08);
  padding: 12px;
  min-width: 240px;
  box-shadow: 0 16px 40px rgba(0, 0, 0, 0.4);
}

/* Month nav */
.forge-dp-nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
}

.forge-dp-nav__label {
  font-size: 13px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.01em;
}

.forge-dp-nav__btn {
  background: none;
  border: none;
  color: rgba(240, 237, 232, 0.4);
  cursor: pointer;
  font-size: 14px;
  padding: 4px 8px;
  border-radius: 4px;
  transition: color 0.15s ease, background 0.15s ease;
}

.forge-dp-nav__btn:hover {
  color: #f0ede8;
  background: rgba(255, 255, 255, 0.05);
}

/* Grid */
.forge-dp-grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 2px;
}

.forge-dp-day-header {
  font-size: 10px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.2);
  text-align: center;
  padding: 4px 0;
  letter-spacing: 0.04em;
}

.forge-dp-cell {
  aspect-ratio: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.5);
  background: none;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: background 0.1s ease, color 0.1s ease;
  letter-spacing: -0.01em;
}

.forge-dp-cell:hover {
  background: rgba(var(--forge-dp-rgb), 0.1);
  color: var(--forge-dp-color);
}

.forge-dp-cell--today {
  color: var(--forge-dp-color);
  font-weight: 500;
}

.forge-dp-cell--selected {
  background: rgba(var(--forge-dp-rgb), 0.2);
  color: var(--forge-dp-color);
  border: 1px solid rgba(var(--forge-dp-rgb), 0.4);
}

@media (prefers-reduced-motion: reduce) {
  .forge-dp-trigger,
  .forge-dp-cell,
  .forge-dp-nav__btn { transition: none; }
}
`;
  return { tsx, css };
}
