import { hexToRgb } from "./utils.js";

export function generateDrawer(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const side = (props.side as string) ?? "right";
  const width = (props.width as number) ?? 280;
  const showOverlay = (props.showOverlay as boolean) ?? true;
  const title = (props.title as string) ?? "Drawer";

  const tsx = `// ForgeDrawer — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update drawer

import { useEffect } from 'react'
import './ForgeDrawer.css'

interface ForgeDrawerProps {
  open: boolean
  onClose: () => void
  title?: string
  children?: React.ReactNode
  color?: string
  side?: 'left' | 'right'
  width?: number
  showOverlay?: boolean
}

export function ForgeDrawer({
  open,
  onClose,
  title = '${title}',
  children,
  color = '${color}',
  side = '${side}',
  width = ${width},
  showOverlay = ${showOverlay},
}: ForgeDrawerProps) {
  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }
    if (open) document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [open, onClose])

  if (!open) return null

  return (
    <div
      className="forge-drawer-root"
      style={{ '--forge-drawer-color': color, '--forge-drawer-rgb': '${rgb}' } as React.CSSProperties}
    >
      {showOverlay && (
        <div className="forge-drawer-overlay" onClick={onClose} />
      )}
      <div
        className={\`forge-drawer forge-drawer--\${side}\`}
        style={{ width }}
        role="dialog"
        aria-modal="true"
      >
        <div className="forge-drawer__header">
          <span className="forge-drawer__title">{title}</span>
          <button className="forge-drawer__close" onClick={onClose} aria-label="Close">✕</button>
        </div>
        <div className="forge-drawer__body">{children}</div>
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeDrawer.css — generated by forge-ui CLI */
.forge-drawer-root {
  position: fixed;
  inset: 0;
  z-index: 100;
}

.forge-drawer-overlay {
  position: absolute;
  inset: 0;
  background: rgba(0,0,0,0.5);
  backdrop-filter: blur(2px);
}

.forge-drawer {
  position: absolute;
  top: 0;
  bottom: 0;
  background: #0f0f12;
  border-color: rgba(255,255,255,0.08);
  border-style: solid;
  border-width: 0;
  font-family: Inter, sans-serif;
  display: flex;
  flex-direction: column;
  box-shadow: 0 0 40px rgba(0,0,0,0.4);
}

.forge-drawer--right { right: 0; border-left-width: 1px; }
.forge-drawer--left  { left: 0;  border-right-width: 1px; }

.forge-drawer__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 24px;
  border-bottom: 1px solid rgba(255,255,255,0.06);
}

.forge-drawer__title {
  font-size: 14px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.02em;
}

.forge-drawer__close {
  background: none;
  border: none;
  color: rgba(240,237,232,0.3);
  cursor: pointer;
  font-size: 13px;
  padding: 4px;
  transition: color 0.15s ease;
}
.forge-drawer__close:hover { color: #f0ede8; }

.forge-drawer__body {
  flex: 1;
  overflow-y: auto;
  padding: 20px 24px;
  font-size: 13px;
  font-weight: 300;
  color: rgba(240,237,232,0.5);
  line-height: 1.6;
}
`;
  return { tsx, css };
}
