import { hexToRgb } from "./utils.js";

export function generateDropdown(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const radius = (props.radius as number) ?? 8;
  const label = (props.label as string) ?? "Options";
  const showDivider = (props.showDivider as boolean) ?? true;
  const items = (props.items as string[]) ?? ["Edit", "Duplicate", "Delete"];
  const dangerItems =
    (props.dangerItems as boolean[]) ?? items.map(() => false);

  const tsx = `// ForgeDropdown — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update dropdown

import { useState, useRef, useEffect } from 'react'
import './ForgeDropdown.css'

interface ForgeDropdownProps {
  label?: string
  items?: string[]
  dangerItems?: boolean[]
  color?: string
  radius?: number
  showDivider?: boolean
  onSelect?: (item: string, index: number) => void
}

export function ForgeDropdown({
  label = '${label}',
  items = ${JSON.stringify(items)},
  dangerItems = ${JSON.stringify(dangerItems)},
  color = '${color}',
  radius = ${radius},
  showDivider = ${showDivider},
  onSelect,
}: ForgeDropdownProps) {
  const [open, setOpen] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  return (
    <div
      ref={ref}
      className="forge-dropdown-wrap"
      style={{ '--forge-dropdown-color': color, '--forge-dropdown-rgb': '${rgb}' } as React.CSSProperties}
    >
      <button
        className="forge-dropdown-trigger"
        style={{ borderRadius: radius }}
        onClick={() => setOpen(o => !o)}
        aria-expanded={open}
      >
        {label}
        <span className="forge-dropdown-trigger__arrow">{open ? '▴' : '▾'}</span>
      </button>

      {open && (
        <div className="forge-dropdown-menu" style={{ borderRadius: radius }}>
          {items.map((item, i) => {
            const isDanger = dangerItems?.[i] ?? false
            const isLast = i === items.length - 1
            return (
              <div key={i}>
                {showDivider && isLast && items.length > 1 && (
                  <div className="forge-dropdown-divider" />
                )}
                <button
                  className={\`forge-dropdown-item\${isDanger ? ' forge-dropdown-item--danger' : ''}\`}
                  onClick={() => { onSelect?.(item, i); setOpen(false) }}
                >
                  {item}
                </button>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeDropdown.css — generated by forge-ui CLI */
.forge-dropdown-wrap {
  position: relative;
  display: inline-block;
  font-family: Inter, sans-serif;
}

.forge-dropdown-trigger {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 8px 14px;
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.08);
  color: rgba(240,237,232,0.7);
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  letter-spacing: -0.01em;
  cursor: pointer;
  transition: all 0.15s ease;
}
.forge-dropdown-trigger:hover {
  border-color: rgba(var(--forge-dropdown-rgb), 0.3);
  color: #f0ede8;
}

.forge-dropdown-trigger__arrow {
  font-size: 10px;
  color: rgba(240,237,232,0.3);
}

.forge-dropdown-menu {
  position: absolute;
  top: calc(100% + 4px);
  left: 0;
  z-index: 50;
  background: #0f0f12;
  border: 1px solid rgba(255,255,255,0.08);
  min-width: 160px;
  padding: 4px;
  box-shadow: 0 8px 24px rgba(0,0,0,0.3);
}

.forge-dropdown-item {
  display: block;
  width: 100%;
  text-align: left;
  padding: 7px 10px;
  border-radius: 4px;
  background: none;
  border: none;
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  color: rgba(240,237,232,0.6);
  letter-spacing: -0.01em;
  cursor: pointer;
  transition: all 0.1s ease;
}
.forge-dropdown-item:hover {
  background: rgba(var(--forge-dropdown-rgb), 0.08);
  color: #f0ede8;
}
.forge-dropdown-item--danger { color: rgba(226,75,74,0.7); }
.forge-dropdown-item--danger:hover { background: rgba(226,75,74,0.08); color: #e24b4a; }

.forge-dropdown-divider {
  height: 1px;
  background: rgba(255,255,255,0.06);
  margin: 4px 0;
}
`;
  return { tsx, css };
}
