export function generateFadeUp(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const duration = (props.duration as number) ?? 600;
  const stagger = (props.stagger as boolean) ?? true;

  const tsx = `// ForgeFadeUp — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update fadeup
// Pure CSS animation — no Framer Motion required.

import { useEffect, useRef, useState } from 'react'
import './ForgeFadeUp.css'

interface ForgeFadeUpProps {
  // Pass a string with newlines to stagger each line,
  // or pass children for a single animated block.
  text?: string
  children?: React.ReactNode
  color?: string
  duration?: number
  stagger?: boolean
  delay?: number
}

export function ForgeFadeUp({
  text,
  children,
  color = '${color}',
  duration = ${duration},
  stagger = ${stagger},
  delay = 0,
}: ForgeFadeUpProps) {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    // Use IntersectionObserver so animation triggers on scroll into view
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } },
      { threshold: 0.1 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  // If text prop provided, split into lines and stagger each one
  if (text) {
    const lines = text.split('\\n').filter(Boolean)
    return (
      <div ref={ref} style={{ '--forge-fadeup-color': color } as React.CSSProperties}>
        {lines.map((line, i) => (
          <div
            key={i}
            className={\`forge-fadeup-line\${visible ? ' forge-fadeup-line--visible' : ''}\`}
            style={{
              animationDuration: \`\${duration}ms\`,
              animationDelay: stagger ? \`\${delay + i * 80}ms\` : \`\${delay}ms\`,
            }}
          >
            {line}
          </div>
        ))}
      </div>
    )
  }

  // Otherwise animate children as a single block
  return (
    <div
      ref={ref}
      className={\`forge-fadeup-block\${visible ? ' forge-fadeup-block--visible' : ''}\`}
      style={{
        '--forge-fadeup-color': color,
        animationDuration: \`\${duration}ms\`,
        animationDelay: \`\${delay}ms\`,
      } as React.CSSProperties}
    >
      {children}
    </div>
  )
}
`;

  const css = `/* ForgeFadeUp.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

@keyframes forge-fade-up {
  from {
    opacity: 0;
    transform: translateY(16px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Per-line stagger mode */
.forge-fadeup-line {
  opacity: 0;
  transform: translateY(16px);
  display: block;
  font-family: Inter, sans-serif;
  font-weight: 300;
  color: #f0ede8;
  letter-spacing: -0.02em;
  line-height: 1.2;
}

.forge-fadeup-line--visible {
  animation: forge-fade-up both;
  animation-fill-mode: both;
}

/* Single block mode */
.forge-fadeup-block {
  opacity: 0;
  transform: translateY(16px);
}

.forge-fadeup-block--visible {
  animation: forge-fade-up both;
  animation-fill-mode: both;
}

/* Respect reduced motion */
@media (prefers-reduced-motion: reduce) {
  .forge-fadeup-line,
  .forge-fadeup-block {
    opacity: 1;
    transform: none;
    animation: none;
  }
}
`;
  return { tsx, css };
}
