import { hexToRgb } from "./utils.js";

export function generateInput(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const size = (props.size as string) ?? "md";
  const radius = (props.radius as number) ?? 8;
  const showLabel = (props.showLabel as boolean) ?? true;
  const showHint = (props.showHint as boolean) ?? true;
  const label = (props.label as string) ?? "Email address";
  const placeholder = (props.placeholder as string) ?? "hello@example.com";
  const hint = (props.hint as string) ?? "";
  const type = (props.type as string) ?? "text";

  const paddingMap: Record<string, string> = {
    sm: "6px 10px",
    md: "9px 14px",
    lg: "12px 16px",
  };
  const fontSizeMap: Record<string, string> = {
    sm: "12px",
    md: "13px",
    lg: "14px",
  };

  const tsx = `// ForgeInput — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update input

import { useState } from 'react'
import './ForgeInput.css'

interface ForgeInputProps {
  label?: string
  placeholder?: string
  hint?: string
  type?: 'text' | 'email' | 'password' | 'number' | 'search'
  color?: string
  size?: 'sm' | 'md' | 'lg'
  radius?: number
  showLabel?: boolean
  showHint?: boolean
  state?: 'default' | 'error' | 'success' | 'disabled'
  value?: string
  onChange?: (value: string) => void
}

export function ForgeInput({
  label = '${label}',
  placeholder = '${placeholder}',
  hint = '${hint}',
  type = '${type}',
  color = '${color}',
  size = '${size}',
  radius = ${radius},
  showLabel = ${showLabel},
  showHint = ${showHint},
  state = 'default',
  value,
  onChange,
}: ForgeInputProps) {
  const [internal, setInternal] = useState('')
  const controlled = value !== undefined
  const current = controlled ? value : internal

  const stateColorMap: Record<string, string> = {
    default: color,
    error: '#e24b4a',
    success: '#1D9E75',
    disabled: '#555',
  }
  const activeColor = stateColorMap[state] ?? color

  return (
    <div
      className={\`forge-input-wrap forge-input-wrap--\${state}\`}
      style={{ '--forge-input-color': activeColor, '--forge-input-rgb': '${rgb}' } as React.CSSProperties}
    >
      {showLabel && label && (
        <label className="forge-input-label">{label}</label>
      )}
      <input
        className={\`forge-input forge-input--\${size}\`}
        type={type}
        placeholder={placeholder}
        value={current}
        disabled={state === 'disabled'}
        style={{ borderRadius: radius }}
        onChange={e => {
          if (!controlled) setInternal(e.target.value)
          onChange?.(e.target.value)
        }}
      />
      {showHint && hint && (
        <span className="forge-input-hint">{hint}</span>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeInput.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-input-wrap {
  display: flex;
  flex-direction: column;
  gap: 5px;
  font-family: Inter, sans-serif;
  width: 100%;
}

.forge-input-label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-input {
  width: 100%;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  color: #f0ede8;
  font-family: Inter, sans-serif;
  font-weight: 400;
  letter-spacing: -0.01em;
  outline: none;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
  box-sizing: border-box;
}

.forge-input--sm { padding: ${paddingMap.sm}; font-size: ${fontSizeMap.sm}; }
.forge-input--md { padding: ${paddingMap.md}; font-size: ${fontSizeMap.md}; }
.forge-input--lg { padding: ${paddingMap.lg}; font-size: ${fontSizeMap.lg}; }

.forge-input::placeholder {
  color: rgba(240, 237, 232, 0.2);
}

.forge-input:focus {
  border-color: rgba(var(--forge-input-rgb), 0.5);
  box-shadow: 0 0 0 3px rgba(var(--forge-input-rgb), 0.12);
}

/* States */
.forge-input-wrap--error .forge-input {
  border-color: rgba(226, 75, 74, 0.4);
}
.forge-input-wrap--error .forge-input:focus {
  border-color: #e24b4a;
  box-shadow: 0 0 0 3px rgba(226, 75, 74, 0.12);
}
.forge-input-wrap--success .forge-input {
  border-color: rgba(29, 158, 117, 0.4);
}
.forge-input-wrap--success .forge-input:focus {
  border-color: #1D9E75;
  box-shadow: 0 0 0 3px rgba(29, 158, 117, 0.12);
}
.forge-input-wrap--disabled .forge-input {
  opacity: 0.4;
  cursor: not-allowed;
  pointer-events: none;
}

.forge-input-hint {
  font-size: 11px;
  color: rgba(240, 237, 232, 0.3);
  letter-spacing: -0.01em;
}
.forge-input-wrap--error .forge-input-hint   { color: #e24b4a; }
.forge-input-wrap--success .forge-input-hint { color: #1D9E75; }
`;
  return { tsx, css };
}
