import { hexToRgb } from "./utils.js";

export function generateLineChart(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#1D9E75";
  const rgb = hexToRgb(color);
  const color2 = (props.color2 as string) ?? "#EF9F27";
  const tension = (props.tension as number) ?? 0.4;
  const fill = (props.fill as boolean) ?? true;
  const showGrid = (props.showGrid as boolean) ?? true;
  const showDots = (props.showDots as boolean) ?? true;
  const animated = (props.animated as boolean) ?? true;
  const title = (props.title as string) ?? "Chart";

  const tsx = `// ForgeLineChart — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update linechart
// Requires Chart.js — add to your layout:
// <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js" />

import { useEffect, useRef } from 'react'
import './ForgeLineChart.css'

interface ForgeLineChartProps {
  title?: string
  labels?: string[]
  series?: { label: string; data: number[]; color?: string }[]
  color?: string
  color2?: string
  tension?: number
  fill?: boolean
  showGrid?: boolean
  showDots?: boolean
  animated?: boolean
  height?: number
}

const DEFAULT_LABELS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
const DEFAULT_DATA = [30, 55, 45, 70, 60, 88]

export function ForgeLineChart({
  title = '${title}',
  labels = DEFAULT_LABELS,
  series,
  color = '${color}',
  color2 = '${color2}',
  tension = ${tension},
  fill = ${fill},
  showGrid = ${showGrid},
  showDots = ${showDots},
  animated = ${animated},
  height = 260,
}: ForgeLineChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<unknown>(null)

  const resolvedSeries = series ?? [
    { label: 'Series 1', data: DEFAULT_DATA, color },
    { label: 'Series 2', data: DEFAULT_DATA.map(v => Math.round(v * 0.6)), color: color2 },
  ]

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const Chart = (window as any).Chart
    if (!Chart || !canvasRef.current) return
    if (chartRef.current) (chartRef.current as any).destroy()

    chartRef.current = new Chart(canvasRef.current, {
      type: 'line',
      data: {
        labels,
        datasets: resolvedSeries.map(s => ({
          label: s.label,
          data: s.data,
          borderColor: s.color ?? color,
          backgroundColor: fill ? \`\${s.color ?? color}22\` : 'transparent',
          tension,
          fill,
          pointRadius: showDots ? 4 : 0,
          pointBackgroundColor: s.color ?? color,
          borderWidth: 2,
        })),
      },
      options: {
        responsive: true,
        animation: animated,
        plugins: {
          legend: { display: true, labels: { color: 'rgba(240,237,232,0.4)', font: { family: 'Inter', size: 11 }, boxWidth: 10 } },
          title: { display: !!title, text: title, color: 'rgba(240,237,232,0.6)', font: { family: 'Inter', size: 13, weight: '400' } },
        },
        scales: {
          x: { grid: { display: false }, ticks: { color: 'rgba(240,237,232,0.3)', font: { family: 'Inter', size: 11 } }, border: { display: false } },
          y: { grid: { display: showGrid, color: 'rgba(255,255,255,0.04)' }, ticks: { color: 'rgba(240,237,232,0.3)', font: { family: 'Inter', size: 11 } }, border: { display: false } },
        },
      },
    })

    return () => { if (chartRef.current) (chartRef.current as any).destroy() }
  }, [labels, color, color2, tension, fill, showGrid, showDots, animated, title])

  return (
    <div
      className="forge-linechart-wrap"
      style={{ '--forge-chart-color': color, '--forge-chart-rgb': '${rgb}' } as React.CSSProperties}
    >
      <canvas ref={canvasRef} height={height} />
    </div>
  )
}
`;

  const css = `/* ForgeLineChart.css — generated by forge-ui CLI */
.forge-linechart-wrap {
  width: 100%;
  background: #0f0f12;
  border: 1px solid rgba(255,255,255,0.06);
  border-radius: 10px;
  padding: 16px;
  box-sizing: border-box;
}
`;
  return { tsx, css };
}
