import { hexToRgb } from "./utils.js";
export function generateModal(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const radius = (props.radius as number) ?? 12;
  const showClose = (props.showClose as boolean) ?? true;
  const showFooter = (props.showFooter as boolean) ?? true;
  const title = (props.title as string) ?? "Modal title";
  const primaryBtn = (props.primaryBtn as string) ?? "Confirm";
  const secondaryBtn = (props.secondaryBtn as string) ?? "Cancel";

  const tsx = `// ForgeModal — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update modal

import { useEffect } from 'react'
import './ForgeModal.css'

interface ForgeModalProps {
  open: boolean
  onClose: () => void
  title?: string
  children?: React.ReactNode
  color?: string
  radius?: number
  showClose?: boolean
  showFooter?: boolean
  primaryBtn?: string
  secondaryBtn?: string
  onPrimary?: () => void
  onSecondary?: () => void
}

export function ForgeModal({
  open,
  onClose,
  title = '${title}',
  children,
  color = '${color}',
  radius = ${radius},
  showClose = ${showClose},
  showFooter = ${showFooter},
  primaryBtn = '${primaryBtn}',
  secondaryBtn = '${secondaryBtn}',
  onPrimary,
  onSecondary,
}: ForgeModalProps) {
  // Close on Escape key
  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }
    if (open) document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [open, onClose])

  if (!open) return null

  return (
    <div
      className="forge-modal-overlay"
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
      style={{ '--forge-modal-color': color, '--forge-modal-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className="forge-modal" style={{ borderRadius: radius }} role="dialog" aria-modal="true">
        <div className="forge-modal__header">
          <h2 className="forge-modal__title">{title}</h2>
          {showClose && (
            <button className="forge-modal__close" onClick={onClose} aria-label="Close">✕</button>
          )}
        </div>
        <div className="forge-modal__body">{children}</div>
        {showFooter && (
          <div className="forge-modal__footer">
            <button className="forge-modal__btn forge-modal__btn--secondary" onClick={onSecondary ?? onClose}>
              {secondaryBtn}
            </button>
            <button className="forge-modal__btn forge-modal__btn--primary" onClick={onPrimary ?? onClose}>
              {primaryBtn}
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeModal.css — generated by forge-ui CLI */
.forge-modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;
  padding: 16px;
  backdrop-filter: blur(4px);
}

.forge-modal {
  background: #0f0f12;
  border: 1px solid rgba(255, 255, 255, 0.08);
  width: 100%;
  max-width: 480px;
  font-family: Inter, sans-serif;
  box-shadow: 0 24px 64px rgba(0, 0, 0, 0.5);
}

.forge-modal__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 24px 0;
}

.forge-modal__title {
  font-size: 15px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.02em;
  margin: 0;
}

.forge-modal__close {
  background: none;
  border: none;
  color: rgba(240, 237, 232, 0.3);
  cursor: pointer;
  font-size: 13px;
  padding: 4px;
  transition: color 0.15s ease;
}
.forge-modal__close:hover { color: #f0ede8; }

.forge-modal__body {
  padding: 16px 24px;
  font-size: 13px;
  font-weight: 300;
  color: rgba(240, 237, 232, 0.5);
  line-height: 1.6;
  letter-spacing: -0.01em;
}

.forge-modal__footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  padding: 0 24px 20px;
}

.forge-modal__btn {
  font-family: Inter, sans-serif;
  font-size: 12px;
  font-weight: 400;
  letter-spacing: -0.01em;
  padding: 8px 16px;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.15s ease;
}

.forge-modal__btn--secondary {
  background: transparent;
  border: 1px solid rgba(255, 255, 255, 0.08);
  color: rgba(240, 237, 232, 0.4);
}
.forge-modal__btn--secondary:hover {
  border-color: rgba(255, 255, 255, 0.15);
  color: #f0ede8;
}

.forge-modal__btn--primary {
  background: rgba(var(--forge-modal-rgb), 0.15);
  border: 1px solid rgba(var(--forge-modal-rgb), 0.3);
  color: rgba(var(--forge-modal-rgb), 0.9);
}
.forge-modal__btn--primary:hover {
  background: rgba(var(--forge-modal-rgb), 0.22);
  border-color: rgba(var(--forge-modal-rgb), 0.5);
}
`;
  return { tsx, css };
}
