import { hexToRgb } from "./utils.js";

export function generateMorphBlob(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const color2 = (props.color2 as string) ?? "#D4537E";
  const size = (props.size as number) ?? 120;
  const speed = (props.speed as string) ?? "normal";
  const opacity = (props.opacity as number) ?? 0.8;
  const blur = (props.blur as number) ?? 0;
  const gradient = (props.gradient as boolean) ?? true;

  const durationMap: Record<string, string> = {
    slow: "8s",
    normal: "5s",
    fast: "3s",
  };

  const tsx = `// ForgeMorphBlob — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update morphblob
// Pure CSS border-radius morphing — no SVG or canvas required.

import './ForgeMorphBlob.css'

interface ForgeMorphBlobProps {
  color?: string
  color2?: string
  size?: number
  speed?: 'slow' | 'normal' | 'fast'
  opacity?: number
  blur?: number
  gradient?: boolean
}

export function ForgeMorphBlob({
  color = '${color}',
  color2 = '${color2}',
  size = ${size},
  speed = '${speed}',
  opacity = ${opacity},
  blur = ${blur},
  gradient = ${gradient},
}: ForgeMorphBlobProps) {
  return (
    <div
      className={\`forge-blob forge-blob--\${speed}\`}
      style={{
        '--forge-blob-color': color,
        '--forge-blob-color2': color2,
        '--forge-blob-rgb': '${rgb}',
        width: size,
        height: size,
        opacity,
        filter: blur > 0 ? \`blur(\${blur}px)\` : undefined,
        background: gradient
          ? \`radial-gradient(circle at 30% 30%, \${color}, \${color2})\`
          : color,
      } as React.CSSProperties}
    />
  )
}
`;

  const css = `/* ForgeMorphBlob.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

@keyframes forge-morph-slow {
  0%   { border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%; }
  25%  { border-radius: 30% 60% 70% 40% / 50% 60% 30% 60%; }
  50%  { border-radius: 50% 60% 30% 60% / 30% 60% 70% 40%; }
  75%  { border-radius: 60% 40% 60% 30% / 70% 30% 50% 60%; }
  100% { border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%; }
}

.forge-blob {
  display: block;
  flex-shrink: 0;
}

.forge-blob--slow   { animation: forge-morph-slow ${durationMap.slow} ease-in-out infinite; }
.forge-blob--normal { animation: forge-morph-slow ${durationMap.normal} ease-in-out infinite; }
.forge-blob--fast   { animation: forge-morph-slow ${durationMap.fast} ease-in-out infinite; }

@media (prefers-reduced-motion: reduce) {
  .forge-blob {
    animation: none;
    border-radius: 50%;
  }
}
`;
  return { tsx, css };
}
