import { hexToRgb } from "./utils.js";

export function generateNavbar(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const brand = (props.brand as string) ?? "FORGE";
  const variant = (props.variant as string) ?? "dark";
  const showCta = (props.showCta as boolean) ?? true;
  const ctaText = (props.ctaText as string) ?? "Get started";
  const showLogo = (props.showLogo as boolean) ?? true;
  const links = (props.links as string[]) ?? ["Work", "About", "Contact"];

  const tsx = `// ForgeNavbar — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update navbar
// Note: links use <a> tags — swap for Next.js <Link> if needed.

import { useState } from 'react'
import './ForgeNavbar.css'

interface ForgeNavbarProps {
  brand?: string
  links?: { label: string; href: string }[] | string[]
  color?: string
  variant?: 'dark' | 'light'
  showLogo?: boolean
  showCta?: boolean
  ctaText?: string
  onCtaClick?: () => void
}

export function ForgeNavbar({
  brand = '${brand}',
  links = ${JSON.stringify(links)},
  color = '${color}',
  variant = '${variant}',
  showLogo = ${showLogo},
  showCta = ${showCta},
  ctaText = '${ctaText}',
  onCtaClick,
}: ForgeNavbarProps) {
  const [open, setOpen] = useState(false)

  // Normalise links — accept both strings and { label, href } objects
  const normalisedLinks = links.map(l =>
    typeof l === 'string' ? { label: l, href: \`#\${l.toLowerCase()}\` } : l
  )

  return (
    <header
      className={\`forge-navbar forge-navbar--\${variant}\`}
      style={{ '--forge-navbar-color': color, '--forge-navbar-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className="forge-navbar__inner">
        {/* Logo / brand */}
        <a href="/" className="forge-navbar__brand">
          {showLogo && <span className="forge-navbar__gem" />}
          <span className="forge-navbar__brand-name">{brand}</span>
        </a>

        {/* Desktop nav */}
        <nav className="forge-navbar__links" aria-label="Main navigation">
          {normalisedLinks.map(link => (
            <a key={link.label} href={link.href} className="forge-navbar__link">
              {link.label}
            </a>
          ))}
        </nav>

        {/* CTA + mobile toggle */}
        <div className="forge-navbar__right">
          {showCta && (
            <button className="forge-navbar__cta" onClick={onCtaClick}>
              {ctaText}
            </button>
          )}
          <button
            className="forge-navbar__toggle"
            onClick={() => setOpen(o => !o)}
            aria-label="Toggle menu"
            aria-expanded={open}
          >
            {open ? '✕' : '☰'}
          </button>
        </div>
      </div>

      {/* Mobile menu */}
      {open && (
        <nav className="forge-navbar__mobile" aria-label="Mobile navigation">
          {normalisedLinks.map(link => (
            <a
              key={link.label}
              href={link.href}
              className="forge-navbar__mobile-link"
              onClick={() => setOpen(false)}
            >
              {link.label}
            </a>
          ))}
          {showCta && (
            <button className="forge-navbar__cta forge-navbar__cta--mobile" onClick={onCtaClick}>
              {ctaText}
            </button>
          )}
        </nav>
      )}
    </header>
  )
}
`;

  const css = `/* ForgeNavbar.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-navbar {
  width: 100%;
  font-family: Inter, sans-serif;
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  position: relative;
}

.forge-navbar--dark  { background: #09090b; }
.forge-navbar--light { background: #ffffff; }

.forge-navbar__inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 56px;
  padding: 0 24px;
  max-width: 1200px;
  margin: 0 auto;
}

/* Brand */
.forge-navbar__brand {
  display: flex;
  align-items: center;
  gap: 8px;
  text-decoration: none;
}

.forge-navbar__gem {
  width: 18px;
  height: 18px;
  background: conic-gradient(from 0deg, #e24b4a, #EF9F27, #1D9E75, #378ADD, #7F77DD, #D4537E, #e24b4a);
  border-radius: 4px;
  flex-shrink: 0;
}

.forge-navbar__brand-name {
  font-size: 14px;
  font-weight: 500;
  letter-spacing: -0.02em;
  color: #f0ede8;
}

.forge-navbar--light .forge-navbar__brand-name {
  color: #09090b;
}

/* Desktop links */
.forge-navbar__links {
  display: flex;
  align-items: center;
  gap: 4px;
}

.forge-navbar__link {
  font-size: 13px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.45);
  text-decoration: none;
  letter-spacing: -0.01em;
  padding: 6px 10px;
  border-radius: 6px;
  transition: color 0.15s ease, background 0.15s ease;
}

.forge-navbar__link:hover {
  color: #f0ede8;
  background: rgba(255, 255, 255, 0.05);
}

.forge-navbar--light .forge-navbar__link {
  color: rgba(9, 9, 11, 0.5);
}

.forge-navbar--light .forge-navbar__link:hover {
  color: #09090b;
  background: rgba(0, 0, 0, 0.05);
}

/* Right side */
.forge-navbar__right {
  display: flex;
  align-items: center;
  gap: 8px;
}

/* CTA button */
.forge-navbar__cta {
  font-family: Inter, sans-serif;
  font-size: 12px;
  font-weight: 400;
  letter-spacing: -0.01em;
  padding: 7px 16px;
  border-radius: 6px;
  border: 1px solid rgba(var(--forge-navbar-rgb), 0.3);
  background: rgba(var(--forge-navbar-rgb), 0.1);
  color: rgba(var(--forge-navbar-rgb), 0.9);
  cursor: pointer;
  transition: all 0.15s ease;
}

.forge-navbar__cta:hover {
  background: rgba(var(--forge-navbar-rgb), 0.18);
  border-color: rgba(var(--forge-navbar-rgb), 0.5);
}

/* Mobile toggle */
.forge-navbar__toggle {
  display: none;
  background: none;
  border: none;
  color: rgba(240, 237, 232, 0.5);
  font-size: 16px;
  cursor: pointer;
  padding: 4px;
}

/* Mobile menu */
.forge-navbar__mobile {
  display: flex;
  flex-direction: column;
  padding: 8px 16px 16px;
  border-top: 1px solid rgba(255, 255, 255, 0.06);
  gap: 2px;
}

.forge-navbar__mobile-link {
  font-size: 14px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.5);
  text-decoration: none;
  padding: 10px 8px;
  letter-spacing: -0.01em;
  border-radius: 6px;
  transition: color 0.15s ease;
}

.forge-navbar__mobile-link:hover {
  color: #f0ede8;
}

.forge-navbar__cta--mobile {
  margin-top: 8px;
  width: 100%;
  justify-content: center;
}

/* Responsive */
@media (max-width: 640px) {
  .forge-navbar__links { display: none; }
  .forge-navbar__toggle { display: block; }
}

@media (prefers-reduced-motion: reduce) {
  .forge-navbar__link,
  .forge-navbar__cta { transition: none; }
}
`;
  return { tsx, css };
}
