import { hexToRgb } from "./utils.js";

export function generatePagination(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const total = (props.total as number) ?? 48;
  const perPage = (props.perPage as number) ?? 10;
  const showCount = (props.showCount as boolean) ?? true;
  const showArrows = (props.showArrows as boolean) ?? true;

  const tsx = `// ForgePagination — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update pagination

import { useState } from 'react'
import './ForgePagination.css'

interface ForgePaginationProps {
  total?: number
  perPage?: number
  color?: string
  showCount?: boolean
  showArrows?: boolean
  page?: number
  onPageChange?: (page: number) => void
}

export function ForgePagination({
  total = ${total},
  perPage = ${perPage},
  color = '${color}',
  showCount = ${showCount},
  showArrows = ${showArrows},
  page,
  onPageChange,
}: ForgePaginationProps) {
  const [internal, setInternal] = useState(1)
  const controlled = page !== undefined
  const current = controlled ? page : internal
  const totalPages = Math.ceil(total / perPage)

  function go(p: number) {
    if (p < 1 || p > totalPages) return
    if (!controlled) setInternal(p)
    onPageChange?.(p)
  }

  // Build page number list with ellipsis
  function getPages(): (number | '...')[] {
    if (totalPages <= 7) return Array.from({ length: totalPages }, (_, i) => i + 1)
    if (current <= 4) return [1, 2, 3, 4, 5, '...', totalPages]
    if (current >= totalPages - 3) return [1, '...', totalPages - 4, totalPages - 3, totalPages - 2, totalPages - 1, totalPages]
    return [1, '...', current - 1, current, current + 1, '...', totalPages]
  }

  const start = (current - 1) * perPage + 1
  const end = Math.min(current * perPage, total)

  return (
    <div
      className="forge-pagination"
      style={{ '--forge-pagination-color': color, '--forge-pagination-rgb': '${rgb}' } as React.CSSProperties}
    >
      {showCount && (
        <span className="forge-pagination__count">
          {start}–{end} of {total}
        </span>
      )}
      <div className="forge-pagination__pages">
        {showArrows && (
          <button
            className="forge-pagination__btn forge-pagination__arrow"
            onClick={() => go(current - 1)}
            disabled={current === 1}
            aria-label="Previous page"
          >
            ←
          </button>
        )}
        {getPages().map((p, i) =>
          p === '...' ? (
            <span key={\`ellipsis-\${i}\`} className="forge-pagination__ellipsis">…</span>
          ) : (
            <button
              key={p}
              className={\`forge-pagination__btn\${current === p ? ' forge-pagination__btn--active' : ''}\`}
              onClick={() => go(p as number)}
              aria-current={current === p ? 'page' : undefined}
            >
              {p}
            </button>
          )
        )}
        {showArrows && (
          <button
            className="forge-pagination__btn forge-pagination__arrow"
            onClick={() => go(current + 1)}
            disabled={current === totalPages}
            aria-label="Next page"
          >
            →
          </button>
        )}
      </div>
    </div>
  )
}
`;

  const css = `/* ForgePagination.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-pagination {
  display: flex;
  align-items: center;
  gap: 12px;
  font-family: Inter, sans-serif;
  flex-wrap: wrap;
}

.forge-pagination__count {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.3);
  letter-spacing: -0.01em;
  margin-right: 4px;
}

.forge-pagination__pages {
  display: flex;
  align-items: center;
  gap: 4px;
}

.forge-pagination__btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 30px;
  height: 30px;
  padding: 0 6px;
  border-radius: 6px;
  border: 1px solid transparent;
  background: transparent;
  color: rgba(240, 237, 232, 0.4);
  font-family: Inter, sans-serif;
  font-size: 12px;
  font-weight: 400;
  letter-spacing: -0.01em;
  cursor: pointer;
  transition: all 0.15s ease;
}

.forge-pagination__btn:hover:not(:disabled) {
  background: rgba(var(--forge-pagination-rgb), 0.08);
  color: var(--forge-pagination-color);
  border-color: rgba(var(--forge-pagination-rgb), 0.2);
}

.forge-pagination__btn--active {
  background: rgba(var(--forge-pagination-rgb), 0.15);
  color: var(--forge-pagination-color);
  border-color: rgba(var(--forge-pagination-rgb), 0.3);
}

.forge-pagination__btn:disabled {
  opacity: 0.25;
  cursor: not-allowed;
}

.forge-pagination__arrow {
  font-size: 14px;
}

.forge-pagination__ellipsis {
  font-size: 12px;
  color: rgba(240, 237, 232, 0.2);
  padding: 0 4px;
  user-select: none;
}

@media (prefers-reduced-motion: reduce) {
  .forge-pagination__btn { transition: none; }
}
`;
  return { tsx, css };
}
