import { hexToRgb } from "./utils.js";

export function generateProgress(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const value = (props.value as number) ?? 72;
  const height = (props.height as number) ?? 6;
  const radius = (props.radius as number) ?? 4;
  const showLabel = (props.showLabel as boolean) ?? true;
  const showValue = (props.showValue as boolean) ?? true;
  const striped = (props.striped as boolean) ?? false;
  const label = (props.label as string) ?? "Completion";

  const tsx = `// ForgeProgress — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update progress

import './ForgeProgress.css'

interface ForgeProgressProps {
  value?: number
  label?: string
  color?: string
  height?: number
  radius?: number
  showLabel?: boolean
  showValue?: boolean
  striped?: boolean
}

export function ForgeProgress({
  value = ${value},
  label = '${label}',
  color = '${color}',
  height = ${height},
  radius = ${radius},
  showLabel = ${showLabel},
  showValue = ${showValue},
  striped = ${striped},
}: ForgeProgressProps) {
  const clamped = Math.min(100, Math.max(0, value))
  return (
    <div className="forge-progress-wrap" style={{ '--forge-progress-color': color, '--forge-progress-rgb': '${rgb}' } as React.CSSProperties}>
      {(showLabel || showValue) && (
        <div className="forge-progress-header">
          {showLabel && <span className="forge-progress-label">{label}</span>}
          {showValue && <span className="forge-progress-value">{clamped}%</span>}
        </div>
      )}
      <div
        className="forge-progress-track"
        style={{ height, borderRadius: radius }}
        role="progressbar"
        aria-valuenow={clamped}
        aria-valuemin={0}
        aria-valuemax={100}
      >
        <div
          className={\`forge-progress-fill\${striped ? ' forge-progress-fill--striped' : ''}\`}
          style={{ width: \`\${clamped}%\`, borderRadius: radius }}
        />
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeProgress.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-progress-wrap {
  display: flex;
  flex-direction: column;
  gap: 6px;
  width: 100%;
  font-family: Inter, sans-serif;
}

.forge-progress-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.forge-progress-label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.38);
  letter-spacing: -0.01em;
}

.forge-progress-value {
  font-size: 12px;
  font-weight: 400;
  color: rgba(var(--forge-progress-rgb), 0.9);
  letter-spacing: -0.01em;
}

.forge-progress-track {
  width: 100%;
  background: rgba(var(--forge-progress-rgb), 0.10);
  overflow: hidden;
}

.forge-progress-fill {
  height: 100%;
  background: var(--forge-progress-color);
  box-shadow: 0 0 8px rgba(var(--forge-progress-rgb), 0.4);
  transition: width 0.4s ease;
}

/* Striped variant */
@keyframes forge-progress-stripes {
  from { background-position: 20px 0; }
  to   { background-position: 0 0; }
}
.forge-progress-fill--striped {
  background-image: linear-gradient(
    45deg,
    rgba(255,255,255,0.1) 25%,
    transparent 25%,
    transparent 50%,
    rgba(255,255,255,0.1) 50%,
    rgba(255,255,255,0.1) 75%,
    transparent 75%,
    transparent
  );
  background-size: 20px 20px;
  animation: forge-progress-stripes 0.8s linear infinite;
}

@media (prefers-reduced-motion: reduce) {
  .forge-progress-fill { transition: none; }
  .forge-progress-fill--striped { animation: none; }
}
`;
  return { tsx, css };
}
