import { hexToRgb } from "./utils.js";

export function generateRadio(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const size = (props.size as string) ?? "md";
  const layout = (props.layout as string) ?? "vertical";
  const options = (props.options as string[]) ?? ["Option 1", "Option 2"];

  const sizeMap: Record<string, string> = {
    sm: "14px",
    md: "16px",
    lg: "20px",
  };
  const fontMap: Record<string, string> = {
    sm: "12px",
    md: "13px",
    lg: "14px",
  };

  const tsx = `// ForgeRadio — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update radio

import { useState } from 'react'
import './ForgeRadio.css'

interface ForgeRadioProps {
  options?: string[]
  color?: string
  size?: 'sm' | 'md' | 'lg'
  layout?: 'vertical' | 'horizontal'
  selected?: number
  onChange?: (index: number, value: string) => void
}

export function ForgeRadio({
  options = ${JSON.stringify(options)},
  color = '${color}',
  size = '${size}',
  layout = '${layout}',
  selected,
  onChange,
}: ForgeRadioProps) {
  const [internal, setInternal] = useState(0)
  const controlled = selected !== undefined
  const active = controlled ? selected : internal

  function handleSelect(i: number) {
    if (!controlled) setInternal(i)
    onChange?.(i, options[i])
  }

  return (
    <div
      className={\`forge-radio-group forge-radio-group--\${layout}\`}
      style={{ '--forge-radio-color': color, '--forge-radio-rgb': '${rgb}' } as React.CSSProperties}
    >
      {options.map((opt, i) => (
        <label key={i} className={\`forge-radio-item forge-radio-item--\${size}\`} onClick={() => handleSelect(i)}>
          <div className={\`forge-radio forge-radio--\${size}\${active === i ? ' forge-radio--checked' : ''}\`}>
            {active === i && <div className="forge-radio__dot" />}
          </div>
          <span className="forge-radio-label">{opt}</span>
        </label>
      ))}
    </div>
  )
}
`;

  const css = `/* ForgeRadio.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-radio-group {
  display: flex;
  font-family: Inter, sans-serif;
}
.forge-radio-group--vertical   { flex-direction: column; gap: 8px; }
.forge-radio-group--horizontal { flex-direction: row; flex-wrap: wrap; gap: 16px; }

.forge-radio-item {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  user-select: none;
}

.forge-radio {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  border-radius: 50%;
  border: 1px solid rgba(255, 255, 255, 0.15);
  background: rgba(255, 255, 255, 0.04);
  transition: all 0.15s ease;
}

.forge-radio--sm { width: ${sizeMap.sm}; height: ${sizeMap.sm}; }
.forge-radio--md { width: ${sizeMap.md}; height: ${sizeMap.md}; }
.forge-radio--lg { width: ${sizeMap.lg}; height: ${sizeMap.lg}; }

.forge-radio--checked {
  border-color: rgba(var(--forge-radio-rgb), 0.6);
  background: rgba(var(--forge-radio-rgb), 0.1);
  box-shadow: 0 0 8px rgba(var(--forge-radio-rgb), 0.2);
}

.forge-radio__dot {
  width: 40%;
  height: 40%;
  border-radius: 50%;
  background: var(--forge-radio-color);
}

.forge-radio-label {
  font-size: ${fontMap[size] ?? fontMap.md};
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-radio-item:hover .forge-radio {
  border-color: rgba(var(--forge-radio-rgb), 0.35);
}
`;
  return { tsx, css };
}
