import { hexToRgb } from "./utils.js";

export function generateSelect(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const size = (props.size as string) ?? "md";
  const radius = (props.radius as number) ?? 8;
  const showLabel = (props.showLabel as boolean) ?? true;
  const label = (props.label as string) ?? "Select";
  const placeholder = (props.placeholder as string) ?? "Choose…";
  const options = (props.options as string[]) ?? [
    "Option 1",
    "Option 2",
    "Option 3",
  ];

  const paddingMap: Record<string, string> = {
    sm: "6px 10px",
    md: "9px 14px",
    lg: "12px 16px",
  };
  const fontSizeMap: Record<string, string> = {
    sm: "12px",
    md: "13px",
    lg: "14px",
  };

  const tsx = `// ForgeSelect — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update select

import { useState } from 'react'
import './ForgeSelect.css'

interface ForgeSelectProps {
  label?: string
  placeholder?: string
  options?: string[]
  color?: string
  size?: 'sm' | 'md' | 'lg'
  radius?: number
  showLabel?: boolean
  value?: string
  onChange?: (value: string) => void
}

export function ForgeSelect({
  label = '${label}',
  placeholder = '${placeholder}',
  options = ${JSON.stringify(options)},
  color = '${color}',
  size = '${size}',
  radius = ${radius},
  showLabel = ${showLabel},
  value,
  onChange,
}: ForgeSelectProps) {
  const [internal, setInternal] = useState('')
  const controlled = value !== undefined
  const current = controlled ? value : internal

  return (
    <div
      className="forge-select-wrap"
      style={{ '--forge-select-color': color, '--forge-select-rgb': '${rgb}' } as React.CSSProperties}
    >
      {showLabel && label && (
        <label className="forge-select-label">{label}</label>
      )}
      <div className="forge-select-inner">
        <select
          className={\`forge-select forge-select--\${size}\`}
          value={current}
          style={{ borderRadius: radius }}
          onChange={e => {
            if (!controlled) setInternal(e.target.value)
            onChange?.(e.target.value)
          }}
        >
          <option value="" disabled>{placeholder}</option>
          {options.map(opt => (
            <option key={opt} value={opt}>{opt}</option>
          ))}
        </select>
        <span className="forge-select-arrow">▾</span>
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeSelect.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-select-wrap {
  display: flex;
  flex-direction: column;
  gap: 5px;
  font-family: Inter, sans-serif;
  width: 100%;
}

.forge-select-label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-select-inner {
  position: relative;
  display: flex;
  align-items: center;
}

.forge-select {
  width: 100%;
  appearance: none;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  color: #f0ede8;
  font-family: Inter, sans-serif;
  font-weight: 400;
  letter-spacing: -0.01em;
  outline: none;
  cursor: pointer;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
  padding-right: 32px;
  box-sizing: border-box;
}

.forge-select--sm { padding: ${paddingMap.sm}; font-size: ${fontSizeMap.sm}; }
.forge-select--md { padding: ${paddingMap.md}; font-size: ${fontSizeMap.md}; }
.forge-select--lg { padding: ${paddingMap.lg}; font-size: ${fontSizeMap.lg}; }

.forge-select:focus {
  border-color: rgba(var(--forge-select-rgb), 0.5);
  box-shadow: 0 0 0 3px rgba(var(--forge-select-rgb), 0.12);
}

.forge-select option {
  background: #0f0f12;
  color: #f0ede8;
}

.forge-select-arrow {
  position: absolute;
  right: 10px;
  font-size: 11px;
  color: rgba(240, 237, 232, 0.3);
  pointer-events: none;
}
`;
  return { tsx, css };
}
