import { hexToRgb } from "./utils.js";

export function generateSideNav(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const brand = (props.brand as string) ?? "FORGE";
  const showIcons = (props.showIcons as boolean) ?? true;
  const items = (props.items as string[]) ?? [
    "◎,Dashboard",
    "⊞,Components",
    "⚙,Settings",
  ];
  const initialActive = (props.active as number) ?? 0;

  const tsx = `// ForgeSideNav — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update sidenav
// Note: links use <a> tags — swap for Next.js <Link> if needed.

import { useState } from 'react'
import './ForgeSideNav.css'

interface ForgeSideNavProps {
  brand?: string
  items?: string[]
  color?: string
  showIcons?: boolean
  active?: number
  onSelect?: (index: number, label: string) => void
}

export function ForgeSideNav({
  brand = '${brand}',
  items = ${JSON.stringify(items)},
  color = '${color}',
  showIcons = ${showIcons},
  active,
  onSelect,
}: ForgeSideNavProps) {
  const [internal, setInternal] = useState(${initialActive})
  const controlled = active !== undefined
  const current = controlled ? active : internal

  // Items format: "icon,Label" or just "Label"
  const parsed = items.map(item => {
    const parts = item.split(',')
    return parts.length >= 2
      ? { icon: parts[0], label: parts.slice(1).join(',') }
      : { icon: '', label: item }
  })

  function handleSelect(i: number) {
    if (!controlled) setInternal(i)
    onSelect?.(i, parsed[i].label)
  }

  return (
    <aside
      className="forge-sidenav"
      style={{ '--forge-sidenav-color': color, '--forge-sidenav-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className="forge-sidenav__brand">{brand}</div>
      <nav className="forge-sidenav__nav">
        {parsed.map((item, i) => (
          <button
            key={i}
            className={\`forge-sidenav__item\${current === i ? ' forge-sidenav__item--active' : ''}\`}
            onClick={() => handleSelect(i)}
          >
            {showIcons && item.icon && (
              <span className="forge-sidenav__icon">{item.icon}</span>
            )}
            <span className="forge-sidenav__label">{item.label}</span>
          </button>
        ))}
      </nav>
    </aside>
  )
}
`;

  const css = `/* ForgeSideNav.css — generated by forge-ui CLI */
.forge-sidenav {
  display: flex;
  flex-direction: column;
  width: 220px;
  height: 100%;
  background: #09090b;
  border-right: 1px solid rgba(255,255,255,0.06);
  padding: 16px 8px;
  font-family: Inter, sans-serif;
  gap: 4px;
}

.forge-sidenav__brand {
  font-size: 13px;
  font-weight: 500;
  color: #f0ede8;
  letter-spacing: -0.02em;
  padding: 8px 10px 16px;
  border-bottom: 1px solid rgba(255,255,255,0.06);
  margin-bottom: 8px;
}

.forge-sidenav__nav {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.forge-sidenav__item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px;
  border-radius: 6px;
  background: none;
  border: none;
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  color: rgba(240,237,232,0.38);
  letter-spacing: -0.01em;
  cursor: pointer;
  text-align: left;
  transition: all 0.15s ease;
  width: 100%;
}

.forge-sidenav__item:hover {
  background: rgba(255,255,255,0.04);
  color: rgba(240,237,232,0.7);
}

.forge-sidenav__item--active {
  background: rgba(var(--forge-sidenav-rgb), 0.1);
  color: var(--forge-sidenav-color);
}

.forge-sidenav__icon {
  font-size: 13px;
  flex-shrink: 0;
  opacity: 0.7;
}

.forge-sidenav__item--active .forge-sidenav__icon { opacity: 1; }

@media (prefers-reduced-motion: reduce) {
  .forge-sidenav__item { transition: none; }
}
`;
  return { tsx, css };
}
