export function generateSkeleton(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const radius = (props.radius as number) ?? 8;
  const animated = (props.animated as boolean) ?? true;
  const variant = (props.variant as string) ?? "card";
  const lines = (props.lines as number) ?? 3;

  const tsx = `// ForgeSkeleton — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update skeleton

import './ForgeSkeleton.css'

interface ForgeSkeletonProps {
  variant?: 'card' | 'text' | 'profile' | 'table'
  lines?: number
  radius?: number
  animated?: boolean
}

function Bone({ w = '100%', h = '16px', r = 6 }: { w?: string; h?: string; r?: number }) {
  return <div className="forge-sk-bone" style={{ width: w, height: h, borderRadius: r }} />
}

export function ForgeSkeleton({
  variant = '${variant}',
  lines = ${lines},
  radius = ${radius},
  animated = ${animated},
}: ForgeSkeletonProps) {
  return (
    <div className={\`forge-skeleton\${animated ? ' forge-skeleton--animated' : ''}\`}>
      {variant === 'text' && (
        <div className="forge-sk-text">
          {Array.from({ length: lines }).map((_, i) => (
            <Bone key={i} w={i === lines - 1 ? '65%' : '100%'} r={radius} />
          ))}
        </div>
      )}

      {variant === 'profile' && (
        <div className="forge-sk-profile">
          <Bone w="48px" h="48px" r={999} />
          <div className="forge-sk-profile__lines">
            <Bone w="140px" h="14px" r={radius} />
            <Bone w="100px" h="12px" r={radius} />
          </div>
        </div>
      )}

      {variant === 'card' && (
        <div className="forge-sk-card" style={{ borderRadius: radius }}>
          <Bone w="40%" h="11px" r={4} />
          <Bone w="85%" h="16px" r={radius} />
          <Bone w="100%" h="13px" r={radius} />
          <Bone w="70%" h="13px" r={radius} />
        </div>
      )}

      {variant === 'table' && (
        <div className="forge-sk-table">
          <div className="forge-sk-table__row forge-sk-table__header">
            {[40,25,20,15].map((w, i) => <Bone key={i} w={\`\${w}%\`} h="12px" r={4} />)}
          </div>
          {Array.from({ length: lines }).map((_, i) => (
            <div key={i} className="forge-sk-table__row">
              {[40,25,20,15].map((w, j) => <Bone key={j} w={\`\${w}%\`} h="13px" r={4} />)}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeSkeleton.css — generated by forge-ui CLI */
@keyframes forge-shimmer {
  from { background-position: -400px 0; }
  to   { background-position: 400px 0; }
}

.forge-skeleton { font-family: Inter, sans-serif; }

.forge-sk-bone {
  background: rgba(255,255,255,0.06);
}

.forge-skeleton--animated .forge-sk-bone {
  background: linear-gradient(
    90deg,
    rgba(255,255,255,0.04) 25%,
    rgba(255,255,255,0.09) 50%,
    rgba(255,255,255,0.04) 75%
  );
  background-size: 400px 100%;
  animation: forge-shimmer 1.4s ease-in-out infinite;
}

.forge-sk-text { display: flex; flex-direction: column; gap: 8px; }

.forge-sk-profile { display: flex; align-items: center; gap: 12px; }
.forge-sk-profile__lines { display: flex; flex-direction: column; gap: 6px; }

.forge-sk-card {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 20px;
  background: #0f0f12;
  border: 1px solid rgba(255,255,255,0.06);
}

.forge-sk-table { display: flex; flex-direction: column; }
.forge-sk-table__row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 0;
  border-bottom: 1px solid rgba(255,255,255,0.04);
}
.forge-sk-table__header { padding-bottom: 12px; }

@media (prefers-reduced-motion: reduce) {
  .forge-sk-bone { animation: none; }
}
`;
  return { tsx, css };
}
