import { hexToRgb } from "./utils.js";

export function generateSlider(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const min = (props.min as number) ?? 0;
  const max = (props.max as number) ?? 100;
  const step = (props.step as number) ?? 1;
  const defaultValue = (props.value as number) ?? 50;
  const showValue = (props.showValue as boolean) ?? true;
  const label = (props.label as string) ?? "Value";
  const unit = (props.unit as string) ?? "";

  const tsx = `// ForgeSlider — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update slider

import { useState } from 'react'
import './ForgeSlider.css'

interface ForgeSliderProps {
  label?: string
  min?: number
  max?: number
  step?: number
  value?: number
  color?: string
  showValue?: boolean
  unit?: string
  onChange?: (value: number) => void
}

export function ForgeSlider({
  label = '${label}',
  min = ${min},
  max = ${max},
  step = ${step},
  value,
  color = '${color}',
  showValue = ${showValue},
  unit = '${unit}',
  onChange,
}: ForgeSliderProps) {
  const [internal, setInternal] = useState(${defaultValue})
  const controlled = value !== undefined
  const current = controlled ? value : internal
  const pct = ((current - min) / (max - min)) * 100

  return (
    <div
      className="forge-slider-wrap"
      style={{ '--forge-slider-color': color, '--forge-slider-rgb': '${rgb}', '--forge-slider-pct': \`\${pct}%\` } as React.CSSProperties}
    >
      <div className="forge-slider-header">
        <span className="forge-slider-label">{label}</span>
        {showValue && (
          <span className="forge-slider-value">{unit}{current}</span>
        )}
      </div>
      <input
        type="range"
        className="forge-slider"
        min={min}
        max={max}
        step={step}
        value={current}
        onChange={e => {
          const v = Number(e.target.value)
          if (!controlled) setInternal(v)
          onChange?.(v)
        }}
      />
    </div>
  )
}
`;

  const css = `/* ForgeSlider.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-slider-wrap {
  display: flex;
  flex-direction: column;
  gap: 8px;
  font-family: Inter, sans-serif;
  width: 100%;
}

.forge-slider-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.forge-slider-label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.38);
  letter-spacing: -0.01em;
}

.forge-slider-value {
  font-size: 12px;
  font-weight: 400;
  color: rgba(var(--forge-slider-rgb), 0.9);
  letter-spacing: -0.01em;
}

.forge-slider {
  -webkit-appearance: none;
  appearance: none;
  width: 100%;
  height: 4px;
  border-radius: 2px;
  outline: none;
  cursor: pointer;
  /* Fill track up to thumb using a gradient */
  background: linear-gradient(
    to right,
    var(--forge-slider-color) 0%,
    var(--forge-slider-color) var(--forge-slider-pct),
    rgba(255, 255, 255, 0.08) var(--forge-slider-pct),
    rgba(255, 255, 255, 0.08) 100%
  );
}

.forge-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: var(--forge-slider-color);
  box-shadow: 0 0 8px rgba(var(--forge-slider-rgb), 0.4);
  border: 2px solid #09090b;
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}

.forge-slider::-moz-range-thumb {
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: var(--forge-slider-color);
  box-shadow: 0 0 8px rgba(var(--forge-slider-rgb), 0.4);
  border: 2px solid #09090b;
  transition: transform 0.15s ease;
}

.forge-slider:hover::-webkit-slider-thumb {
  transform: scale(1.2);
  box-shadow: 0 0 14px rgba(var(--forge-slider-rgb), 0.5);
}

.forge-slider:hover::-moz-range-thumb {
  transform: scale(1.2);
}

@media (prefers-reduced-motion: reduce) {
  .forge-slider::-webkit-slider-thumb,
  .forge-slider::-moz-range-thumb { transition: none; }
}
`;
  return { tsx, css };
}
