import { hexToRgb } from "./utils.js";

export function generateSparkline(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const fill = (props.fill as boolean) ?? true;
  const variant = (props.variant as string) ?? "line";
  const showDot = (props.showDot as boolean) ?? true;
  const height = (props.height as number) ?? 60;
  const animated = (props.animated as boolean) ?? true;

  const tsx = `// ForgeSparkline — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update sparkline
// Requires Chart.js — add to your layout:
// <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js" />

import { useEffect, useRef } from 'react'
import './ForgeSparkline.css'

interface ForgeSparklineProps {
  data?: number[]
  color?: string
  fill?: boolean
  variant?: 'line' | 'bar'
  showDot?: boolean
  height?: number
  width?: number
  animated?: boolean
}

const DEFAULT_DATA = [20, 35, 28, 50, 42, 65, 55, 72, 60, 88]

export function ForgeSparkline({
  data = DEFAULT_DATA,
  color = '${color}',
  fill = ${fill},
  variant = '${variant}',
  showDot = ${showDot},
  height = ${height},
  width = 160,
  animated = ${animated},
}: ForgeSparklineProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const chartRef = useRef<unknown>(null)

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const Chart = (window as any).Chart
    if (!Chart || !canvasRef.current) return
    if (chartRef.current) (chartRef.current as any).destroy()

    const isBar = variant === 'bar'

    chartRef.current = new Chart(canvasRef.current, {
      type: isBar ? 'bar' : 'line',
      data: {
        labels: data.map(() => ''),
        datasets: [{
          data,
          borderColor: color,
          backgroundColor: fill ? \`\${color}33\` : 'transparent',
          borderWidth: isBar ? 0 : 1.5,
          fill: !isBar && fill,
          tension: 0.4,
          pointRadius: showDot ? data.map((_, i) => (i === data.length - 1 ? 3 : 0)) : 0,
          pointBackgroundColor: color,
          borderRadius: isBar ? 2 : 0,
        }],
      },
      options: {
        responsive: false,
        animation: animated,
        plugins: { legend: { display: false }, tooltip: { enabled: false } },
        scales: {
          x: { display: false },
          y: { display: false },
        },
      },
    })

    return () => { if (chartRef.current) (chartRef.current as any).destroy() }
  }, [data, color, fill, variant, showDot, animated])

  return (
    <div
      className="forge-sparkline"
      style={{ '--forge-sparkline-color': color, '--forge-sparkline-rgb': '${rgb}' } as React.CSSProperties}
    >
      <canvas ref={canvasRef} width={width} height={height} />
    </div>
  )
}
`;

  const css = `/* ForgeSparkline.css — generated by forge-ui CLI */
.forge-sparkline {
  display: inline-flex;
  align-items: center;
}
`;
  return { tsx, css };
}
