import { hexToRgb } from "./utils.js";

export function generateSpinner(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "ring";
  const size = (props.size as string) ?? "md";
  const speed = (props.speed as string) ?? "normal";
  const showLabel = (props.showLabel as boolean) ?? false;
  const label = (props.label as string) ?? "Loading…";

  const sizeMap: Record<string, string> = {
    sm: "16px",
    md: "24px",
    lg: "36px",
    xl: "48px",
  };
  const speedMap: Record<string, string> = {
    slow: "1.4s",
    normal: "0.8s",
    fast: "0.4s",
  };

  const tsx = `// ForgeSpinner — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update spinner

import './ForgeSpinner.css'

interface ForgeSpinnerProps {
  color?: string
  variant?: 'ring' | 'dots' | 'bars' | 'orbit' | 'pulse'
  size?: 'sm' | 'md' | 'lg' | 'xl'
  speed?: 'slow' | 'normal' | 'fast'
  showLabel?: boolean
  label?: string
}

export function ForgeSpinner({
  color = '${color}',
  variant = '${variant}',
  size = '${size}',
  speed = '${speed}',
  showLabel = ${showLabel},
  label = '${label}',
}: ForgeSpinnerProps) {
  return (
    <div
      className="forge-spinner-wrap"
      style={{ '--forge-spinner-color': color, '--forge-spinner-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className={\`forge-spinner forge-spinner--\${variant} forge-spinner--\${size} forge-spinner--\${speed}\`}>
        {variant === 'dots' && (
          <>
            <div className="forge-spinner__dot" />
            <div className="forge-spinner__dot" />
            <div className="forge-spinner__dot" />
          </>
        )}
        {variant === 'bars' && (
          <>
            <div className="forge-spinner__bar" />
            <div className="forge-spinner__bar" />
            <div className="forge-spinner__bar" />
            <div className="forge-spinner__bar" />
          </>
        )}
      </div>
      {showLabel && <span className="forge-spinner__label">{label}</span>}
    </div>
  )
}
`;

  const css = `/* ForgeSpinner.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-spinner-wrap {
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
}

.forge-spinner {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

/* Sizes */
.forge-spinner--sm { width: ${sizeMap.sm}; height: ${sizeMap.sm}; }
.forge-spinner--md { width: ${sizeMap.md}; height: ${sizeMap.md}; }
.forge-spinner--lg { width: ${sizeMap.lg}; height: ${sizeMap.lg}; }
.forge-spinner--xl { width: ${sizeMap.xl}; height: ${sizeMap.xl}; }

/* Ring variant */
@keyframes forge-spin { to { transform: rotate(360deg); } }
.forge-spinner--ring {
  border-radius: 50%;
  border: 2px solid rgba(var(--forge-spinner-rgb), 0.15);
  border-top-color: var(--forge-spinner-color);
}
.forge-spinner--ring.forge-spinner--slow   { animation: forge-spin ${speedMap.slow} linear infinite; }
.forge-spinner--ring.forge-spinner--normal { animation: forge-spin ${speedMap.normal} linear infinite; }
.forge-spinner--ring.forge-spinner--fast   { animation: forge-spin ${speedMap.fast} linear infinite; }

/* Pulse variant */
@keyframes forge-pulse-spin {
  0%   { transform: scale(1);    opacity: 1; }
  50%  { transform: scale(0.6);  opacity: 0.4; }
  100% { transform: scale(1);    opacity: 1; }
}
.forge-spinner--pulse {
  border-radius: 50%;
  background: var(--forge-spinner-color);
}
.forge-spinner--pulse.forge-spinner--slow   { animation: forge-pulse-spin ${speedMap.slow} ease-in-out infinite; }
.forge-spinner--pulse.forge-spinner--normal { animation: forge-pulse-spin ${speedMap.normal} ease-in-out infinite; }
.forge-spinner--pulse.forge-spinner--fast   { animation: forge-pulse-spin ${speedMap.fast} ease-in-out infinite; }

/* Dots variant */
@keyframes forge-dot-bounce {
  0%, 80%, 100% { transform: scale(0.6); opacity: 0.4; }
  40%           { transform: scale(1);   opacity: 1; }
}
.forge-spinner--dots {
  gap: 4px;
}
.forge-spinner__dot {
  width: 30%;
  height: 30%;
  border-radius: 50%;
  background: var(--forge-spinner-color);
}
.forge-spinner--slow   .forge-spinner__dot:nth-child(1) { animation: forge-dot-bounce ${speedMap.slow} ease-in-out infinite 0s; }
.forge-spinner--slow   .forge-spinner__dot:nth-child(2) { animation: forge-dot-bounce ${speedMap.slow} ease-in-out infinite 0.16s; }
.forge-spinner--slow   .forge-spinner__dot:nth-child(3) { animation: forge-dot-bounce ${speedMap.slow} ease-in-out infinite 0.32s; }
.forge-spinner--normal .forge-spinner__dot:nth-child(1) { animation: forge-dot-bounce ${speedMap.normal} ease-in-out infinite 0s; }
.forge-spinner--normal .forge-spinner__dot:nth-child(2) { animation: forge-dot-bounce ${speedMap.normal} ease-in-out infinite 0.16s; }
.forge-spinner--normal .forge-spinner__dot:nth-child(3) { animation: forge-dot-bounce ${speedMap.normal} ease-in-out infinite 0.32s; }
.forge-spinner--fast   .forge-spinner__dot:nth-child(1) { animation: forge-dot-bounce ${speedMap.fast} ease-in-out infinite 0s; }
.forge-spinner--fast   .forge-spinner__dot:nth-child(2) { animation: forge-dot-bounce ${speedMap.fast} ease-in-out infinite 0.16s; }
.forge-spinner--fast   .forge-spinner__dot:nth-child(3) { animation: forge-dot-bounce ${speedMap.fast} ease-in-out infinite 0.32s; }

/* Bars variant */
@keyframes forge-bar-stretch {
  0%, 40%, 100% { transform: scaleY(0.4); }
  20%           { transform: scaleY(1); }
}
.forge-spinner--bars {
  gap: 3px;
  align-items: center;
}
.forge-spinner__bar {
  width: 15%;
  height: 60%;
  background: var(--forge-spinner-color);
  border-radius: 2px;
}
.forge-spinner--slow   .forge-spinner__bar:nth-child(1) { animation: forge-bar-stretch ${speedMap.slow} ease-in-out infinite 0s; }
.forge-spinner--slow   .forge-spinner__bar:nth-child(2) { animation: forge-bar-stretch ${speedMap.slow} ease-in-out infinite 0.1s; }
.forge-spinner--slow   .forge-spinner__bar:nth-child(3) { animation: forge-bar-stretch ${speedMap.slow} ease-in-out infinite 0.2s; }
.forge-spinner--slow   .forge-spinner__bar:nth-child(4) { animation: forge-bar-stretch ${speedMap.slow} ease-in-out infinite 0.3s; }
.forge-spinner--normal .forge-spinner__bar:nth-child(1) { animation: forge-bar-stretch ${speedMap.normal} ease-in-out infinite 0s; }
.forge-spinner--normal .forge-spinner__bar:nth-child(2) { animation: forge-bar-stretch ${speedMap.normal} ease-in-out infinite 0.1s; }
.forge-spinner--normal .forge-spinner__bar:nth-child(3) { animation: forge-bar-stretch ${speedMap.normal} ease-in-out infinite 0.2s; }
.forge-spinner--normal .forge-spinner__bar:nth-child(4) { animation: forge-bar-stretch ${speedMap.normal} ease-in-out infinite 0.3s; }
.forge-spinner--fast   .forge-spinner__bar:nth-child(1) { animation: forge-bar-stretch ${speedMap.fast} ease-in-out infinite 0s; }
.forge-spinner--fast   .forge-spinner__bar:nth-child(2) { animation: forge-bar-stretch ${speedMap.fast} ease-in-out infinite 0.1s; }
.forge-spinner--fast   .forge-spinner__bar:nth-child(3) { animation: forge-bar-stretch ${speedMap.fast} ease-in-out infinite 0.2s; }
.forge-spinner--fast   .forge-spinner__bar:nth-child(4) { animation: forge-bar-stretch ${speedMap.fast} ease-in-out infinite 0.3s; }

/* Orbit variant */
@keyframes forge-orbit {
  to { transform: rotate(360deg); }
}
.forge-spinner--orbit {
  border-radius: 50%;
  border: 2px solid rgba(var(--forge-spinner-rgb), 0.1);
  position: relative;
}
.forge-spinner--orbit::before {
  content: '';
  position: absolute;
  top: -2px; left: -2px; right: -2px; bottom: -2px;
  border-radius: 50%;
  border: 2px solid transparent;
  border-top-color: var(--forge-spinner-color);
  border-right-color: rgba(var(--forge-spinner-rgb), 0.4);
}
.forge-spinner--orbit.forge-spinner--slow::before   { animation: forge-orbit ${speedMap.slow} linear infinite; }
.forge-spinner--orbit.forge-spinner--normal::before { animation: forge-orbit ${speedMap.normal} linear infinite; }
.forge-spinner--orbit.forge-spinner--fast::before   { animation: forge-orbit ${speedMap.fast} linear infinite; }

/* Label */
.forge-spinner__label {
  font-family: Inter, sans-serif;
  font-size: 12px;
  color: rgba(240, 237, 232, 0.38);
  letter-spacing: -0.01em;
}

/* Respect reduced motion */
@media (prefers-reduced-motion: reduce) {
  .forge-spinner,
  .forge-spinner::before,
  .forge-spinner__dot,
  .forge-spinner__bar { animation: none !important; }
}
`;
  return { tsx, css };
}
