import { hexToRgb } from "./utils.js";

export function generateStatCard(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const showIcon = (props.showIcon as boolean) ?? true;
  const showDelta = (props.showDelta as boolean) ?? true;
  const showBar = (props.showBar as boolean) ?? true;
  const barValue = (props.barValue as number) ?? 72;
  const title = (props.title as string) ?? "Metric";
  const value = (props.value as string) ?? "0";
  const delta = (props.delta as string) ?? "+0%";
  const deltaDir = (props.deltaDir as string) ?? "up";
  const icon = (props.icon as string) ?? "↑";

  const tsx = `// ForgeStatCard — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update statcard

import './ForgeStatCard.css'

interface ForgeStatCardProps {
  title?: string
  value?: string | number
  delta?: string
  deltaDir?: 'up' | 'down'
  icon?: string
  color?: string
  showIcon?: boolean
  showDelta?: boolean
  showBar?: boolean
  barValue?: number
}

export function ForgeStatCard({
  title = '${title}',
  value = '${value}',
  delta = '${delta}',
  deltaDir = '${deltaDir}',
  icon = '${icon}',
  color = '${color}',
  showIcon = ${showIcon},
  showDelta = ${showDelta},
  showBar = ${showBar},
  barValue = ${barValue},
}: ForgeStatCardProps) {
  const clamped = Math.min(100, Math.max(0, barValue))
  return (
    <div
      className="forge-statcard"
      style={{ '--forge-statcard-color': color, '--forge-statcard-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className="forge-statcard__header">
        <span className="forge-statcard__title">{title}</span>
        {showIcon && <span className="forge-statcard__icon">{icon}</span>}
      </div>
      <div className="forge-statcard__value">{value}</div>
      {showDelta && (
        <div className={\`forge-statcard__delta forge-statcard__delta--\${deltaDir}\`}>
          {deltaDir === 'up' ? '↑' : '↓'} {delta}
        </div>
      )}
      {showBar && (
        <div className="forge-statcard__track">
          <div className="forge-statcard__fill" style={{ width: \`\${clamped}%\` }} />
        </div>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeStatCard.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-statcard {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 20px;
  background: #0f0f12;
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 12px;
  font-family: Inter, sans-serif;
  min-width: 180px;
}

.forge-statcard__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.forge-statcard__title {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.38);
  letter-spacing: -0.01em;
}

.forge-statcard__icon {
  font-size: 14px;
  color: rgba(var(--forge-statcard-rgb), 0.6);
}

.forge-statcard__value {
  font-size: 24px;
  font-weight: 300;
  color: #f0ede8;
  letter-spacing: -0.04em;
  line-height: 1;
}

.forge-statcard__delta {
  font-size: 11px;
  font-weight: 400;
  letter-spacing: -0.01em;
}
.forge-statcard__delta--up   { color: #1D9E75; }
.forge-statcard__delta--down { color: #e24b4a; }

.forge-statcard__track {
  height: 3px;
  background: rgba(var(--forge-statcard-rgb), 0.1);
  border-radius: 2px;
  overflow: hidden;
  margin-top: 4px;
}

.forge-statcard__fill {
  height: 100%;
  background: var(--forge-statcard-color);
  border-radius: 2px;
  box-shadow: 0 0 6px rgba(var(--forge-statcard-rgb), 0.4);
  transition: width 0.4s ease;
}
`;
  return { tsx, css };
}
