import { hexToRgb } from "./utils.js";

export function generateStepper(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "horizontal";
  const showDesc = (props.showDesc as boolean) ?? true;
  const steps = (props.steps as string[]) ?? ["Step 1", "Step 2", "Step 3"];
  const descs = (props.descs as string[]) ?? [];
  const initialCurrent = (props.current as number) ?? 0;

  const tsx = `// ForgeStepper — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update stepper

import { useState } from 'react'
import './ForgeStepper.css'

interface ForgeStepperProps {
  steps?: string[]
  descs?: string[]
  color?: string
  variant?: 'horizontal' | 'vertical'
  showDesc?: boolean
  current?: number
  onChange?: (step: number) => void
}

export function ForgeStepper({
  steps = ${JSON.stringify(steps)},
  descs = ${JSON.stringify(descs)},
  color = '${color}',
  variant = '${variant}',
  showDesc = ${showDesc},
  current,
  onChange,
}: ForgeStepperProps) {
  const [internal, setInternal] = useState(${initialCurrent})
  const controlled = current !== undefined
  const active = controlled ? current : internal

  function handleClick(i: number) {
    if (!controlled) setInternal(i)
    onChange?.(i)
  }

  return (
    <div
      className={\`forge-stepper forge-stepper--\${variant}\`}
      style={{ '--forge-stepper-color': color, '--forge-stepper-rgb': '${rgb}' } as React.CSSProperties}
    >
      {steps.map((step, i) => {
        const done = i < active
        const curr = i === active
        return (
          <div key={i} className={\`forge-step\${done ? ' forge-step--done' : ''}\${curr ? ' forge-step--current' : ''}\`}>
            <div className="forge-step__indicator" onClick={() => handleClick(i)}>
              <div className="forge-step__dot">
                {done ? '✓' : i + 1}
              </div>
              {i < steps.length - 1 && <div className="forge-step__line" />}
            </div>
            <div className="forge-step__content">
              <div className="forge-step__label">{step}</div>
              {showDesc && descs[i] && (
                <div className="forge-step__desc">{descs[i]}</div>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}
`;

  const css = `/* ForgeStepper.css — generated by forge-ui CLI */
.forge-stepper {
  display: flex;
  font-family: Inter, sans-serif;
}

.forge-stepper--horizontal { flex-direction: row; align-items: flex-start; gap: 0; }
.forge-stepper--vertical   { flex-direction: column; gap: 0; }

.forge-step {
  display: flex;
  flex: 1;
}

.forge-stepper--horizontal .forge-step { flex-direction: column; align-items: center; }
.forge-stepper--vertical   .forge-step { flex-direction: row; align-items: flex-start; gap: 12px; }

.forge-step__indicator {
  display: flex;
  align-items: center;
  cursor: pointer;
}

.forge-stepper--horizontal .forge-step__indicator { flex-direction: row; width: 100%; }
.forge-stepper--vertical   .forge-step__indicator { flex-direction: column; align-items: center; }

.forge-step__dot {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 11px;
  font-weight: 400;
  flex-shrink: 0;
  border: 1px solid rgba(255,255,255,0.1);
  background: rgba(255,255,255,0.04);
  color: rgba(240,237,232,0.3);
  transition: all 0.2s ease;
}

.forge-step--done .forge-step__dot {
  background: rgba(var(--forge-stepper-rgb), 0.15);
  border-color: rgba(var(--forge-stepper-rgb), 0.4);
  color: var(--forge-stepper-color);
}

.forge-step--current .forge-step__dot {
  background: rgba(var(--forge-stepper-rgb), 0.2);
  border-color: rgba(var(--forge-stepper-rgb), 0.6);
  color: var(--forge-stepper-color);
  box-shadow: 0 0 12px rgba(var(--forge-stepper-rgb), 0.25);
}

.forge-step__line {
  flex: 1;
  background: rgba(255,255,255,0.06);
}

.forge-stepper--horizontal .forge-step__line { height: 1px; }
.forge-stepper--vertical   .forge-step__line { width: 1px; height: 32px; margin: 4px 0; }

.forge-step--done .forge-step__line {
  background: rgba(var(--forge-stepper-rgb), 0.25);
}

.forge-step__content {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.forge-stepper--horizontal .forge-step__content {
  align-items: center;
  padding-top: 8px;
}

.forge-step__label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240,237,232,0.3);
  letter-spacing: -0.01em;
  white-space: nowrap;
}

.forge-step--current .forge-step__label { color: #f0ede8; }
.forge-step--done    .forge-step__label { color: rgba(240,237,232,0.5); }

.forge-step__desc {
  font-size: 11px;
  font-weight: 300;
  color: rgba(240,237,232,0.25);
  letter-spacing: -0.01em;
  line-height: 1.4;
}
`;
  return { tsx, css };
}
