import { hexToRgb } from "./utils.js";

export function generateTable(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const showStripes = (props.showStripes as boolean) ?? true;
  const showHover = (props.showHover as boolean) ?? true;
  const compact = (props.compact as boolean) ?? false;
  const caption = (props.caption as string) ?? "";
  const columns = (props.columns as string[]) ?? ["Name", "Status", "Date"];

  const tsx = `// ForgeTable — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update table

import './ForgeTable.css'

interface ForgeTableProps {
  columns?: string[]
  rows?: (string | number)[][]
  caption?: string
  color?: string
  showStripes?: boolean
  showHover?: boolean
  compact?: boolean
}

// Default demo rows — replace with your data
const DEFAULT_ROWS: (string | number)[][] = [
  ${columns
    .map((_, i) => `[${columns.map((c) => `'${c} ${i + 1}'`).join(", ")}]`)
    .slice(0, 3)
    .join(",\n  ")},
]

export function ForgeTable({
  columns = ${JSON.stringify(columns)},
  rows = DEFAULT_ROWS,
  caption = '${caption}',
  color = '${color}',
  showStripes = ${showStripes},
  showHover = ${showHover},
  compact = ${compact},
}: ForgeTableProps) {
  return (
    <div
      className="forge-table-wrap"
      style={{ '--forge-table-color': color, '--forge-table-rgb': '${rgb}' } as React.CSSProperties}
    >
      <table className={\`forge-table\${showStripes ? ' forge-table--striped' : ''}\${showHover ? ' forge-table--hover' : ''}\${compact ? ' forge-table--compact' : ''}\`}>
        {caption && <caption className="forge-table__caption">{caption}</caption>}
        <thead>
          <tr>
            {columns.map(col => (
              <th key={col} className="forge-table__th">{col}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="forge-table__row">
              {row.map((cell, j) => (
                <td key={j} className="forge-table__td">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
`;

  const css = `/* ForgeTable.css — generated by forge-ui CLI */
.forge-table-wrap {
  width: 100%;
  overflow-x: auto;
  border: 1px solid rgba(255,255,255,0.06);
  border-radius: 8px;
}

.forge-table {
  width: 100%;
  border-collapse: collapse;
  font-family: Inter, sans-serif;
}

.forge-table__caption {
  font-size: 11px;
  font-weight: 400;
  color: rgba(240,237,232,0.25);
  letter-spacing: -0.01em;
  padding: 10px 16px;
  text-align: left;
  border-bottom: 1px solid rgba(255,255,255,0.04);
}

.forge-table__th {
  padding: 10px 16px;
  font-size: 11px;
  font-weight: 400;
  color: rgba(240,237,232,0.3);
  letter-spacing: 0.04em;
  text-transform: uppercase;
  text-align: left;
  border-bottom: 1px solid rgba(255,255,255,0.06);
  background: rgba(255,255,255,0.02);
  white-space: nowrap;
}

.forge-table__td {
  padding: 12px 16px;
  font-size: 13px;
  font-weight: 300;
  color: rgba(240,237,232,0.6);
  letter-spacing: -0.01em;
  border-bottom: 1px solid rgba(255,255,255,0.04);
}

.forge-table__row:last-child .forge-table__td { border-bottom: none; }

/* Striped */
.forge-table--striped .forge-table__row:nth-child(even) .forge-table__td {
  background: rgba(255,255,255,0.02);
}

/* Hover */
.forge-table--hover .forge-table__row:hover .forge-table__td {
  background: rgba(var(--forge-table-rgb), 0.05);
  color: rgba(240,237,232,0.8);
}

/* Compact */
.forge-table--compact .forge-table__th { padding: 7px 12px; }
.forge-table--compact .forge-table__td { padding: 8px 12px; }
`;
  return { tsx, css };
}
