import { hexToRgb } from "./utils.js";

export function generateTabs(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "underline";
  const tabs = (props.tabs as string[]) ?? ["Overview", "Features", "Pricing"];

  const tsx = `// ForgeTabs — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update tabs

import { useState } from 'react'
import './ForgeTabs.css'

interface ForgeTabsProps {
  tabs?: string[]
  color?: string
  variant?: 'underline' | 'pill' | 'line'
  defaultTab?: number
  onChange?: (index: number, label: string) => void
  children?: React.ReactNode
}

export function ForgeTabs({
  tabs = ${JSON.stringify(tabs)},
  color = '${color}',
  variant = '${variant}',
  defaultTab = 0,
  onChange,
  children,
}: ForgeTabsProps) {
  const [active, setActive] = useState(defaultTab)

  function handleSelect(i: number) {
    setActive(i)
    onChange?.(i, tabs[i])
  }

  return (
    <div
      className="forge-tabs-wrap"
      style={{ '--forge-tabs-color': color, '--forge-tabs-rgb': '${rgb}' } as React.CSSProperties}
    >
      <div className={\`forge-tabs forge-tabs--\${variant}\`} role="tablist">
        {tabs.map((tab, i) => (
          <button
            key={i}
            role="tab"
            aria-selected={active === i}
            className={\`forge-tab\${active === i ? ' forge-tab--active' : ''}\`}
            onClick={() => handleSelect(i)}
          >
            {tab}
          </button>
        ))}
      </div>
      {children && (
        <div className="forge-tabs-panel" role="tabpanel">
          {children}
        </div>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeTabs.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-tabs-wrap {
  display: flex;
  flex-direction: column;
  gap: 16px;
  font-family: Inter, sans-serif;
}

.forge-tabs {
  display: flex;
  align-items: center;
}

.forge-tab {
  background: none;
  border: none;
  cursor: pointer;
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  letter-spacing: -0.01em;
  color: rgba(240, 237, 232, 0.38);
  transition: color 0.15s ease;
  padding: 8px 14px;
  white-space: nowrap;
}

.forge-tab:hover {
  color: rgba(240, 237, 232, 0.7);
}

/* Underline variant */
.forge-tabs--underline {
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
  gap: 0;
}
.forge-tabs--underline .forge-tab {
  padding: 8px 16px;
  border-bottom: 2px solid transparent;
  margin-bottom: -1px;
}
.forge-tabs--underline .forge-tab--active {
  color: var(--forge-tabs-color);
  border-bottom-color: var(--forge-tabs-color);
}

/* Pill variant */
.forge-tabs--pill {
  gap: 4px;
  background: rgba(255, 255, 255, 0.04);
  border-radius: 8px;
  padding: 3px;
}
.forge-tabs--pill .forge-tab {
  border-radius: 6px;
  padding: 6px 14px;
}
.forge-tabs--pill .forge-tab--active {
  background: rgba(var(--forge-tabs-rgb), 0.15);
  color: var(--forge-tabs-color);
}

/* Line variant */
.forge-tabs--line {
  gap: 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
}
.forge-tabs--line .forge-tab {
  padding: 8px 16px;
  position: relative;
}
.forge-tabs--line .forge-tab--active {
  color: #f0ede8;
}
.forge-tabs--line .forge-tab--active::after {
  content: '';
  position: absolute;
  bottom: -1px;
  left: 0;
  right: 0;
  height: 1px;
  background: var(--forge-tabs-color);
  box-shadow: 0 0 8px rgba(var(--forge-tabs-rgb), 0.5);
}

.forge-tabs-panel {
  color: rgba(240, 237, 232, 0.6);
  font-size: 13px;
  line-height: 1.6;
}

@media (prefers-reduced-motion: reduce) {
  .forge-tab { transition: none; }
}
`;
  return { tsx, css };
}
