import { hexToRgb } from "./utils.js";

export function generateTagInput(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "soft";
  const removable = (props.removable as boolean) ?? true;
  const placeholder = (props.placeholder as string) ?? "Add tag…";
  const initialTags = (props.tags as string[]) ?? [];

  const tsx = `// ForgeTagInput — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update taginput

import { useState, KeyboardEvent } from 'react'
import './ForgeTagInput.css'

interface ForgeTagInputProps {
  tags?: string[]
  placeholder?: string
  color?: string
  variant?: 'soft' | 'pill' | 'outline'
  removable?: boolean
  onChange?: (tags: string[]) => void
}

export function ForgeTagInput({
  tags: initialTags = ${JSON.stringify(initialTags)},
  placeholder = '${placeholder}',
  color = '${color}',
  variant = '${variant}',
  removable = ${removable},
  onChange,
}: ForgeTagInputProps) {
  const [tags, setTags] = useState<string[]>(initialTags)
  const [input, setInput] = useState('')

  function addTag() {
    const val = input.trim()
    if (val && !tags.includes(val)) {
      const next = [...tags, val]
      setTags(next)
      onChange?.(next)
    }
    setInput('')
  }

  function removeTag(i: number) {
    const next = tags.filter((_, j) => j !== i)
    setTags(next)
    onChange?.(next)
  }

  function handleKey(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault()
      addTag()
    }
    if (e.key === 'Backspace' && !input && tags.length) {
      removeTag(tags.length - 1)
    }
  }

  return (
    <div
      className="forge-taginput"
      style={{ '--forge-tag-color': color, '--forge-tag-rgb': '${rgb}' } as React.CSSProperties}
    >
      {tags.map((tag, i) => (
        <span key={i} className={\`forge-tag forge-tag--\${variant}\`}>
          {tag}
          {removable && (
            <button
              type="button"
              className="forge-tag__remove"
              onClick={() => removeTag(i)}
              aria-label={\`Remove \${tag}\`}
            >
              ✕
            </button>
          )}
        </span>
      ))}
      <input
        className="forge-taginput__input"
        value={input}
        placeholder={tags.length === 0 ? placeholder : ''}
        onChange={e => setInput(e.target.value)}
        onKeyDown={handleKey}
        onBlur={addTag}
      />
    </div>
  )
}
`;

  const css = `/* ForgeTagInput.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-taginput {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  align-items: center;
  padding: 8px 12px;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 8px;
  font-family: Inter, sans-serif;
  min-height: 42px;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}

.forge-taginput:focus-within {
  border-color: rgba(var(--forge-tag-rgb), 0.4);
  box-shadow: 0 0 0 3px rgba(var(--forge-tag-rgb), 0.1);
}

/* Tag variants */
.forge-tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  font-weight: 400;
  letter-spacing: -0.01em;
  white-space: nowrap;
}

.forge-tag--soft {
  padding: 2px 8px;
  border-radius: 4px;
  background: rgba(var(--forge-tag-rgb), 0.12);
  color: rgba(var(--forge-tag-rgb), 0.9);
  border: 1px solid transparent;
}

.forge-tag--pill {
  padding: 2px 10px;
  border-radius: 999px;
  background: rgba(var(--forge-tag-rgb), 0.12);
  color: rgba(var(--forge-tag-rgb), 0.9);
  border: 1px solid transparent;
}

.forge-tag--outline {
  padding: 2px 8px;
  border-radius: 4px;
  background: transparent;
  color: rgba(var(--forge-tag-rgb), 0.9);
  border: 1px solid rgba(var(--forge-tag-rgb), 0.3);
}

.forge-tag__remove {
  background: none;
  border: none;
  color: rgba(var(--forge-tag-rgb), 0.5);
  cursor: pointer;
  font-size: 9px;
  padding: 0;
  line-height: 1;
  transition: color 0.15s ease;
}

.forge-tag__remove:hover {
  color: rgba(var(--forge-tag-rgb), 0.9);
}

/* Input */
.forge-taginput__input {
  flex: 1;
  min-width: 80px;
  background: none;
  border: none;
  outline: none;
  color: #f0ede8;
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  letter-spacing: -0.01em;
  padding: 0;
}

.forge-taginput__input::placeholder {
  color: rgba(240, 237, 232, 0.2);
}
`;
  return { tsx, css };
}
