import { hexToRgb } from "./utils.js";

export function generateTextarea(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const radius = (props.radius as number) ?? 8;
  const rows = (props.rows as number) ?? 4;
  const showLabel = (props.showLabel as boolean) ?? true;
  const showHint = (props.showHint as boolean) ?? true;
  const showCount = (props.showCount as boolean) ?? true;
  const maxLength = (props.maxLength as number) ?? 500;
  const label = (props.label as string) ?? "Message";
  const placeholder = (props.placeholder as string) ?? "Write something…";
  const hint = (props.hint as string) ?? "";

  const tsx = `// ForgeTextarea — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update textarea

import { useState } from 'react'
import './ForgeTextarea.css'

interface ForgeTextareaProps {
  label?: string
  placeholder?: string
  hint?: string
  color?: string
  radius?: number
  rows?: number
  maxLength?: number
  showLabel?: boolean
  showHint?: boolean
  showCount?: boolean
  value?: string
  onChange?: (value: string) => void
}

export function ForgeTextarea({
  label = '${label}',
  placeholder = '${placeholder}',
  hint = '${hint}',
  color = '${color}',
  radius = ${radius},
  rows = ${rows},
  maxLength = ${maxLength},
  showLabel = ${showLabel},
  showHint = ${showHint},
  showCount = ${showCount},
  value,
  onChange,
}: ForgeTextareaProps) {
  const [internal, setInternal] = useState('')
  const controlled = value !== undefined
  const current = controlled ? value : internal

  return (
    <div
      className="forge-textarea-wrap"
      style={{ '--forge-textarea-color': color, '--forge-textarea-rgb': '${rgb}' } as React.CSSProperties}
    >
      {showLabel && label && (
        <label className="forge-textarea-label">{label}</label>
      )}
      <textarea
        className="forge-textarea"
        placeholder={placeholder}
        value={current}
        rows={rows}
        maxLength={maxLength}
        style={{ borderRadius: radius }}
        onChange={e => {
          if (!controlled) setInternal(e.target.value)
          onChange?.(e.target.value)
        }}
      />
      <div className="forge-textarea-footer">
        {showHint && hint && <span className="forge-textarea-hint">{hint}</span>}
        {showCount && (
          <span className="forge-textarea-count">{current.length} / {maxLength}</span>
        )}
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeTextarea.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-textarea-wrap {
  display: flex;
  flex-direction: column;
  gap: 5px;
  font-family: Inter, sans-serif;
  width: 100%;
}

.forge-textarea-label {
  font-size: 12px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-textarea {
  width: 100%;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  color: #f0ede8;
  font-family: Inter, sans-serif;
  font-size: 13px;
  font-weight: 400;
  letter-spacing: -0.01em;
  outline: none;
  resize: vertical;
  padding: 10px 14px;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
  box-sizing: border-box;
  line-height: 1.5;
}

.forge-textarea::placeholder {
  color: rgba(240, 237, 232, 0.2);
}

.forge-textarea:focus {
  border-color: rgba(var(--forge-textarea-rgb), 0.5);
  box-shadow: 0 0 0 3px rgba(var(--forge-textarea-rgb), 0.12);
}

.forge-textarea-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.forge-textarea-hint {
  font-size: 11px;
  color: rgba(240, 237, 232, 0.3);
  letter-spacing: -0.01em;
}

.forge-textarea-count {
  font-size: 11px;
  color: rgba(240, 237, 232, 0.2);
  letter-spacing: -0.01em;
  margin-left: auto;
}

@media (prefers-reduced-motion: reduce) {
  .forge-textarea { transition: none; }
}
`;
  return { tsx, css };
}
