import { hexToRgb } from "./utils.js";

export function generateTicker(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const speed = (props.speed as string) ?? "normal";
  const separator = (props.separator as string) ?? "—";
  const gap = (props.gap as number) ?? 48;
  const pauseOnHover = (props.pauseOnHover as boolean) ?? true;
  const items = (props.items as string[]) ?? [
    "Item one",
    "Item two",
    "Item three",
    "Item four",
  ];

  const durationMap: Record<string, string> = {
    slow: "40s",
    normal: "24s",
    fast: "14s",
  };

  const tsx = `// ForgeTicker — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update ticker
// Pure CSS infinite scroll — no JS animation required.

import './ForgeTicker.css'

interface ForgeTickerProps {
  items?: string[]
  color?: string
  speed?: 'slow' | 'normal' | 'fast'
  separator?: string
  gap?: number
  pauseOnHover?: boolean
}

export function ForgeTicker({
  items = ${JSON.stringify(items)},
  color = '${color}',
  speed = '${speed}',
  separator = '${separator}',
  gap = ${gap},
  pauseOnHover = ${pauseOnHover},
}: ForgeTickerProps) {
  // Duplicate items so the loop appears seamless
  const all = [...items, ...items]

  return (
    <div
      className="forge-ticker"
      style={{ '--forge-ticker-color': color, '--forge-ticker-rgb': '${rgb}', '--forge-ticker-gap': \`\${gap}px\` } as React.CSSProperties}
    >
      <div className={\`forge-ticker__track forge-ticker__track--\${speed}\${pauseOnHover ? ' forge-ticker__track--pausable' : ''}\`}>
        {all.map((item, i) => (
          <span key={i} className="forge-ticker__item">
            {item}
            <span className="forge-ticker__sep">{separator}</span>
          </span>
        ))}
      </div>
    </div>
  )
}
`;

  const css = `/* ForgeTicker.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-ticker {
  overflow: hidden;
  width: 100%;
  font-family: Inter, sans-serif;
  /* Fade edges */
  mask-image: linear-gradient(to right, transparent, black 10%, black 90%, transparent);
  -webkit-mask-image: linear-gradient(to right, transparent, black 10%, black 90%, transparent);
}

@keyframes forge-ticker-scroll {
  from { transform: translateX(0); }
  to   { transform: translateX(-50%); }
}

.forge-ticker__track {
  display: flex;
  width: max-content;
  gap: var(--forge-ticker-gap);
  white-space: nowrap;
}

.forge-ticker__track--slow   { animation: forge-ticker-scroll ${durationMap.slow} linear infinite; }
.forge-ticker__track--normal { animation: forge-ticker-scroll ${durationMap.normal} linear infinite; }
.forge-ticker__track--fast   { animation: forge-ticker-scroll ${durationMap.fast} linear infinite; }

.forge-ticker__track--pausable:hover {
  animation-play-state: paused;
}

.forge-ticker__item {
  display: inline-flex;
  align-items: center;
  gap: var(--forge-ticker-gap);
  font-size: 13px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.5);
  letter-spacing: -0.01em;
}

.forge-ticker__sep {
  color: rgba(var(--forge-ticker-rgb), 0.4);
  font-size: 11px;
}

@media (prefers-reduced-motion: reduce) {
  .forge-ticker__track { animation: none; }
}
`;
  return { tsx, css };
}
