export function generateToast(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const variant = (props.variant as string) ?? "success";
  const showIcon = (props.showIcon as boolean) ?? true;
  const showClose = (props.showClose as boolean) ?? true;

  const tsx = `// ForgeToast — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update toast

import { useState } from 'react'
import './ForgeToast.css'

type ToastVariant = 'success' | 'error' | 'warning' | 'info'

interface ForgeToastProps {
  title?: string
  message?: string
  variant?: ToastVariant
  showIcon?: boolean
  showClose?: boolean
  onClose?: () => void
}

const ICONS: Record<ToastVariant, string> = {
  success: '✓',
  error: '✕',
  warning: '⚠',
  info: 'i',
}

export function ForgeToast({
  title = 'Notification',
  message,
  variant = '${variant}',
  showIcon = ${showIcon},
  showClose = ${showClose},
  onClose,
}: ForgeToastProps) {
  const [visible, setVisible] = useState(true)

  function handleClose() {
    setVisible(false)
    onClose?.()
  }

  if (!visible) return null

  return (
    <div className={\`forge-toast forge-toast--\${variant}\`} role="alert">
      {showIcon && (
        <span className="forge-toast__icon">{ICONS[variant]}</span>
      )}
      <div className="forge-toast__content">
        <div className="forge-toast__title">{title}</div>
        {message && <div className="forge-toast__message">{message}</div>}
      </div>
      {showClose && (
        <button className="forge-toast__close" onClick={handleClose} aria-label="Dismiss">✕</button>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeToast.css — generated by forge-ui CLI */
.forge-toast {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 12px 16px;
  border-radius: 8px;
  border: 1px solid;
  font-family: Inter, sans-serif;
  max-width: 360px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.3);
}

.forge-toast--success { background: rgba(29,158,117,0.1);  border-color: rgba(29,158,117,0.25);  }
.forge-toast--error   { background: rgba(226,75,74,0.1);   border-color: rgba(226,75,74,0.25);   }
.forge-toast--warning { background: rgba(239,159,39,0.1);  border-color: rgba(239,159,39,0.25);  }
.forge-toast--info    { background: rgba(55,138,221,0.1);  border-color: rgba(55,138,221,0.25);  }

.forge-toast__icon {
  font-size: 13px;
  flex-shrink: 0;
  margin-top: 1px;
}
.forge-toast--success .forge-toast__icon { color: #1D9E75; }
.forge-toast--error   .forge-toast__icon { color: #e24b4a; }
.forge-toast--warning .forge-toast__icon { color: #EF9F27; }
.forge-toast--info    .forge-toast__icon { color: #378ADD; }

.forge-toast__content { flex: 1; }

.forge-toast__title {
  font-size: 13px;
  font-weight: 400;
  color: #f0ede8;
  letter-spacing: -0.01em;
}

.forge-toast__message {
  font-size: 12px;
  font-weight: 300;
  color: rgba(240,237,232,0.5);
  letter-spacing: -0.01em;
  margin-top: 2px;
  line-height: 1.5;
}

.forge-toast__close {
  background: none;
  border: none;
  color: rgba(240,237,232,0.3);
  cursor: pointer;
  font-size: 11px;
  padding: 0;
  flex-shrink: 0;
  transition: color 0.15s ease;
}
.forge-toast__close:hover { color: #f0ede8; }
`;
  return { tsx, css };
}
