import { hexToRgb } from "./utils.js";

export function generateToggle(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const size = (props.size as string) ?? "md";
  const checked = (props.checked as boolean) ?? false;
  const showLabel = (props.showLabel as boolean) ?? true;
  const label = (props.label as string) ?? "Toggle";
  const labelPos = (props.labelPos as string) ?? "right";

  const trackMap: Record<string, { w: string; h: string; thumb: string }> = {
    sm: { w: "28px", h: "16px", thumb: "10px" },
    md: { w: "36px", h: "20px", thumb: "14px" },
    lg: { w: "44px", h: "24px", thumb: "18px" },
  };
  const t = trackMap[size] ?? trackMap.md;

  const tsx = `// ForgeToggle — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update toggle

import { useState } from 'react'
import './ForgeToggle.css'

interface ForgeToggleProps {
  label?: string
  color?: string
  size?: 'sm' | 'md' | 'lg'
  checked?: boolean
  showLabel?: boolean
  labelPos?: 'left' | 'right'
  onChange?: (checked: boolean) => void
}

export function ForgeToggle({
  label = '${label}',
  color = '${color}',
  size = '${size}',
  checked,
  showLabel = ${showLabel},
  labelPos = '${labelPos}',
  onChange,
}: ForgeToggleProps) {
  const [internal, setInternal] = useState(${checked})
  const controlled = checked !== undefined
  const active = controlled ? checked : internal

  function handleClick() {
    if (!controlled) setInternal(v => !v)
    onChange?.(!active)
  }

  return (
    <div
      className={\`forge-toggle-wrap forge-toggle-wrap--\${labelPos}\`}
      style={{ '--forge-toggle-color': color, '--forge-toggle-rgb': '${rgb}' } as React.CSSProperties}
      onClick={handleClick}
    >
      {showLabel && labelPos === 'left' && (
        <span className="forge-toggle-label">{label}</span>
      )}
      <div className={\`forge-toggle forge-toggle--\${size}\${active ? ' forge-toggle--on' : ''}\`}>
        <div className="forge-toggle__thumb" />
      </div>
      {showLabel && labelPos === 'right' && (
        <span className="forge-toggle-label">{label}</span>
      )}
    </div>
  )
}
`;

  const css = `/* ForgeToggle.css — generated by forge-ui CLI */
/* Edit freely — you own this file. */

.forge-toggle-wrap {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  user-select: none;
  font-family: Inter, sans-serif;
}

.forge-toggle-label {
  font-size: 13px;
  font-weight: 400;
  color: rgba(240, 237, 232, 0.6);
  letter-spacing: -0.01em;
}

.forge-toggle {
  position: relative;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.08);
  border: 1px solid rgba(255, 255, 255, 0.1);
  transition: background 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease;
  flex-shrink: 0;
}

.forge-toggle--sm { width: ${t.w}; height: ${t.h}; }
.forge-toggle--md { width: ${trackMap.md.w}; height: ${trackMap.md.h}; }
.forge-toggle--lg { width: ${trackMap.lg.w}; height: ${trackMap.lg.h}; }

.forge-toggle__thumb {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  left: 2px;
  border-radius: 50%;
  background: rgba(240, 237, 232, 0.4);
  transition: left 0.2s ease, background 0.2s ease, width 0.1s ease;
}

.forge-toggle--sm .forge-toggle__thumb { width: ${trackMap.sm.thumb}; height: ${trackMap.sm.thumb}; }
.forge-toggle--md .forge-toggle__thumb { width: ${trackMap.md.thumb}; height: ${trackMap.md.thumb}; }
.forge-toggle--lg .forge-toggle__thumb { width: ${trackMap.lg.thumb}; height: ${trackMap.lg.thumb}; }

/* On state */
.forge-toggle--on {
  background: rgba(var(--forge-toggle-rgb), 0.25);
  border-color: rgba(var(--forge-toggle-rgb), 0.5);
  box-shadow: 0 0 12px rgba(var(--forge-toggle-rgb), 0.2);
}
.forge-toggle--sm.forge-toggle--on .forge-toggle__thumb {
  left: calc(${t.w} - ${trackMap.sm.thumb} - 2px);
  background: var(--forge-toggle-color);
}
.forge-toggle--md.forge-toggle--on .forge-toggle__thumb {
  left: calc(${trackMap.md.w} - ${trackMap.md.thumb} - 2px);
  background: var(--forge-toggle-color);
}
.forge-toggle--lg.forge-toggle--on .forge-toggle__thumb {
  left: calc(${trackMap.lg.w} - ${trackMap.lg.thumb} - 2px);
  background: var(--forge-toggle-color);
}

@media (prefers-reduced-motion: reduce) {
  .forge-toggle, .forge-toggle__thumb { transition: none; }
}
`;
  return { tsx, css };
}
