import { hexToRgb } from "./utils.js";

export function generateTooltip(props: Record<string, unknown>): {
  tsx: string;
  css: string;
} {
  const color = (props.color as string) ?? "#7F77DD";
  const rgb = hexToRgb(color);
  const variant = (props.variant as string) ?? "dark";

  const tsx = `// ForgeTooltip — generated by forge-ui CLI
// Edit this file freely — you own it.
// Re-generate with: npx @forgelabs-studio/ui update tooltip

import { useState } from 'react'
import './ForgeTooltip.css'

interface ForgeTooltipProps {
  tip: string
  children: React.ReactNode
  color?: string
  variant?: 'dark' | 'light'
  position?: 'top' | 'bottom' | 'left' | 'right'
}

export function ForgeTooltip({
  tip,
  children,
  color = '${color}',
  variant = '${variant}',
  position = 'top',
}: ForgeTooltipProps) {
  const [visible, setVisible] = useState(false)

  return (
    <span
      className="forge-tooltip-wrap"
      style={{ '--forge-tooltip-color': color, '--forge-tooltip-rgb': '${rgb}' } as React.CSSProperties}
      onMouseEnter={() => setVisible(true)}
      onMouseLeave={() => setVisible(false)}
      onFocus={() => setVisible(true)}
      onBlur={() => setVisible(false)}
    >
      {children}
      {visible && (
        <span className={\`forge-tooltip forge-tooltip--\${variant} forge-tooltip--\${position}\`} role="tooltip">
          {tip}
        </span>
      )}
    </span>
  )
}
`;

  const css = `/* ForgeTooltip.css — generated by forge-ui CLI */
.forge-tooltip-wrap {
  position: relative;
  display: inline-flex;
  align-items: center;
}

.forge-tooltip {
  position: absolute;
  z-index: 50;
  white-space: nowrap;
  font-family: Inter, sans-serif;
  font-size: 11px;
  font-weight: 400;
  letter-spacing: -0.01em;
  padding: 5px 10px;
  border-radius: 5px;
  pointer-events: none;
}

.forge-tooltip--dark {
  background: #1a1a1f;
  color: rgba(240,237,232,0.8);
  border: 1px solid rgba(255,255,255,0.08);
}

.forge-tooltip--light {
  background: #f0ede8;
  color: #09090b;
  border: 1px solid rgba(0,0,0,0.08);
}

.forge-tooltip--top    { bottom: calc(100% + 6px); left: 50%; transform: translateX(-50%); }
.forge-tooltip--bottom { top: calc(100% + 6px);    left: 50%; transform: translateX(-50%); }
.forge-tooltip--left   { right: calc(100% + 6px);  top: 50%;  transform: translateY(-50%); }
.forge-tooltip--right  { left: calc(100% + 6px);   top: 50%;  transform: translateY(-50%); }
`;
  return { tsx, css };
}
